hirosystems/stacks-blockchain-api

.env, .eslintignore, .vscode/launch.json, migrations/1584604583726_blocks.ts, migrations/1584619633448_txs.ts, package-lock.json, package.json, src/datastore/common.ts, src/datastore/memory-store.ts, src/datastore/postgres-store.ts, src/event-stream/core-node-message.ts, src/helpers.ts, src/index.ts, src/p2p/tx.ts, tests/datastore-tests.ts
* Closes https://github.com/blockstack/blockstack-core-sidecar/issues/12: Consume core-node socket messages
* Closes https://github.com/blockstack/blockstack-core-sidecar/issues/15: Consume Clarity values from core-node stream
* Progress on https://github.com/blockstack/blockstack-core-sidecar/issues/10: Define db schema
* Progress on https://github.com/blockstack/blockstack-core-sidecar/issues/8: Fork-tolerance, determine and pressure test approaches
The core-node event stream payloads are about finalized in PR https://github.com/blockstack/stacks-blockchain/pull/1319. This PR consumes all available core-node msg data and transforms into database-ready objects. 
Blocks, transactions, token events, and smart-contract events are transformed into a WIP db structure, along with some naive …
=> Near-finalized ingest of core-node socket data

.github/workflows/linting.yml, .vscode/launch.json, .vscode/tasks.json, docs/api/transaction/get-transactions.schema.json, docs/entities/transactions/abstract-transaction.schema.json, docs/entities/transactions/abstract-tx-event.schema.json, docs/entities/transactions/transaction-0-token-transfer.schema.json, docs/entities/transactions/transaction-1-smart-contract.schema.json, docs/entities/transactions/transaction-2-contract-call.schema.json, docs/entities/transactions/transaction-3-poison-microblock.schema.json, docs/entities/transactions/transaction-4-coinbase.schema.json, docs/entities/transactions/transaction-status.schema.json, docs/entities/transactions/transaction.schema.json, docs/openapi.yaml, docs/package.json, gulpfile.js, package-lock.json, package.json, scripts/generate-types.ts, scripts/validate-schemas.ts, src/api/routes/tx.ts, src/api/validate.ts, src/index.ts, tsconfig.json
- Improves generation of types, less redundancy in output file.
- Adds CI job to validate examples
- Uses a load of npm packages, but flow actually works pretty nice (previously derefing was done with gulp task before):
1. Parse and de-`$ref` the schema files with [`@apidevtools/json-schema-ref-parser`](https://github.com/APIDevTools/json-schema-ref-parser)
2. Use [`json-schema-merge-allof`](https://github.com/mokkabonna/json-schema-merge-allof) to merge `allOf` with some sensible logic that ignores `additionalProperties: false`
3. Compile them to TypeScript types with [`json-schema-to-typescript`](https://github.com/bcherny/json-schema-to-typescript)
- Manually publishing types package for now
- Adds schema validation to `/tx` and `/tx/:tx_id` routes in dev mode
[See new output types …
=> refactor: type generation

src/api/init.ts, src/api/routes/contract.ts
Minor sidecar API feature to include a GET `/contract/:contract-id` endpoint
=> feat: add GET contract API endpoint

src/api/controllers/db-controller.ts, src/datastore/common.ts, src/p2p/tx.ts
* Encode the `contract-call` function args as into a flat value for db storage (using Clarity list encoding)
* Fix couple bugs with Clarity value deserialization not incrementing the buffer reader pointer
=> Flatten contract-call fn args for db storage

src/api/routes/core-node-rpc-proxy.ts
Fix the 504 errors when the core-node RPC server takes several seconds to respond
=> increase core-node RPC proxy timeout

src/api/routes/debug.ts
Forgot to include this functionality.
Also, can we setup the ENV variable with a private key for a genesis block address? So we can fully wire this up?
=> feat: broadcast from faucet

.gitignore, src/datastore/common.ts
`addressFromHashMode` needs to be wrapped in `addressToString`. Currently it returns `[object Object]`
=> Fix: sender address in contract name

docs/entities/transactions/transaction-type.schema.json, docs/package.json
This PR creates a string literal for tx types, available in `@blockstack/stacks-blockchain-sidecar-types` package
=> feat: add string literal type for tx_type

package-lock.json, src/api/controllers/db-controller.ts, src/api/routes/tx.ts, src/datastore/common.ts, src/datastore/memory-store.ts, src/datastore/postgres-store.ts
A few changes that I hope you're onboard with @zone117x 
- Omit type repetition: imo less error-prone and easier to read relying on the implemented types in `./common.ts`, than retyping. See use of `as const` where necessary. This is equally as type strong.
- Alternate between result and results. Don't think consistency is necessary here, favouring readability, but if you disagree, maybe we can choose another name altogether?
- Schema validation works now 👍
=> feat: conform to schema

codecov.yml, src/api/routes/tx.ts, src/helpers.ts, src/tests/helpers-tests.ts
Minor update but hopefully a helpful one. Added this as noticed that `broadcastTransaction` from stacks-transaction returns non-prefixed txid.
=> feat: add hex prefix if not given, dev-friendly

tsconfig.json
I was getting errors running the sidecar in dev mode because it could not find the types we have for `coinselect`. This fixes the dev task.
=> fix: use paths to find custom types

src/btc-faucet.ts, src/helpers.ts
Noticed that the faucet RPC requests on staging are sometimes timing out. Implementing the following to help diagnose and possibly fix the issue:
1. Increased logging around each RPC request.
2. Batching `getrawtransaction` requests.
=> Batch bitcoin RPC requests

docs/entities/post-conditions/post-condition-2-non-fungible.schema.json, docs/entities/transaction-events/transaction-event-non-fungible-asset.schema.json, docs/entities/transaction-events/transaction-event-smart-contract-log.schema.json, docs/entities/transactions/transaction-2-contract-call.schema.json, package-lock.json, package.json, src/api/controllers/db-controller.ts, src/api/routes/debug.ts, src/api/serializers/post-conditions.ts, src/core-rpc/client.ts, src/tests/api-tests.ts
Closes https://github.com/blockstack/stacks-blockchain-sidecar/issues/99 - Clarity values should be returned as repr strings
All API responses which previously returned a hex string for Clarity values now returns an object:
```ts
{
hex: string, // the raw value as a hex string
repr: string // the new repr string
}
```
Updated fields:
* asset value in post conditions for non-fungible tokens
* asset value in non-fungible token transfer events
* contract log value in smart contract log events
* function arg values in contract call transactions
=> Clarity values returned as repr strings

package-lock.json, package.json
Ref: https://github.com/blockstack/stacks-blockchain-sidecar/issues/99
Now that https://github.com/blockstack/stacks-transactions-js/pull/83 is merged
=> chore: point stx-tx lib to latest master

docs/entities/transactions/transaction-2-contract-call.schema.json, docs/index.d.ts, docs/package.json, package-lock.json, package.json, src/api/controllers/db-controller.ts, src/tests/api-tests.ts
Closes https://github.com/blockstack/stacks-blockchain-sidecar/issues/101
Contract-call tx response objects now include more function data:
* Function signature (the Clarity function repr string)
* Function arg names and type repr strings
Examples:
```js
contract_call: {
contract_id: 'ST11NJTTKGVT6D1HY4NJRVQWMQM7TVAR091EJ8P2Y.hello-world',
function_name: 'fn-name',
function_signature: '(define-public (fn-name (arg1 int)))',
function_args: [
{
hex: '0x000000000000000000000000000000022c',
repr: '556',
name: 'arg1',
type: 'int',
},
],
},
```
```js
contract_call: {
contract_id: 'STB44HYPYAT2BB2QE513NSP81HTMYWBJP02HPGK6.hello-world-contract',
function_name: 'set-value',
function_signature: '(define-public (set-value (key (buff 32)) (value (buff 32))))',
function_args: [
{
hex: …
```
=> Add function summary data to contract-call tx response

src/api/routes/block.ts, src/datastore/common.ts, src/datastore/memory-store.ts, src/datastore/postgres-store.ts
Closes https://github.com/blockstack/stacks-blockchain-sidecar/issues/120
* Adds pagination support to the list-blocks API endpoint
* Latest 20 blocks are returned by default
=> feat: add block list API limit and offset query

src/api/controllers/db-controller.ts, src/api/routes/tx.ts, src/datastore/common.ts, src/datastore/memory-store.ts, src/datastore/postgres-store.ts, src/tests/api-tests.ts
Closes https://github.com/blockstack/stacks-blockchain-sidecar/issues/98
The recent transaction list API can use query param arrays to filter by type. The Express query param array formats are supported. Example usage:
* `/sidecar/v1/tx?type=token_transfer`
* `/sidecar/v1/tx?type=contract_call&type=smart_contract`
* `/sidecar/v1/tx?type[]=contract_call&type[]=smart_contract`
=> feat: ability to filter tx list by types

docs/entities/transactions/transaction-status.schema.json, docs/index.d.ts, src/api/controllers/db-controller.ts, src/datastore/common.ts, src/datastore/memory-store.ts, src/datastore/postgres-store.ts, src/event-stream/core-node-message.ts, src/tests/api-tests.ts, src/tests/datastore-tests.ts
Reference: https://github.com/blockstack/stacks-blockchain/pull/1612
Closes: https://github.com/blockstack/stacks-blockchain-sidecar/issues/97
The `tx_status` field is now one of the following values: `success`, `abort_by_response`, or `abort_by_post_condition`.
Note that `failed` is no longer a possible value. 
See https://github.com/blockstack/stacks-blockchain/pull/1612 for description of the abort value meanings.
=> Include tx failed status code

package-lock.json, package.json, src/api/init.ts, src/event-stream/event-server.ts, src/helpers.ts, src/index.ts, src/tests/api-tests.ts, src/tests/faucet-tests.ts, src/tests/setup.ts, src/tests/websocket-tests.ts
This PR adds a websocket server that can be accessed via the endpoint `ws://<sidecar-address>/sidecar/v1`. Clients can use this endpoint to open a websocket connection to the sidecar. They can subscribe to transactions by sending a message containing just a `txid` to the server via the websocket connection. Once subscribed to a transaction, the server will stream updates to the client when the state of the transaction changes.
Example client usage with [ws](https://github.com/websockets/ws):
```javascript
const WebSocket = require('ws');
const ws = new WebSocket(`ws://localhost:3999/sidecar/v1`);
// subscribe to tx once connection is open
ws.on('open', function open() {
ws.send('0x54da30065d7265347c43f5a6e9ec5f3a7409d802b0c5eb8e72735fec364fe075');
});
// log updates to the subscribed tx …
```
=> feat: Transaction Updates via Websockets

docs/package-lock.json, package-lock.json, src/datastore/common.ts, src/datastore/postgres-store.ts, src/event-stream/core-node-message.ts, src/event-stream/event-server.ts, src/event-stream/reader.ts, src/migrations/1593523025263_raw_tx_data.ts, src/tests/api-tests.ts, src/tests/datastore-tests.ts
Closes https://github.com/blockstack/stacks-blockchain-sidecar/issues/149
Raw transaction bytes are now stored in the tx and mempool tx tables.
=> feat: store raw tx bytes in db

src/api/routes/address.ts, src/api/routes/contract.ts, src/datastore/common.ts, src/datastore/memory-store.ts, src/datastore/postgres-store.ts, src/helpers.ts, src/tests/api-tests.ts
Closes https://github.com/blockstack/stacks-blockchain-sidecar/issues/150
Closes https://github.com/blockstack/stacks-blockchain-sidecar/issues/141
Closes https://github.com/blockstack/stacks-blockchain-sidecar/issues/148
This PR creates a new endpoint that returns the contract-log-events emitted on a given contract:
`GET /sidecar/v1/contract/<contract_id>/events` 
* `limit` and `offset` query params supported.
* Ordered by most recent -- DESC block height, tx index, event index.
Example: `/sidecar/v1/contract/hello-world/events?limit=20&offset=0`
```ts
{
limit: 20,
offset: 0,
results: [
{
event_index: 4,
event_type: 'smart_contract_log',
contract_log: {
contract_id: 'hello-world',
topic: 'print', // note that the Clarity `print` statement is the only possibly event topic for now
value: { …
```
=> feat: contract event enumeration endpoint

src/datastore/postgres-store.ts, src/migrations/1584619633448_txs.ts
Adds missing `contract-call` and `contract-deploy` txs to the `/address/:contract/transactions` endpoint response. 
Thx @hstove for finding this bug.
=> Fix address endpoint missing contract-calls and contract-deploys txs

docs/entities/blocks/block.schema.json, docs/entities/mempool-transactions/abstract-transaction.schema.json, docs/entities/transactions/abstract-transaction.schema.json, docs/index.d.ts, src/api/controllers/db-controller.ts, src/helpers.ts, src/tests/api-tests.ts
Closes https://github.com/blockstack/stacks-blockchain-sidecar/issues/157
All API response objects that include a unix timestamp now also include an [ISO 8601](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Date/toISOString) encoded value. This provides a more readable date, and in a standardized date format, especially for JS projects, e.g. `new Date(resp.timestamp_iso)` just works.
* `block` response objects now include both a `receipt_time` and `receipt_time_iso` value, e.g.:
```js
{
burn_block_time: 1594307695,
burn_block_time_iso: '2020-07-09T15:14:55.000Z' 
}
```
* `transaction` (mined) response objects now include both a `receipt_time` and `receipt_time_iso` value, e.g.:
```js
{
burn_block_time: 1594307695,
burn_block_time_iso: …
```
=> Include ISO 8601 formatted timestamps alongside unix epochs

docs/api/address/get-address-stx-balance.example.json, docs/api/address/get-address-stx-balance.schema.json, docs/api/address/get-address-transactions.schema.json, docs/index.d.ts, docs/openapi.yaml, src/api/routes/address.ts, src/datastore/postgres-store.ts, src/tests/api-tests.ts, src/tests/datastore-tests.ts
Fixed bug where address STX balance value was not taking fees into account.
Also added a new API for STX-only wallets which doesn't perform queries on FTs/NFTs: `/extended/v1/address/{principal}/stx`
=> fix: make address stx balance take fees into account

docs/entities/mempool-transactions/abstract-transaction.schema.json, docs/entities/transactions/abstract-transaction.schema.json, docs/index.d.ts, docs/package-lock.json, package-lock.json, package.json, src/api/controllers/db-controller.ts, src/api/init.ts, src/api/routes/debug.ts, src/datastore/common.ts, src/datastore/postgres-store.ts, src/event-stream/core-node-message.ts, src/event-stream/event-server.ts, src/event-stream/reader.ts, src/migrations/1593415759720_add-txs-raw-result.ts, src/migrations/1595337815840_sponsored_tx.ts, src/tests/api-tests.ts
Depends on https://github.com/blockstack/stacks-transactions-js/pull/99
This PR updates the sidecar to support processing and returning sponsored tx data. 
The `/sidecar/v1/debug/broadcast` endpoints now have a checkbox to create and broadcast a sponsored transaction. 
For example: 
* Visit `http://localhost:3999/sidecar/v1/debug/broadcast/contract-deploy`
* Check `[x] Create sponsored transaction` and click Submit
* The tx response will then contain sponsored tx info, for example: 
```js
// localhost:3999/sidecar/v1/tx/0x2537c7090545c01db3f86300efb75b72e07695c6d4bf5358d218242d2da859a1
{
...
"sponsored": true,
"sponsor_address": "STRYYQQ9M8KAF4NS7WNZQYY59X93XEKR31JP64CP",
...
}
```
=> Support sponsored transactions

rosetta-cli-config/bootstrap_balances.json, rosetta-cli-config/exempt_accounts.json, rosetta-cli-config/rosetta-config.json, src/api/init.ts, src/api/rosetta-constants.ts, src/api/routes/rosetta/account.ts, src/api/routes/rosetta/block.ts, src/api/routes/rosetta/mempool.ts, src/api/routes/rosetta/network.ts
This PR contains the implementation for two Rosetta API endpoints -- `/network/list` and `/network/options` -- and stubs for the others.
`/network/status` is not included in this PR because it requires several changes to the datastore interface, and to the postgres and memory store implementations.
Type information is not present because that requires a large number of entity/schema files.  That's in the next pull request.
The rosetta config files are included, and `rosetta-cli --configuration-file rosetta-cli-config/rosetta-config.json view:networks` can test the implemented endpoints.
=> rosetta api: base

.dockerignore, .github/workflows/stacks-blockchain-api.yml, docker-compose.dev.stacks-blockchain-follower.yml, docker-compose.dev.stacks-blockchain.yml, docker-compose.follower.yml, docker-compose.yml, follower.Dockerfile, package.json, readme.md, src/datastore/postgres-store.ts, stacks-blockchain/Stacks-follower.toml, stacks-blockchain/dist-tool/index.js, stacks-blockchain/docker/Dockerfile
Closes https://github.com/blockstack/stacks-blockchain-api/issues/184
A self-contained Docker image which will start a Stacks 2.0 blockchain and API testnet.
```
docker run -p 3999:3999 blockstack/stacks-blockchain-api-standalone
```
Once the blockchain has synced with network, the API will be available at:
[http://localhost:3999](http://localhost:3999)
When the core-node exits (due to chain reset or any other reason), the API service and postgres is stopped, data is wiped, and the whole thing is restarted. This behavior can be tested by entering shell for a running image and killing the `stacks-node` process e.g. `pkill -9 stacks-node`
=> Self contained follower

follower.Dockerfile, readme.md
Add option to start the standalone image using local mocknet.
```
docker run -p 3999:3999 blockstack/stacks-blockchain-api-standalone mocknet
```
=> feat: option to start the self-contained image in mocknet mode

src/event-stream/core-node-message.ts, src/event-stream/event-server.ts
Noop handler for the stx-lock-event introduced in https://github.com/blockstack/stacks-blockchain/pull/1899
This _should_ prevent rejects when the event is received.
=> noop handler for STXLockEvent

docs/openapi.yaml, src/api/routes/faucets.ts, src/helpers.ts
Closes #247
* Update the STX faucet endpoint default amount to 500 stx, and the original 5 requests with 5 minute cooldown.
* Added an optional param `stacking=true` to the endpoint which sends the Stacking amount, and has a 48 hour cooldown.
The default behavior is the non-stacking amount.
Regular STX amount request, several can be made within rolling 5 minute window:
```shell
curl -L -d POST \
"http://localhost:3999/extended/v1/faucets/stx?address=STRYYQQ9M8KAF4NS7WNZQYY59X93XEKR31JP64CP"
```
Stacking STX amount request, 1 per 48 hours:
```shell
curl -L -d POST \
"http://localhost:3999/extended/v1/faucets/stx?address=STRYYQQ9M8KAF4NS7WNZQYY59X93XEKR31JP64CP&stacking=true"
```
=> STX faucet Stacking differentiation

client/package.json, client/src/generated/apis/SmartContractsApi.ts, client/test/test.ts, docs/openapi.yaml
This PR
* renames `stacks_address` to `contract_address` in contract related rpc calls
* renames `principal_address` to `contract_address` in the documentation
* fixes #258
=> chore(openapi): use contract_address only #258

docs/openapi.yaml
I used multiple tags for the Rosetta endpoints.  I'm not sure if that's the right thing to do.
Documented:
=> add openapi docs for rosetta endpoints

docs/api/rosetta/rosetta-construction-combine-request.schema.json, docs/api/rosetta/rosetta-construction-combine-response.schema.json, docs/api/rosetta/rosetta-construction-payloads-request.schema.json, docs/api/rosetta/rosetta-construction-payloads-response.schema.json, docs/entities/rosetta/rosetta-signature-type.schema.json, docs/entities/rosetta/rosetta-signature.schema.json, docs/entities/rosetta/rosetta-signing-payload.schema.json, docs/index.d.ts, docs/openapi.yaml, src/api/rosetta-constants.ts, src/api/routes/rosetta/construction.ts, src/rosetta-helpers.ts, src/tests-rosetta/api.ts
-implment construction/payloads endpoint 
-unit test coveratge
-implment construction/combine endpoint 
-unit test coveratge
=> Implementation of construction/payloads and construction/combine endpoints

client/src/generated/apis/FeesApi.ts, docs/api/core-node/get-fee-transfer.schema.json, docs/index.d.ts, docs/openapi.yaml
without this, the response is simply undefined
=> fix: adding schema for fee estimates

client/package-lock.json, client/src/generated/models/Block.ts, docker-compose.yml, docs/entities/blocks/block.example.json, docs/entities/blocks/block.schema.json, docs/index.d.ts, follower.Dockerfile, package.json, src/api/controllers/db-controller.ts, src/datastore/common.ts, src/datastore/postgres-store.ts, src/event-stream/core-node-message.ts, src/event-stream/event-server.ts, src/migrations/1584604583726_blocks.ts, src/tests/api-tests.ts, src/tests/datastore-tests.ts, src/tests/websocket-tests.ts, stacks-blockchain/docker/Dockerfile
Closes https://github.com/blockstack/stacks-blockchain-api/issues/302
Adds the new bitcoin fields to the block API: `burn_block_hash`, `burn_block_height`, `miner_txid`
Also switch the docker setup to pull the `stacks-node` binary from the official docker hub images. Updated to the latest build which closes https://github.com/blockstack/stacks-blockchain-api/issues/301
=> Expose btc info

docs/openapi.yaml
The design details will now be explained in the API guide inside the docs.
No
=> docs: remove design chapter form api spec

client/src/generated/apis/BlocksApi.ts, docs/openapi.yaml, src/api/routes/block.ts
As a developer, I don't want to relearn the API for different clients (RPC vs js lib)
This PR
* renames the block hash parameter in the RPC API from `block_hash` to `hash`
* fixes issue #262 
no
new client docs 
Provide context on how tests should be performed.
1. Is testing required for this change?
2. If it’s a bug fix, list steps to reproduce the bug
3. Briefly mention affected code paths
4. List other affected projects if possible
5. Things to watch out for when testing
=> chore: rename block_hash to hash

rosetta-cli-config/bootstrap_balances.json, src/datastore/postgres-store.ts, src/rosetta-helpers.ts, src/tests-rosetta/api.ts, stx-rosetta.Dockerfile
* A few transactions on the testnet have contract function calls without arguments.  The code to handle this for rosetta's `/block` endpoint didn't expect that case, and handled it incorrectly by throwing an exception.  This is a one-line fix, and probably a **high priority** one (breaks `rosetta-cli`'s `check:data`).
This can be seen by trying
```
curl -s -H 'content-type: application/json' \
-d '{"network_identifier": {"blockchain": "stacks", "network": "testnet"}, "block_identifier": {"index": 1209}}' \
https://stacks-node-api.blockstack.org/rosetta/v1/block
curl -s -H 'content-type: application/json' \
-d '{"network_identifier": {"blockchain": "stacks", "network": "testnet"}, "block_identifier": {"index": 1210}}' \
https://stacks-node-api.blockstack.org/rosetta/v1/block
curl -s -H …
```
=> three rosetta fixes: API_TAG in stx-rosetta, contract function args, and fees calculation.

src/event-stream/core-node-message.ts, src/event-stream/event-server.ts
Stub response for the `/new_burn_block` event. Allows the sidecar to run with latest core-node (v23.0.0.11-krypton).
=> Stub response for `/new_burn_block`

client/src/generated/models/AddressBalanceResponseStx.ts, client/src/generated/models/AddressStxBalanceResponse.ts, docs/entities/balance/stx-balance.schema.json, docs/index.d.ts, src/api/routes/address.ts, src/datastore/common.ts, src/datastore/postgres-store.ts, src/event-stream/core-node-message.ts, src/event-stream/event-server.ts, src/migrations/1605184662317_miner_rewards.ts, src/tests/api-tests.ts, src/tests/datastore-tests.ts, src/tests/websocket-tests.ts
Closes #314 - Balance reported by API does not match balance reported by miner/follower
The various STX balance endpoints now return the structure:
```ts
type StxBalance = {
locked: string;
unlock_height: number;
total_sent: string;
total_received: string;
total_fees_sent: string; // NEW
total_miner_rewards_received: string; // NEW
balance: string; // Now returns an accurate balance with rewards factored in
}
```
=> Miner STX reward event handling

src/helpers.ts
Closes #322 - Search endpoint not recognizing short contract names
Contract names were previously required to be at least 5 chars long. This is not the case with the `pox` contract, and perhaps no longer the case at all in core. Either way, the restriction was unnecessary.
=> fix: contract names can be less than 5 chars

docker-compose.dev.postgres.yml, src/datastore/common.ts, src/datastore/postgres-store.ts, src/migrations/1591291822107_mempool_txs.ts, src/tests-rosetta/api.ts, src/tests/api-tests.ts, src/tests/datastore-tests.ts, src/tests/websocket-tests.ts
Closes https://github.com/blockstack/stacks-blockchain-api/issues/333 - Disappearing Mempool TX
This was a bug in the sidecar's handling of mempool transactions. Transactions were not "re-inserted" into the mempool in the event that the block they were mined in became non-canonical.
=> Fix mempool transaction disappear during re-orgs

src/datastore/postgres-store.ts
Closes #343
Closes #344
Updates the query to check the burnchain tip against a stx unlock height rather than using the STX chain tip.
=> Fix locked STX bugs

client/src/generated/models/AddressBalanceResponseStx.ts, client/src/generated/models/AddressStxBalanceResponse.ts, docs/api/address/get-address-balances.example.json, docs/api/address/get-address-stx-balance.example.json, docs/entities/balance/stx-balance.schema.json, docs/index.d.ts, src/api/routes/address.ts, src/datastore/common.ts, src/datastore/postgres-store.ts, src/tests/api-tests.ts, src/tests/datastore-tests.ts, src/tests/websocket-tests.ts
Closes #340
Adds both lock height (for both burnchain and Stacks chain), as well as the associated lockup txid.
Also clarifies that the unlock height refers to the burnchain by renaming to `burnchain_unlock_height`.
The new response interface:
```ts
interface Balance {
balance: string;
total_sent: string;
total_received: string;
total_fees_sent: string;
total_miner_rewards_received: string;
/**
* The transaction where the lock event occurred. Empty if no tokens are locked.
*/
lock_tx_id: string;
/**
* The amount of locked STX, as string quoted micro-STX. Zero if no tokens are locked.
*/
locked: string;
/**
* The STX chain block height of when the lock event occurred. Zero if no tokens are locked.
*/
lock_height: number;
/**
* The burnchain block height of when the lock event occurred. …
```
=> Add locked height and locked txid to balance endpoints

src/datastore/postgres-store.ts
A couple endpoints that return the stx-mint events for the genesis transaction are currently extremely resource intensive due to loading in ~330k at once. This is a temporary fix by adding a 200 limit to the amount of stx-asset events returned for a given transaction.
A permanent fix is could be to simply not return events for these special massive genesis transactions, as I don't think there's a real need to display them. Alternatively, we can implement per-transaction event pagination. This will require some discussion.
=> Temporary limit of 200 stx asset events

src/api/routes/faucets.ts, src/helpers.ts, src/tests/faucet-stx-tests.ts
Reference https://github.com/blockstack/stacks-blockchain-api/issues/359
* Performs nonce incrementing without the previously hardcoded limit.
* Broadcast transaction to both miner and follower if both are configured.
=> Send stx faucet requests to both miner and follower

src/datastore/common.ts, src/datastore/postgres-store.ts, src/event-stream/core-node-message.ts, src/event-stream/event-server.ts, src/migrations/1605184662317_miner_rewards.ts, src/tests/datastore-tests.ts
Fixed a bug with API getting stuck around block 101 on current Xenon testnet. A parse error in the miner reward event handler was stalling block processing.
=> fix: miner reward event parse error

client/src/generated/apis/TransactionsApi.ts, docs/openapi.yaml, src/api/controllers/db-controller.ts, src/api/routes/address.ts, src/api/routes/tx.ts, src/datastore/common.ts, src/datastore/memory-store.ts, src/datastore/postgres-store.ts, src/migrations/1588252682585_stx_events.ts, src/migrations/1588256295395_ft_events.ts, src/migrations/1588261750265_nft_events.ts, src/migrations/1588266401242_contract_logs.ts, src/migrations/1605100253938_stx_lock_events.ts, src/tests/api-tests.ts, src/tests/datastore-tests.ts
Closes https://github.com/blockstack/stacks-blockchain-api/issues/365
Implement pagination for transaction events. 
The endpoint `/extended/v1/tx/<txid>` can now be passed query parameters `event_offset` and `event_limit`. If unspecified, the default is `96`.
=> Add pagination for tx events #365

src/datastore/postgres-store.ts, tsconfig.json
Closes (hopefully) https://github.com/blockstack/stacks-blockchain-api/issues/384
Followed the guide from https://node-postgres.com/guides/project-structure to augment the postgres lib with query leak detection and logging. This appears to be one of the least invasive methods, but this PR will still cause merge conflicts with other PRs modifying the postgres layer.
Changes:
* All db queries are performed with a new helper function that logs an error if a query/pg-client isn't released after 5 seconds. This should help identify any queries that could be causing the "idle in transaction" status reported by postgres.
* All sql transactions are performed in a similar helper function that enforces the `try { BEGIN; <query>; COMMIT; } catch { ROLLBACK; }` statements.
=> Implement sql query leak detection and logging

src/api/init.ts, src/api/routes/bns/pricing.ts, src/bns-helpers.ts, src/tests-bns/api.ts
Following endpoints are implemented: 
1. /v2/prices/namespaces/{tld}
2. /v2/prices/names/{name}
For details please refer to this [issue](https://github.com/blockstack/stacks-blockchain-api/issues/317)
No
No
Test cases are added for the endpoints implemented.
To run the test cases `npm run test:bns`
=> feat: add pricing names and namespaces

package-lock.json, src/api/init.ts, src/api/routes/bns/addresses.ts, src/api/routes/bns/names.ts, src/datastore/common.ts, src/datastore/memory-store.ts, src/datastore/postgres-store.ts, src/tests-bns/api.ts
Following endpoints are implemented:
1. /:name/zonefile/:zoneFileHash
2. /:name/zonefile
3. /:blockchain/:address
For details refer to [issue](https://github.com/blockstack/stacks-blockchain-api/issues/317)
Test cases are added for the endpoints implemented.
To run the test cases `npm run test:bns`
=> feat: get names by address and historical zonefile

src/event-stream/reader.ts, src/p2p/tx.ts
Just the first commit from #398, which is the only one tested
Fixes #396 , which was halting progress on the api at block 119
=> fix: create mock tx from event for BTC tx's

src/event-stream/event-server.ts
Closes https://github.com/blockstack/stacks-blockchain-api/issues/402
Transaction event indexes are received scoped to block level rather than a transaction. E.g. if a block has 100 transactions, with one or more events per transaction, then transactions N+1 will have event indexes started _after_ 0. 
This resulted in some STX transfer transactions, which should only have 1 event, not showing the event because it was pushed 1 or more pages down when queried. 
This PR modifies the event server to re-calculate event indexes on a per-transaction level.
=> fix: #402 tx events not showing due to pagination issue

client/src/generated/apis/TransactionsApi.ts, docs/openapi.yaml, src/api/routes/tx.ts, src/datastore/common.ts, src/datastore/postgres-store.ts, src/tests/api-tests.ts
Closes https://github.com/blockstack/stacks-blockchain-api/issues/380
```yaml
/extended/v1/tx/mempool:
get:
summary: Get mempool transactions
tags:
- Transactions
operationId: get_mempool_transaction_list
description: Get all recently-broadcast mempool transactions
parameters:
- name: sender_address
in: query
description: Filter to only STX transfer transactions with this sender address.
required: false
schema:
type: string
- name: recipient_address
in: query
description: Filter to only STX transfer transactions with this recipient address.
required: false
schema:
type: string
- name: address
in: query
description: Filter to only show STX transfer transactions with this address as the recipient or sender.
required: false
schema:
type: string
- name: limit
in: query
description: max number …
```
=> Tx mempool address filters

package-lock.json, package.json, src/api/init.ts, src/index.ts
Fixes https://github.com/blockstack/stacks-blockchain-api/issues/403
This converts the raw paths received by the `@promster/express` middleware into Express path template strings.
1. First, [`express-list-endpoints`](https://www.npmjs.com/package/express-list-endpoints) is used to enumerate all the application defined API route templates.
2. Then [`path-to-regexp`](https://www.npmjs.com/package/path-to-regexp) is used to map the Express route strings into a set of regexps.
3. The promster middleware runs the raw request URL paths through this set of regexes to determine the route template.
The resulting raw paths, e.g.
`/extended/v1/address/ST26DR4VGV507V1RZ1JNM7NN4K3DTGX810S62SBBR/stx?asdf=1234`
are now reported by their path template, .e.g.
`/extended/v1/address/:stx_address/stx `
=> feat: normalize express prometheus metrics with route parsing

src/event-stream/event-server.ts, src/event-stream/reader.ts, src/index.ts, src/tests-rosetta-cli/validate-rosetta-construction.ts, src/tests-rosetta-cli/validate-rosetta.ts, src/tests-rosetta/api.ts, src/tests/setup.ts
Closes https://github.com/blockstack/stacks-blockchain-api/issues/411
PR adds support for the on-btc-chain `stx-stacks` operation. A synthetic pox contract call tx is generated for the operation event, similar to the previous on-btc-chain stx-transfer operation.
This was tested by grabbing event data generated by this stacks-node integration test: https://github.com/blockstack/stacks-blockchain/commit/d163d5cf2c817d83d7d120f8f988d9abf0a684be and injecting it into the API while running in mocknet mode.
=> feat: handling for on-btc-chain stx-stacks operations

client/src/generated/apis/AccountsApi.ts, client/src/generated/apis/SmartContractsApi.ts, docs/openapi.yaml
A few of the RPC methods accept a `tip` query parameter. This can be used to query at a chain tip. Importantly, this lets you query data at an `unanchored_chain_tip`, AKA microblock.
=> fix: add `?tip` query param to RPC methods

src/api/routes/rosetta/construction.ts
Fix added for rosetta endpoint `/combine`.
For details refer to this [issue](https://github.com/blockstack/stacks-blockchain-api/issues/435)
No
No
For review @zone117x
=> fix: removed 0x from public key in rosetta combine api

docs/api/rosetta/rosetta-construction-payloads-request.schema.json, docs/index.d.ts, src/api/routes/rosetta/account.ts, src/api/routes/rosetta/construction.ts, src/tests-rosetta/api.ts
Custom nonce added in rosetta endpoints `/construction/payloads` and `/account/balance`
For details refer to this [issue # 433](https://github.com/blockstack/stacks-blockchain-api/issues/433)
No
No
For review @zone117x
=> fix: custom nonce added in /payloads and /balance

follower.Dockerfile, src/datastore/common.ts, src/datastore/postgres-store.ts, src/event-stream/core-node-message.ts, src/event-stream/event-server.ts, src/migrations/1605184662317_miner_rewards.ts, src/tests/datastore-tests.ts, stx-rosetta.Dockerfile
Closes https://github.com/blockstack/stacks-blockchain-api/issues/376
This fixes miner rewards being higher than what the stacks-node reports for account balance.
There were a few issues:
1. Re-orgs for miner rewards were using the block index hash for the reward origin block, rather than the reward maturation block.
2. Miner rewards received by immediately non-canonical blocks were not being immediately set as non-canonical.
3. `tx_fees_streamed_produced`, one of the three values that make up the tx fee reward amount, was missing entirely from the event stream. This required a fix in the core node.
This PR is blocked on https://github.com/blockstack/stacks-blockchain/pull/2418
=> Correct re-org handling for miner rewards

docs/openapi.yaml, src/datastore/postgres-store.ts
Closes https://github.com/blockstack/stacks-blockchain-api/issues/438
Previously, when using an address filter for the `/extended/v1/tx/mempool` endpoint, only `stx-transfer` tx types would be returned. This decision was initially made because only `stx-transfer` types have anything like a known `recipient` before the tx is mined. This is in contrast to a `contract-call` tx type, where there _can_ be recipients in the events generated, but events are not available until the tx is actually mined (and the contract code is ran).
This change allows any tx type to be returned, but keep in mind that only the tx `sender` will be checked for all tx types that are not a `stx-transfer`.
=> Include any tx type in the address filtered mempool result

docs/openapi.yaml, src/api/routes/address.ts, src/datastore/common.ts, src/datastore/postgres-store.ts
Closes https://github.com/blockstack/stacks-blockchain-api/issues/457
Adds a block `height` filter to the `/stx_inbound` endpoint, e.g.
`/extended/v1/address/ST11NJTTKGVT6D1HY4NJRVQWMQM7TVAR091EJ8P2Y/stx_inbound?height=127`
Also increases pagination limit to 500, and fixes the error response message.
=> Add `height` filter to `/stx_inbound`

docs/openapi.yaml, src/api/controllers/db-controller.ts, src/api/routes/block.ts, src/tests/api-tests.ts
Implement a new endpoint `get block by height`, similar to the `get block by hash` endpoint. 
`GET /extended/v1/block/by_height/<number>`
=> Add get block by height endpoint

src/api/routes/rosetta/construction.ts, src/tests-rosetta/api.ts
Fix added for ecdsa signature in endpoint `/combine`
For details refer to this [issue](https://github.com/blockstack/stacks-blockchain-api/issues/434)
No
=> Fix: Rosetta/ECDSA signature

docs/api/info/get-total-stx-supply-legacy-format.example.json, docs/api/info/get-total-stx-supply-legacy-format.schema.json, docs/api/info/get-total-stx-supply.example.json, docs/api/info/get-total-stx-supply.schema.json, docs/index.d.ts, docs/openapi.yaml, src/api/init.ts, src/api/routes/total-supply.ts, src/datastore/common.ts, src/datastore/memory-store.ts, src/datastore/postgres-store.ts, src/helpers.ts
Closes https://github.com/blockstack/stacks-blockchain-api/issues/455
Implements a total STX supply endpoint, and another that is formatted the same as the legacy 1.0 API -- so integrators would only need to change the URL.
Examples:
`GET /extended/v1/total_supply`:
```json
{
"unlocked_percent": "77.48",
"total_stx": "1352464600.000000",
"unlocked_stx": "1047848171.287772",
"block_height": 5086
}
```
`GET /extended/v1/total_supply/legacy_format`:
```json
{
"unlockedPercent": "77.48",
"totalStacks": "1352464600.000000",
"totalStacksFormatted": "1,352,464,600.000000",
"unlockedSupply": "1047848171.287772",
"unlockedSupplyFormatted": "1,047,848,171.287772",
"blockHeight": "5086
}
```
=> Total STX supply endpoint

.github/workflows/gh-pages.yml
Adds a Github workflow to generate and publish gh-pages docs on each commit + merge into the `master` branch.
I haven't used this gulp library before, so I'm not sure if anything special is needed for it to work in a GH workflow, but it's placed in a separate workflow file to ensure it doesn't interfere with the standard release workflow.
Closes https://github.com/blockstack/stacks-blockchain-api/issues/297
No
=> chore: add gh workflow to publish gh-pages

.github/workflows/gh-pages.yml
Sets github user and email info when generating and committing gh-pages docs.
Addresses comment https://github.com/blockstack/stacks-blockchain-api/pull/476#issuecomment-792657387
No
No
=> chore: set gh-pages commit info

.github/workflows/gh-pages.yml
Fixes github auth issue from [here](https://github.com/blockstack/stacks-blockchain-api/runs/2057412650?check_suite_focus=true#step:7:36) when pushing up gh-pages docs. I had to abandon using Gulp to deploy the docs because it's doing something weird and causing authentication problems where there shouldn't be any.
This solution generates the types and docs the same way it was being created previously, but uses a different method of publishing to the `gh-pages` branch.
Tested and working: https://github.com/blockstack/stacks-blockchain-api/tree/gh-pages
No
No
=> chore: fix gh pages workflow

src/api/serializers/post-conditions.ts, src/tests/api-tests.ts
Fixes https://github.com/blockstack/stacks-blockchain-api/issues/486
Fixes the bug seen here:
Ge => greater than or equal
Le => less than or equal
/ht @kantai, @aulneau, @jasperjansz
=> fix: correct post-condition code string

src/event-stream/core-node-message.ts, src/event-stream/event-server.ts
Fixes https://github.com/blockstack/stacks-blockchain-api/issues/390
Events marked non-committed (i.e. their transaction was aborted) are no longer stored in the tables used to lookup balances. 
~~Also maybe https://github.com/blockstack/stacks-blockchain-api/issues/468 -- need to still test on mainnet.~~ EDIT: not a fix for this one
=> fix: do not store aborted events

src/datastore/postgres-store.ts
Closes https://github.com/blockstack/stacks-blockchain-api/issues/497
Transient pg connection errors are not handled by the postgres lib's connection pool. This is somewhat unexpected, see https://github.com/brianc/node-postgres/issues/1789.
This PR adds connection try/catch retry logic for the errors that occur when the postgres service is restarting.
=> fix: handle transient postgres connection errors #497

src/api/init.ts
Closes https://github.com/blockstack/stacks-blockchain-api/issues/403
Make all `v2/*` routes report as a single metric.
=> Condense all v2 routes into a single prom metric bucket

docs/api/address/get-address-nft-events.example.json, docs/entities/nft-events/nft-event.schema.json, docs/index.d.ts, src/api/routes/address.ts, src/tests/api-tests.ts
This PR 
* replaces the `value` and `value_repr` properties of `NFTEvent` by the common clarity value type `{hex:string, repr: string}`
* towards #506 
Another update for `value` and `asset_identifier` should follow (#432).
As this feature was only introduce a day ago, it is still new enough.
Self-documenting
=> fix: use common clarity value type in NFTEvent

src/datastore/postgres-store.ts, src/event-stream/event-server.ts, src/tests-bns/bns-integration-tests.ts
The PR fixes two issues in Bns.
1) the name details api works for this:  https://stacks-node-api-bns.testnet.stacks.co/v1/names/test-registrar. instead of 
https://stacks-node-api-bns.testnet.stacks.co/v1/names/test-registrar.id 
2) zone file is not being updated for `name-update
see details here: #511
=> Fixed name not being updated issue. 

src/api/routes/search.ts, src/tests/api-tests.ts
This PR provides transaction information for pending contract transactions. For consistency, I have added `tx_id` in the search result endpoint for contract_address for both pending and confirmed transactions. 
For details see:  #378
=> Provide ability to fetch information for a pending contract

src/bns-helpers.ts, src/event-stream/event-server.ts
This PR fixes the improper zone file issue for subdomains.
The subdomain https://stacks-node-api.testnet.stacks.co/v1/names/second_test.test-registrar.id returns zone file for the name instead of subdomain. This PR extracts subdomain zonefile from parent `zonefile` and save only that in subdomains table. 
For details refer to issue #520
=> Fix: subdomain zone file

docs/entities/rosetta/rosetta-construction-options.schema.json, docs/index.d.ts, src/api/rosetta-constants.ts, src/api/routes/debug.ts, src/api/routes/faucets.ts, src/api/routes/rosetta/construction.ts, src/core-rpc/client.ts, src/rosetta-helpers.ts, src/tests-rosetta-cli/validate-rosetta-construction.ts, src/tests-rosetta-cli/validate-rosetta.ts, src/tests-rosetta/api.ts, src/tests/core-rpc-tests.ts
We now use `suggested_fee` to calculate the fee required for the transaction. We don't need the `fee` operation neither in order to create a transaction.
See https://github.com/blockstack/stacks-blockchain-api/issues/505
Yes. The api will return an error if `fee` operation is added when creating an transaction.
=> fix: use `suggested_fee` info in rosetta

.env, src/datastore/common.ts, src/datastore/memory-store.ts, src/datastore/postgres-store.ts, src/import-v1/index.ts, src/index.ts, src/migrations/1616752858364_config_state.ts
Fixes https://github.com/blockstack/stacks-blockchain-api/issues/504
Related to https://github.com/blockstack/stacks-blockchain-api/issues/500
Once this is merged, the BNS PR https://github.com/blockstack/stacks-blockchain-api/pull/483 can be merged without breaking API restart capabilities.
=> fix: do not re-import Stacks 1.0 BNS data

src/api/routes/bns/names.ts, src/datastore/common.ts, src/datastore/memory-store.ts, src/datastore/postgres-store.ts, src/migrations/1610030345948_bns-subdomain.ts, src/tests-bns/api.ts
This PR replicates behavior in stacks 1.0 for subdomains. It redirects the request to the subdomain registrar for missing subdomains the following way,  If a subdomain isn't found in the `stacks-blockchain-api` database, extract resolver(which should be the URL for subdomain registrar) from the latest subdomain for this Bns name and redirect the request to that.  This would allow users to resolve subdomains that aren't fully registered yet. 
For details refer to issue #517 
@markmhx @jcnelson
=> Redirect subdomains endpoint to resolve for missing subdomains

docs/openapi.yaml, src/api/routes/address.ts, src/api/routes/tx.ts, src/datastore/common.ts, src/datastore/memory-store.ts, src/datastore/postgres-store.ts, src/tests/api-tests.ts, src/tests/datastore-tests.ts
A couple of endpoints are added
1. `/tx/block/[block_hash]`
Returns the transactions in a block
2. `/address/[address]/mempool`
Returns the mempool transactions for the address
For details refer to issue #307 
No
Tests added for new endpoints
=> Fix/ include tx data for block and address

src/import-v1/index.ts, src/tests-bns/bns-integration-tests.ts
This PR converts BTC address to STX address before saving it in db for stacks 1.0 subdomains. 
For details refer to issue #541
=> Convert Btc address to Stx address for subdomain

src/import-v1/index.ts
On the latest API instance, we noticed an issue where existing BNS names were not imported. Digging in, it looks like the issue was caused by an invalid BTC address (`1AafnuydZLQJ1phQZd7MeYLbcWA6Ewwqp5`). We run `b58toC32` which will throw if the address is invalid. I believe this was causing the whole import to fail. Invalid subdomain addresses are "normal", because they're off-chain.
This adds a catch block for invalid conversions, and instead the original value (the BTC address) is used as the `owner`. I've tested this with the full import, and it seems to be working.
=> fix: handle invalid BTC addresses in import

src/import-v1/index.ts, src/tests-bns/bns-integration-tests.ts
This PR addresses the small fix in the v1-import script, It assigns the name part to the `name` field of `subdomains` instead of `fqn`
fixes #554
=> Fix subdomain name part

docs/api/address/get-address-transactions-with-transfers.example.json, docs/api/address/get-address-transactions-with-transfers.schema.json, docs/entities/address/transaction-with-transfers.schema.json, docs/index.d.ts, docs/openapi.yaml, src/api/routes/address.ts, src/datastore/common.ts, src/datastore/memory-store.ts, src/datastore/postgres-store.ts, src/tests/api-tests.ts
Closes #369
Implements a new endpoint `/extended/v1/address/{principal}/transactions_with_transfers`. This is similar to the `/extended/v1/address/{principal}/transactions` endpoint, but adds STX transfer data to each transaction entry.
This allows the explorer and wallets to easily show STX transfer amounts for tx types other than simple stx-transfer txs. For example:
* The genesis block transaction for addresses in the Stacks 1.0 import.
* Coinbase transactions where STX are minted for addresses with an unlocking schedule.
* Contract-call transactions, for example the `send-many` contract used by exchanges.
Here's the interface for the items returned in the response:
https://github.com/blockstack/stacks-blockchain-api/blob/e8becd488bddc99da32c6306a5320c4772d16645/docs/index.d.ts#L1085-L1 …
=> feat: address transactions with stx transfers endpoint

src/api/routes/bns/names.ts, src/tests-bns/api.ts
BNS's `v1/names/:fqn` API redirects to incorrect URL. This PR fixes that.
=> Fix redirect url issue

docs/api/rosetta/rosetta-construction-metadata-response.schema.json, docs/entities/rosetta/rosetta-operation.schema.json, docs/index.d.ts, src/api/controllers/db-controller.ts, src/api/routes/rosetta/account.ts, src/api/routes/rosetta/block.ts, src/api/routes/rosetta/construction.ts, src/api/routes/rosetta/mempool.ts, src/api/routes/rosetta/network.ts, src/datastore/memory-store.ts, src/rosetta-helpers.ts, src/tests-rosetta/api.ts, src/tests-rosetta/offline-api-tests.ts
Modifications regarding the rosetta api. It contains the following changes : 
* Return 50 error everywhere
* Re-introduce back the fee operation and suggest fee if there is none
* Remove `status` in construction API to fit the spec
No. But error status code are not 400 anymore. This can have an impact on how error is being handle.
=> [Rosetta] Error 500 & fee operation

follower.Dockerfile, package.json, src/bns-helpers.ts, src/datastore/common.ts, src/datastore/memory-store.ts, src/datastore/postgres-store.ts, src/event-stream/core-node-message.ts, src/event-stream/event-server.ts, src/tests-bns/bns-integration-tests.ts, src/tests-rosetta/api.ts, src/tests/core-rpc-tests.ts, src/tests/setup.ts, stacks-blockchain/docker/Dockerfile
Fix bug with the `/attachment/new` event handler returning 404 when a subdomain's tx is forked.
=> fix: use index_block_hash for unresolved subdomain attachment handling

src/datastore/common.ts, src/datastore/memory-store.ts, src/datastore/postgres-store.ts, src/event-stream/event-server.ts
There were empty subdomains being stored in the subdomains table.  This PR fixes that. 
Closes #564.
=> Fix empty subdomains

src/api/rosetta-constants.ts, src/api/routes/rosetta/account.ts, src/api/routes/rosetta/construction.ts, src/rosetta-helpers.ts, src/tests-rosetta/api.ts
This PR add `vesting` info in the Rosetta api. Locked balance now consider stacking and vesting. In Construction API, we removed the requierement for the `public_keys` when calling `/metadata` and instead use the data given in options.
No.
=> [Rosetta-api] - Adding vesting info & remove public keys requierement in /metadata

src/api/routes/rosetta/construction.ts, src/tests-rosetta/api.ts
Rosetta spec don't recognize `VRS` signature format and only give a signature under the format `RSV` when sending a request to `/submit`. This PR modify the signature format back to `VRS` before submitting it to the node.
No.
=> fix: Rosetta Construction api `/submit` signature format

src/api/rosetta-constants.ts, src/api/routes/rosetta/construction.ts, src/tests-rosetta/api.ts, src/tests-rosetta/offline-api-tests.ts
Remove rpc calls for nonce and add a proper error if nonce is missing instead of fallback on getting nonce from node.
=> fix: remove stack call on /payload

stx-rosetta.Dockerfile
- Refactoring to use runit vs custom script
- clone the latest releases vs static versions
This change refactors the rosetta Dockerfile to use [runit](http://smarden.org/runit/) as a scheduler vs a customized shell script. This change was motivated by discussions with another team trying to use this Dockerfile, and realizing the static version was very out of date. Further work was added to standardize the Dockerfile, so there weren't things like custom users/scripts (particularly in the case of postgresql). 
The *builder* images are also refactored to more closely resemble the default Dockerfiles, as well as cloning the latest release for each of `stacks-blockchain-api` and `stacks-blockchain` repos. 
Other changes are more use of ARG and ENV variables to create the scripts, i.e.
``` …
```
=> Updating rosetta dockerfile

docs/api/rosetta/rosetta-network-options-response.schema.json, docs/entities/rosetta/rosetta-error-no-details.schema.json, docs/entities/rosetta/rosetta-error.schema.json, docs/generated.d.ts, src/api/rosetta-constants.ts, src/api/rosetta-validate.ts, src/api/routes/rosetta/construction.ts, src/tests-rosetta/api.ts
Fixes https://github.com/blockstack/stacks-blockchain-api/issues/591
Global Rosetta error constants were being mutated in various API response handlers, for example:
```ts
const err = RosettaErrors[RosettaErrorsTypes.invalidTransactionString];
err.details = { message: e.message }; // <-- BAD
res.status(500).json(err);
```
This caused the list of errors returned by `/rosetta/v1/network/options` to seemingly randomly include extra error details, and break clients like the Rosetta Go SDK.
This was fixed with applying Typescript's `Readonly<T>` to the error consts, then fixing the various mutation violations provided by the Typescript compiler. 
```ts
// Previous, unsafe const definition:
const RosettaErrors: Record<RosettaErrorsTypes, RosettaError>;
// New, safe readonly const definition: …
```
=> fix: [Rosetta] fix unintentional global error object mutations

src/api/routes/rosetta/construction.ts, src/tests-rosetta/api.ts
Reverse Rosetta Construction api signature modification. 
See old PR https://github.com/blockstack/stacks-blockchain-api/pull/572
No
=> fix: rosetta no signature format modification

src/event-stream/event-server.ts
Needed to support running the API with stacks-node 2.0.12.0.0
=> fix: add a no-op handler for `/new_microblocks` events

running_an_api.md, running_api_from_source.md
This PR updates some of the spacing, layout, and content per the [markdownlint extension](https://marketplace.visualstudio.com/items?itemName=DavidAnson.vscode-markdownlint) specifications.
This PR intentionally avoids removing the `$` from commands, although this is recommended if an input is not shown below. For now, it seemed better to leave everything consistent to what was there before.
This PR also adds a TOC to each file, generated by the VSCode extension. If using the same extension, the TOC is updated on save.
1. Motivation for change: after following the instructions saw a typo, and thought I'd give it a full once over
2. What was changed: mostly spacing, some headers, detailed notes in commits
3. How does this impact application developers: makes the document more accessible
No …
=> Clean up and lint markdown for api node instructions

src/api/controllers/db-controller.ts, src/rosetta-helpers.ts
This PR fixes two things:
1. prioritize using the `blockhash` over `index` when both are provided for `rosetta/v1/block` endpoint
2. fix `-0` value in amount for rosetta operations that caused rosetta-sdk-go to error when parsing
=> [rosetta] prioritize blockhash over index for /block and fix -0 amount values

client/package.json, client/tsconfig.json
Fixes issue with the gh-pages action failing while building client package docs, like here: https://github.com/blockstack/stacks-blockchain-api/runs/2621973076
=> fix: issue with client doc generation in gh actions

docs/index.js, docs/package.json
This is a bit of an odd fix, but we need to either:
- Export the types as a regular typescript file, not a declaration
- Trick module bundlers into thinking it's a legit module
One of the later TS versions introduces the inability to import `.d.ts` files. Declaration files are generated to describe the contents of compiled output, and thus shouldn't be imported.
The contents of this package may only be typings, but it describes our API, not the contents of a compiled script. 
See https://github.com/octokit/types.ts for another example of a type-only package.
=> fix: bundling issues

src/api/rosetta-constants.ts, src/api/routes/rosetta/network.ts
This removes the hardcoded `stacks.co` URLs  in `rosetta` `network/status` api and uses `STACKS_CORE_RPC_HOST`  and `STACKS_CORE_RPC_PORT` environment variables instead.
closes #656 
No
No
=> Fix rosetta network/status api issue

docs/openapi.yaml, src/api/controllers/db-controller.ts, src/api/routes/block.ts, src/datastore/common.ts, src/datastore/memory-store.ts, src/datastore/postgres-store.ts, src/tests/api-tests.ts
Stacks blockchain has a view into the burnchain. This information should be made available through the api also via burnchain information
This PR 
* adds to RPC methods that allow users to query a block by the corresponding burn block identified either by its hash or height.
* fixes #675 
No
Documentation was added in openapi.yaml
Tests were added in api-tests
On a running server 
1. get /v2/info and remember burn block height and burn block hash and block height
2. get /extended/v1/block/by_height/1234 (use block height) and remember block
2. get /extended/v1/block/by_burn_block_height/5678 (use burn block height) and compare with the previously retrieved block
3. get /extended/v1/block/by_burn_block_height/0x1234 (use burn block hash) and compare with the previously retrieved block
4. …
=> Add get block by burn block height and by burn block hash (#675)

src/api/routes/rosetta/construction.ts
This PR removes the `token_transfer_recipient_address` from stacking transactions and only us it in `token_transfer` transaction. 
closes #673
=> [Rosetta][Construction-API] Remove token_transfer_recipient_address from stacking transactions

package-lock.json, package.json, src/api/routes/rosetta/construction.ts, src/tests-rosetta/offline-api-tests.ts
This PR fixes the bug for rosetta `construction/preprocess`. The PR was making an api request to the node where it was supposed to work offline. 
fixes #674 
_NO_
_NO_
=> [Rosetta][Construction-API] fix constructing stacking tx using /preprocess

docs/entities/rosetta/rosetta-construction-options.schema.json, docs/generated.d.ts, src/api/routes/rosetta/construction.ts, src/rosetta-helpers.ts, src/tests-rosetta/api.ts, src/tests-rosetta/offline-api-tests.ts
Support BTC reward(`pox_addr`) address  for `preprocess` and `payload`
closes #672
=> Support reward address for stacking transactions

src/api/routes/rosetta/account.ts, src/api/routes/rosetta/construction.ts, src/rosetta-helpers.ts
Fetch nonce, using both `postgres` and `stacks-node` and selecting the maximum nonce to avoid conflict. 
Closes https://github.com/blockstack/stacks-blockchain-api/issues/685
=> [Rosetta] Avoid conflicting nonce issue in rosetta

docs/api/rosetta/rosetta-block-transaction-request.schema.json, src/api/controllers/db-controller.ts, src/tests-rosetta/api.ts
Closes https://github.com/blockstack/stacks-blockchain-api/issues/704
Stacking transaction operations included in the rosetta `/block` endpoint where missing from the rosetta `/block/transaction` endpoint.
=> fix(rosetta): `/block/transaction` endpoint missing ops #704

src/api/init.ts, src/helpers.ts, src/index.ts, src/shutdown-handler.ts
Internal connections may take a long time to shut down, causing the API to hang and not report any errors until the process is complete. To avoid that, this PR sets a time limit for connection close handlers so we can run some logic when one of them gets stuck. Solves issue #681 
No
No
Testing is done by sending a SIGINT to the nodejs process so shutdown sequences are triggered.
=> graceful shutdown of stuck connections

docs/api/address/get-address-assets.example.json, docs/entities/transaction-events/transaction-event-fungible-asset.schema.json, docs/entities/transaction-events/transaction-event-non-fungible-asset.schema.json, docs/entities/transaction-events/transaction-event-smart-contract-log.schema.json, docs/entities/transaction-events/transaction-event-stx-asset.schema.json, docs/entities/transaction-events/transaction-event-stx-lock.schema.json, src/api/controllers/db-controller.ts, src/tests/api-tests.ts, src/tests/datastore-tests.ts
Returns the transaction ID along with every asset queried on a particular address under the  `/extended/v1/address/[:addr]/assets` endpoint. This will be useful for wallets and the explorer so they can display additional information about the purchase or transfer of said assets.
Closes #678 
No
Yes, the documentation for this particular endpoint should be updated.
Covered by current API and Datastore unit tests (ammended in this PR).
=> return tx_id on every asset in /extended/v1/address/[:addr]/assets

src/api/routes/tx.ts, src/datastore/postgres-store.ts, src/tests/api-tests.ts
This change allows API users to query the mempool by a smart contract id or a contract call id using the existing `address` parameter so they can monitor transactions that are relevant to the execution of any smart contract.
No
Yes. The new parameter behavior should be updated in the API endpoint docs.
Covered by existing unit tests.
Closes #605
=> add smart contract id or contract call id queries to /extended/v1/tx/mempool

client/tsconfig.json
The `openapi-generator-cli` utility started generating typescript that is incompatible with `strictNullChecks: true`. Temporarily disable this in the client lib until fixed.
=> fix: client lib and docs build fix

src/api/routes/rosetta/account.ts, src/api/routes/rosetta/construction.ts, src/rosetta-helpers.ts
Should revert the change that introduced https://github.com/blockstack/stacks-blockchain-api/issues/718
However, this re-introduces possible conflicting nonce errors if more than one tx per account is submitted in a block https://github.com/blockstack/stacks-blockchain-api/issues/685
=> Revert "fix(rosetta): conflicting nonce issue in rosetta tx construction #685"

docs/api/address/get-address-transactions-with-transfers.example.json, docs/entities/address/transaction-with-transfers.schema.json, docs/generated.d.ts, src/api/routes/address.ts, src/datastore/common.ts, src/datastore/memory-store.ts, src/datastore/postgres-store.ts, src/tests/api-tests.ts
Add FT and NFT transfers to the list of transactions listed in `/extended/v1/address/[:principal]/transactions_with_transfers` so wallets can display this information to users.
Closes #615 
No.
Yes. Endpoint descriptions should be updated.
Covered in existing unit tests.
=> expose FT and NFT transfers in /extended/v1/address/[:principal]/transactions_with_transfers

src/rosetta-helpers.ts
This PR changes the type of `sender` and `receiver` operations to  `token_transfer`, even if the STX transfer happens through `contract_call` the last two operations(`sender` & `receiver`) will be `token_transfer`.
closes #683 
All the clients expecting `contract_call` of the last two operations of transfer through contract call should change the logic and expect `token_transfer` now. 
see details here #683.
=> Change sender and receiver operations to token_transfer

docs/api/search/search-address.schema.json, docs/api/search/search-block.schema.json, docs/api/search/search-contract.schema.json, docs/api/search/search-error.schema.json, docs/api/search/search-mempool.schema.json, docs/api/search/search-success.schema.json, docs/api/search/search-tx-id.example.json, docs/api/search/search-tx-id.schema.json, docs/api/search/search.schema.json, docs/generated.d.ts, docs/openapi.yaml, src/api/routes/search.ts
The types for Search were made locally and not documented properly. This PR adds types in the docs and uses them in search.ts.
Types for search can be imported as 
```
import {SearchResult} from '@stacks/stacks-blockchain-api-types';
```
For details refer to issue #645
=> Types for search

src/api/routes/socket-io.ts
This code adds metrics for socket.io activity in the API. It tracks connections, disconnections, topic subscriptions, and sent events.
Example metrics output:
```
socket_io_subscriptions 1
socket_io_subscriptions{topic="mempool"} 1
socket_io_connect_total 1
socket_io_disconnect_total 1
socket_io_events_sent{event="mempool"} 3
```
Closes #589 
No
No
Testing was done locally via a Prometheus instance.
=> emit prometheus metrics for socket.io

.env, src/api/controllers/db-controller.ts, src/api/routes/address.ts, src/api/routes/tx.ts, src/datastore/postgres-store.ts, src/migrations/1584619633448_txs.ts
* Add sql index to speed up tx list queries.
* Remove redundant sql queries for already found tx db data.
* Make the max pg connection pool limit configurable via env var.
=> fix: sql optimizations to speed up various tx queries

src/api/routes/status.ts
Support POST in status endpoint since the Desktop Wallet uses that verb to check API status.
No
No
No
=> support post verb in /extended/v1/status

docs/entities/rosetta/rosetta-construction-options.schema.json, docs/entities/rosetta/rosetta-transaction.schema.json, docs/generated.d.ts, src/api/controllers/db-controller.ts, src/api/routes/rosetta/construction.ts, src/api/routes/rosetta/mempool.ts, src/rosetta-helpers.ts, src/tests-rosetta/api.ts
Closes https://github.com/blockstack/stacks-blockchain-api/issues/752
Implement memo support for rosetta STX token transfers. 
Uses the proposed schema from https://github.com/blockstack/stacks-blockchain-api/issues/752
=> feat(rosetta): support memos in stx token transfer operations

src/api/init.ts
Related to https://github.com/hirosystems/devops/issues/795
Add buckets larger than 10 seconds to the prometheus http duration histogram configuration as defined here: https://github.com/tdeekens/promster/#-documentation
thx @wileyj for identifying this default config
=> fix: increase the 10 second cap on prometheus http metric reporting

src/api/routes/core-node-rpc-proxy.ts
(Hopefully) closes https://github.com/blockstack/stacks-blockchain-api/issues/756
Disables the http keep-alive header in the /v2 proxy to the Stacks core node. This should prevent individual API instances from sticking to specific stacks-node instances.
=> fix: disable http keep-alive for stacks-node /v2 proxied endpoints

src/api/controllers/db-controller.ts, src/datastore/postgres-store.ts, src/rosetta-helpers.ts, src/tests-rosetta/api.ts
This pr fixes the conflicting hash problem. The `stx_lock` transaction hash was conflicting with `stx_unlock` transactions. Now,  `stx_unlock` uses `coinbase` transaction hash.  
closes #760 
Updated integration test to check this scenerio
=> Fix conflicting transaction hash for rosetta issue

src/api/routes/bns/addresses.ts, src/datastore/postgres-store.ts, src/tests-bns/api.ts
This PR fixes the bug described in #714. The names transferred to the new address should only be returned under the new address. 
closes #714
=> Return only latest name by address

.env, config/extra-tx-post-endpoints.txt, src/api/routes/core-node-rpc-proxy.ts, src/tests/test-helpers.ts, src/tests/v2-proxy-tests.ts
Closes https://github.com/blockstack/stacks-blockchain-api/issues/765
Implements tx "multicast" ability where tx broadcasts to `POST /v2/transactions` can be forwarded to multiple configured stacks-nodes at once. 
A new environment variable `STACKS_API_EXTRA_TX_ENDPOINTS_FILE` is implemented which can be pointed at a file containing newline-delimitated URLs. When an http POST request is made to `/v2/transactions` it will be concurrently broadcasted to both the original proxied endpoint (e.g. `STACKS_CORE_PROXY_HOST`) and to each of the URLs defined in the file. The response from the original endpoint will proxied back to the client, and any response errors from the others will be logged. 
Env var:
```
STACKS_API_EXTRA_TX_ENDPOINTS_FILE=/config/extra-tx-post-endpoints.txt
```
Contents of …
=> feat: ability to configure multiple tx broadcast endpoints

docs/entities/blocks/block.schema.json, docs/generated.d.ts, src/api/controllers/db-controller.ts, src/datastore/common.ts, src/datastore/postgres-store.ts, src/event-stream/event-server.ts, src/migrations/1584604583726_blocks.ts, src/tests-bns/api.ts, src/tests/api-tests.ts, src/tests/datastore-tests.ts, src/tests/microblocks-tests.ts, src/tests/websocket-tests.ts
Added the execution cost(sum of the execution costs for each tx included in the block) in `blocks` and block response. 
closes #735 
NO
Schema changes should be enough
Unit tests coverage updated
=> Execution cost for in block response

src/bns-helpers.ts, src/event-stream/event-server.ts, src/tests-bns/bns-integration-tests.ts
This PR fixes the issue with `name-transfer` owner.  BNS names were being shown by the old owner after transfer to the new owner. 
closes #779 
NO
NO
The integration test is updated to cover this scenario.
=> Fix name transfer owner

docs/openapi.yaml
This PR removes references for regtest from openapi.yaml.
For details refer to issue #784
=> Remove regtest reference from openapi.yaml

client/src/socket-io/index.ts, docs/socket-io/index.d.ts, src/api/routes/socket-io.ts, src/datastore/common.ts, src/datastore/postgres-notifier.ts, src/datastore/postgres-store.ts, src/tests/socket-io-tests.ts
This PR adds socket-io microblock update support in the API and `StacksApiSocketClient`.
Closes #661 
No
Probably, to indicate microblock support for our socket-io client.
A new `socket-io-tests.ts` unit tests file was created to cover this new functionality. This file should also be used to expand test coverage for socket-io codepaths.
=> feat: add microblock update support to socket-io

.github/ISSUE_TEMPLATE/testnet-bug.md, .github/PULL_REQUEST_TEMPLATE.md, README-rosetta.md, client/README.md, client/package.json, client/src/generated/apis/TransactionsApi.ts, docs/api/bns/name-querying/bns-get-subdomain-at-tx-response.schema.json, docs/openapi.yaml, docs/package.json, overview.md, package-lock.json, package.json, readme.md, running_an_api.md, running_api_from_source.md, src/api/routes/core-node-rpc-proxy.ts, src/api/routes/info.ts, src/tests/parse-db-tx.ts, stx-rosetta.Dockerfile
This PR renames all references from blockstack to hirosystems. It also removes some other broken URLs and obsolete refs from our code comments.
See https://github.com/hirosystems/devops/issues/830
No
No
N/A
=> chore: rename github org references from blockstack to hirosystems

src/api/routes/core-node-rpc-proxy.ts, src/tests/v2-proxy-tests.ts
This patch fixes the transaction broadcast logs when an API pod is set to multicast.
Closes #838 
No
No
Local tests
=> fix: transaction broadcast log

.eslintignore, .eslintrc.js, src/core-rpc/client.ts, utils/.eslintrc.js, utils/package-lock.json, utils/package.json, utils/src/index.ts, utils/tsconfig.json
This PR adds a new `utils` module to the API that will allow us to write and use utility scripts to help us debug issues much faster.
To start this module, a first script is added that displays the top N addresses that have the most STX transfer events in the `stx_events` table along with their reported balances both by the API database and a Stacks node. This function will help us debug block and microblock re-org bugs that cause balance discrepancies (such as #804).
An example usage for this script is:
```
utils$ npm run build
utils$ node ./lib/utils/src/index.js stx-balances --count=5 --block-height=25000
Calculating balances for top 5 accounts at block height 25000...
╔═════════════╤══════════════════════════════════════════════════════╤════════════════╤════════════════╤═════════╗
║ …
```
=> Add utils module with script to display top address balances

src/datastore/postgres-store.ts, src/index.ts, src/migrations/1636130197558_nft_custody.ts, src/tests/api-tests.ts
This PR adds a Postgres materialized view `nft_custody` that stores the current owner address of an NFT (a combination of `asset_identifier` and `value`) at the **current canonical chain tip**. It also adds indexes so lookups by NFT or owner address is very quick.
After using this view, the current NFT lookup query sees a huge increase in performance. Local tests showed an improvement from ~400ms before to ~35ms after.
Related to #828 
No
No
Local performance tests
=> Add nft_custody pg materialized view to speed up nft event lookup

src/api/routes/core-node-rpc-proxy.ts, src/tests/v2-proxy-tests.ts
Closes https://github.com/hirosystems/stacks-blockchain-api/issues/852
Implemented the fix at a few layers for robustness:
A. Use `<fetch result>.text()` rather than `<fetch resuilt>.json()` to get the unaltered response (similar to the non-tx-multicasting behavior).
B. Use a regex to strip the double quotes, rather than `JSON.parse()`, which allows for them to be optional `"123"` -> `123`, or `123` -> `123` (unaltered, no error).
C. Wrap the logging function in a try/catch/log-error so that any potential future errors in this function (e.g. resolving the current block height) won't result in an error response to the client.
Updated the unit test so that this code path is covered. This logging path is skipped when there are no blocks in the db, which was the case for the tx multicast unit …
=> fix: tx broadcast logging error

client/README.md, docs/entities/blocks/block.example.json, docs/entities/microblocks/microblock.example.json
This patch expands the client JS library README to include sections on how to use Socket.io and examples of every update we send to clients.
No
Not sure
N/A
=> chore: expand client README to include socket.io and message examples

README-rosetta.md, client/README.md, overview.md, running_an_api.md
Fixes #836 by replacing `blockstack.github.io` with `hirosystems.github.io`.
No
No
None
=> Fix: update from blockstack to hirosystems in links

docs/entities/transactions/abstract-transaction.schema.json, docs/entities/transactions/transaction-with-events.schema.json, docs/generated.d.ts, docs/openapi.yaml, src/api/controllers/db-controller.ts, src/tests/api-tests.ts, src/tests/microblocks-tests.ts
The transaction's history endpoint returned transaction with event_count non zero. However, the transaction events contained an empty list. This PR removed the unnecessary events object from the response.
For details refer to issue #668
=> Remove Empty Array From Address Endpoint

src/api/routes/ws/metrics.ts, src/api/routes/ws/socket-io.ts, src/api/routes/ws/ws-rpc.ts
This patch adds Prometheus metrics for WebSocket usage. Example:
```
websocket_subscriptions{topic="block"} 0
websocket_subscription_timers_bucket{le="1",topic="block"} 0
websocket_subscription_timers_bucket{le="5",topic="block"} 0
websocket_subscription_timers_bucket{le="10",topic="block"} 0
websocket_subscription_timers_bucket{le="30",topic="block"} 1
websocket_subscription_timers_bucket{le="60",topic="block"} 1
websocket_subscription_timers_bucket{le="180",topic="block"} 1
websocket_subscription_timers_bucket{le="300",topic="block"} 1
websocket_subscription_timers_bucket{le="600",topic="block"} 1
websocket_subscription_timers_bucket{le="1200",topic="block"} 1
websocket_subscription_timers_bucket{le="1800",topic="block"} 1
websocket_subscription_timers_bucket{le="3600",topic="block"} 1 …
```
=> feat: add prometheus metrics for websockets

docs/openapi.yaml, src/api/query-helpers.ts, src/api/routes/address.ts, src/api/routes/ws/socket-io.ts, src/api/routes/ws/ws-rpc.ts, src/datastore/common.ts, src/datastore/memory-store.ts, src/datastore/postgres-store.ts, src/tests/api-tests.ts, src/tests/datastore-tests.ts
This PR adds `at_block` query param for all `/address` endpoints to get data till that block height.  It also checks for exclusive params `height`  and `unanchored`.  It changes a little bit of the structure of involving methods. 
For details refer to issue #803
=> Add `at_block` query param for `/address` endpoints

client/README.md, readme.md
Add subscription examples to WebSocket/Socket.io updates. Add a reference to the client README from the main project README.
=> chore: add a reference to the client readme, expand docs

.github/workflows/stacks-blockchain-api.yml, Dockerfile, docker/stx-rosetta.Dockerfile
This patch upgrades our `build-publish` Github actions step to use `docker/build-push-action@v2`. It also makes a few improvements:
- Push images to `blockstack/` and `hirosystems/` on Docker hub
- Limit `branch` event hook to only run actions on `master` and `develop` to avoid duplicating work with every PR push
- Adds `cmake` dependency to Dockerfiles so CPU profiling tools work correctly
- Checks out the repo with full depth so git tags work correctly
Closes #832 
No
No
=> Move build-publish Github actions to docker/build-push-action@v2

.github/workflows/stacks-blockchain-api.yml
This patch fixes the `git-info` build step for Docker Github actions.
=> fix: set explicit context for docker builds in github actions

src/api/routes/tx.ts, src/datastore/postgres-store.ts, src/tests/api-tests.ts
Regression introduced in https://github.com/hirosystems/stacks-blockchain-api/pull/807
Contract-call txs are not being constructed properly, see https://stacks-node-api-pr-877.stacks.co/extended/v1/tx
=> chore: fix missing contract-call tx data in tx list endpoint response

src/api/routes/debug.ts, src/datastore/postgres-store.ts, src/tests/api-tests.ts
Fix another bug introduced in #807.
Contract-call tx args were missing from the endpoint
`/extended/v1/address/<principal>/transactions_with_transfers`
=> Fix contract-call tx bug in `address/<principal>/transactions_with_transfers`

.github/workflows/stacks-blockchain-api.yml, overview.md
Experimenting with github-cache support for intermediate docker layers in order to speed up the `stacks-node` rust build within the docker image build step
=> chore: cache docker layers in to speed up stacks-node build CI step

src/datastore/postgres-store.ts, src/tests-rosetta/api.ts, src/tests/api-tests.ts, src/tests/microblocks-tests.ts
Adds the rest of abi columns for the remaining `txs` queries.
#858
=> fix: get abi for all tx queries

src/api/routes/contract.ts, src/datastore/common.ts, src/tests/api-tests.ts
Fix a regression introduced in #860 where the `smart_contracts` table `abi` column was changed from `text` to `jsonb`. The sql query responses also started returning a JSON object rather than a string, which ended up propagating to the http response for `/extended/v1/contract/<contract-id>`. 
This broke various products like the Explorer which attempted `JSON.parse(response.abi)`.
=> fix: regression with `contract` http response `abi` field

src/datastore/postgres-store.ts, src/tests/api-tests.ts, src/tests/test-helpers.ts
Follow up to fixes related to #807 
This PR parses mempool tx abi retrievals in our /v1 endpoints.
It also creates a couple of test helpers that build blocks and mempool txs easily, which would be expanded in the future as required.
=> fix: add parsed abi to mempool tx endpoints

.github/workflows/stacks-blockchain-api.yml
Closes https://github.com/hirosystems/stacks-blockchain-api/issues/867
=> chore: upgrade github action codecov v1 (deprecated) to codecov v2

.github/workflows/stacks-blockchain-api.yml
Currently on releases, docker tagging is broken due to the recent refactoring in the GH actions workflow. This should help fix it by passing the release version directly to the metadata actions.
=> ci: fix docker tagging on release

src/datastore/postgres-store.ts
Event replay/import was failing if a `/attachments/new` event was received out-of-order from the block/tx that anchors it:
```
Raw event requests processed: 94% (102200 / 108623)
Raw event requests processed: 95% (103200 / 108623)
Raw event requests processed: 96% (104300 / 108623)
Raw event requests processed: 97% (105400 / 108623)
Raw event requests processed: 98% (106500 / 108623)
{"message":"Could not find transaction 0xc9c246838ac346ac5b2167bf73e7f20d9e3a431a902713a4538fe700a8d80f42 associated with attachment","level":"warn","timestamp":"2021-12-21T18:48:35.423Z"}
{"level":"error","message":"Error processing new attachment message Could not find tx index for subdomain entry: {\"name\":\"id.stx\",\"namespace_id\":\"stx\",\"fully_qualified_subdomain\":\"peterdutoit.id.stx\",\"owner\":\" …
```
=> hotfix: ignore out of order attachments failing to resolve tx data

.github/workflows/stacks-blockchain-api.yml, package.json
Closes https://github.com/hirosystems/stacks-blockchain-api/issues/941
Adds a couple steps to the CI `test` job which installs dependencies in the `client` and `docs` directories. If there are any issues during the installation, they should now be caught before making their way to the `master` branch.
I also removed the notification jobs in the main CI workflow since they're not helpful anymore as Hiro doesn't use Slack.
No
=> ci: test installing client and docs deps

src/api/controllers/db-controller.ts, src/api/routes/tx.ts, src/datastore/common.ts, src/datastore/memory-store.ts, src/datastore/postgres-store.ts, src/tests/api-tests.ts, src/tests/datastore-tests.ts
Closes #924
Paginating txs by block wasn't working correctly due to lack of ordering, so each page would have random-looking txs that could have been included in a previous page, as well as potentially never getting a full list of txs from ones randomly left out.
The first commit in this PR cleans up some long-standing TODOs around sql transaction integrity for fetching txs lists.
=> fix: tx pagination failing due to lack of ordering #924

src/migrations/1640210247253_latest_contract_txs-canonical.ts, src/tests/api-tests.ts
Fixes duplicate txs regression in the `/transactions` endpoint for smart contracts where we would return non-canonicals too.
```
INNER JOIN txs USING (tx_id)
WHERE
numbered_txs.r <= 50
AND txs.canonical = TRUE
AND txs.microblock_canonical = TRUE
```
=> fix: join canonical txs on latest_contract_txs view

.github/workflows/project-automation.yml
Adds a new GH workflow that will add auto-generated PRs (e.g. from dependabot or snyk) to the Auto-generated PRs column in the API org dashboard.
cc @saralab
=> chore: add project automation gh workflow

src/api/controllers/cache-controller.ts, src/api/init.ts
Fixes caching issue with certain CDNs (e.g. Cloudflare) where intermediate caching will only be performed if the `304 CACHE OK` response _also_ includes the `Cache-Control` headers.
Cloudflare will perform intermediate caching when the following page rules are applied for `/v1/extended/*`:
=> fix: ensure `Cache-Control` is specified in 304 response

.env, .vscode/launch.json, readme.md, src/helpers.ts, src/index.ts
- Add `writeonly` API mode
- Unify `readonly` and `offline` modes into a single ENV setting alongside `writeonly`
- Update README
Closes #965 
TODO: Test in a dedicated deployment to measure performance and any other considerations that could've been missed cc @CharlieC3
=> feat: add write-only mode

client/README.md
This PR
* adds a link to the documentation of the client library in the README
* fixes #979
=> Fix: add link to client library documentation

src/datastore/postgres-store.ts, src/migrations/1588261750265_nft_events.ts, src/migrations/1636130197558_nft_custody.ts, src/migrations/1640037852136_nft_custody_unanchored.ts, src/test-utils/test-builders.ts, src/tests/api-tests.ts, src/tests/token-tests.ts
* Fixes an edge case in which an NFT could have several sequential events all in the same `block_height` (i.e. in different microblocks for the same block) and events would be returned in the wrong order for that block
* Optimizes some indexes on `nft_events` including the addition of a "mint events" index
* Optimizes indexes on the `nft_custody` materialized views
* Fixes `tx_index` and `event_index` on test block builders
=> fix: nft event sorting

.env, src/datastore/postgres-store.ts
Adds primary pg server .env vars for `PgNotifier` to use.
Related to #990
=> feat: use primary pg server for notifier

src/api/pagination.ts, src/errors.ts, src/tests/api-tests.ts
This PR updates the errors in pagination queries to the custom error created in PR #864. It sends 400 status code and does not spam the log messages.
For details refer to issue #854
=> Return 400 on invalid pagination query

.github/workflows/ci.yml, package.json
* Changed the name of the main workflow to just "CI". It was originally given the same name as the repository when GH Actions was much newer, and was a requirement for something hacky we were doing back then. It's not necessary anymore.
* Removed the Slack notify jobs from the CI workflow.
No
No
=> ci: update CI workflow and remove slack notifs

readme.md
Add readme badges for:
* Latest github release version w/ link
* Docker image downloads w/ link (using the legacy `blockstack` user because it has more downloads, but linking to the updated `hirosystems` image)
* NPM client library to increase discoverability
Updated a couple references from `blockstack/stacks-blockchain-api-standalone` to `hirosystems/stacks-blockchain-api-standalone`
=> chore: add additional readme badges

.github/dependabot.yml
https://docs.github.com/en/code-security/supply-chain-security/keeping-your-dependencies-updated-automatically/configuration-options-for-dependency-updates#open-pull-requests-limit
> By default, Dependabot opens a maximum of five pull requests for version updates. Once there are five open pull requests, new requests are blocked until you merge or close some of the open requests, after which new pull requests can be opened on subsequent updates. Use open-pull-requests-limit to change this limit. This also provides a simple way to temporarily disable version updates for a package manager.
> 
> This option has no impact on security updates, which have a separate, internal limit of ten open pull requests.
=> chore: configure dependabot to only open PRs for security issues

src/datastore/postgres-notifier.ts
Configure `pg-listen` reconnection settings to retry indefinitely while the database is restarting.
Fixes #960
=> fix: reconnect broken pgnotify clients

.env, src/datastore/postgres-store.ts, src/index.ts, src/tests-bns/api.ts, src/tests-bns/bns-integration-tests.ts, src/tests-bns/setup.ts, src/tests-rosetta-cli-construction/setup.ts, src/tests-rosetta-cli-construction/validate-construction.ts, src/tests-rosetta-cli-data/setup.ts, src/tests-rosetta-cli-data/validate-rosetta.ts, src/tests-rosetta/account-tests.ts, src/tests-rosetta/api.ts, src/tests-rosetta/block-tests.ts, src/tests-rosetta/setup.ts, src/tests-tokens/setup.ts, src/tests-tokens/tokens-metadata-tests.ts, src/tests/api-tests.ts, src/tests/cache-control-tests.ts, src/tests/datastore-tests.ts, src/tests/import-genesis-tests.ts, src/tests/microblocks-tests.ts, src/tests/socket-io-tests.ts, src/tests/token-tests.ts, src/tests/v2-proxy-tests.ts, src/tests/websocket-tests.ts
Closes https://github.com/hirosystems/stacks-blockchain-api/issues/1046
Use the pg connection `application_name` string property to specify usage context. This was previously left undefined which makes it difficult to determine which API instances are using connections or what purpose a give connection is serving.
This is a free-form value, the PR uses the convention:
`<app instance name>:<optional datastore instance scope>;<connection instance scope>`
The app instance name is read from the env var `PG_APPLICATION_NAME` (or `PG_PRIMARY_APPLICATION_NAME` when applicable), which could be set to something like the pod name.
The usage scopes are specified in code, e.g. `event-replay`, `notifier`, `init-connection-poll`, the run-mode, etc.
Examples: …
=> feat: add usage details for each pg connection via application_name

src/datastore/postgres-store.ts, src/migrations/1640651533899_principal_stx_txs.ts
* Add `microblock_sequence` and `tx_index` columns to `principal_stx_txs`
* Sort via these columns when querying for `/transactions`
Closes #1050
=> fix: principal_stx_txs sorting

src/datastore/postgres-store.ts, src/migrations/1643755236533_chain_tip.ts, src/tests-bns/api.ts, src/tests-bns/bns-integration-tests.ts, src/tests/api-tests.ts, src/tests/cache-control-tests.ts, src/tests/datastore-tests.ts
* Calculate block height, leading block hashes, leading microblock hash, and transaction counts in a materialized view
* Substitute all `block_height` calculations for a SELECT against the new view
* Substitute all `COUNT(*)` queries for their respective stats in the view
=> feat: add `chain_tip` materialized view to track chain tip stats

src/datastore/postgres-store.ts, src/migrations/1636130197558_nft_custody.ts, src/migrations/1640037852136_nft_custody_unanchored.ts, src/tests/token-tests.ts
Consider `event_index` too for sorting in all NFT endpoint queries, in case different events for the same NFT come by in the same transaction.
Closes #1060
=> fix: sort NFT events by event_index too

.github/workflows/gh-pages.yml
Updates the name of the referenced CI workflow to kick off the gh-pages workflow.
This should fix the problem where the gh-pages aren't updated after a release.
=> ci: update gh-pages workflow

overview.md
As a user, while reviewing the architecture overview, I noticed the missing reference to the path in which the Express.js route may have been residing, so I wanted to make it more explicit as to where they are living in this doc-change.
Please disregard and close this PR if I misinterpreted the intent. Perhaps the correct directory reference would still be helpful for the general audience.
=> Add the missing "routes" path to the overview guide for completeness

docs/openapi.yaml
Cleaned up references to subdomain endpoints that haven't been implemented yet
=> chore: remove unimplemented subdomain references

src/datastore/postgres-store.ts, src/migrations/1640651533899_principal_stx_txs.ts, src/test-utils/test-builders.ts, src/tests/api-tests.ts
Add the `canonical` and `microblock_canonical` columns to the `principal_stx_txs` table in order to update them with block and microblock re-orgs correctly.
This has the added benefit of keeping all filtering done over the `principal_stx_txs` table and only using `txs` for the final JOIN to get additional transaction info, which in turn makes the `/transactions` query much faster.
This is an example output from EXPLAIN ANALYZE, showing only the indices `principal_stx_txs_principal_index` and `txs_tx_id_index` are needed to gather results in less than 1ms:
```
Nested Loop  (cost=403.76..805.93 rows=68 width=44) (actual time=0.035..0.048 rows=6 loops=1)
->  Limit  (cost=403.76..403.88 rows=50 width=47) (actual time=0.028..0.030 rows=6 loops=1)
->  Sort  (cost=403.76..403.99 rows=95 …
```
=> fix: capture re-organized txs correctly in `/extended/v1/:address/transactions`

src/import-v1/index.ts, src/migrations/1608030374841_namespaces.ts, src/migrations/1608030374842_names.ts, src/migrations/1610030345948_subdomains.ts
This patch temporarily disables indices on the `subdomains`, `zonefiles`, `namespaces`, and `names` tables before subdomain import, and also removes unused indices from these tables.
From postgres docs on [populating a database](https://www.postgresql.org/docs/current/populate.html#POPULATE-RM-INDEXES):
> If you are adding large amounts of data to an existing table, it might be a win to drop the indexes, load the table, and then recreate the indexes.
Instead of dropping and re-creating, this code just disables and reindexes them after import is complete via the use of the `indisready` and `indisvalid` [index state flags](https://www.postgresql.org/docs/current/catalog-pg-index.html).
On local tests, it now takes ~2 seconds to import 10,000 subdomains when before this change it took ~30 …
=> fix: deactivate bns table indices before subdomain import

src/api/routes/ws/socket-io.ts, src/api/routes/ws/ws-rpc.ts, src/datastore/postgres-store.ts, src/tests/socket-io-tests.ts, src/tests/websocket-tests.ts
`block_height` was being sent incorrectly to the ws/socket.io handlers when a transaction was confirmed in a microblock, causing the call to `getAddressTxsWithAssetTransfers` to return empty results.
This patch also fixes some race conditions and flaky tests that happened from socket messages not being awaited correctly.
Fixes #1085
=> fix: send address tx updates correctly on microblocks

.github/workflows/ci.yml
Adds a step to the CI workflow to send a Github notification upon release.
=> ci: add step to send discord notif on release

src/datastore/postgres-store.ts, src/tests/api-tests.ts
This patch fixes a query statement when calculating the response for `/extended/v1/address/:addr/transactions` endpoint where even though the tx list and total was being calculated correctly, the `JOIN` with the `txs` table could bring a duplicate tx entry in the case of a re-org.
=> fix: filter canonical txs correctly for account tx history

docker/docker-compose.dev.postgres.yml, docker/docker-compose.yml, readme.md, src/api/controllers/cache-controller.ts, src/api/routes/address.ts, src/api/routes/block.ts, src/api/routes/status.ts, src/api/routes/tokens/tokens.ts, src/api/routes/tx.ts, src/datastore/common.ts, src/datastore/memory-store.ts, src/datastore/postgres-store.ts, src/migrations/1647573802137_mempool_digest.ts, src/tests/cache-control-tests.ts
This PR adds `ETag` cache support for mempool endpoints.
- Creates a new `mempool_digest` materialized view that calculates a pending mempool tx digest string only for pg14+. A version check is added to disable this string for earlier pg versions.
- Adds a new `mempool` entry to response locals to keep and validate this `ETag`.
- Installs the new cache handler in all mempool-sensitive endpoints, and adds chain tip handlers to endpoints that didn't have them before.
- Upgrade the postgres version used in our docker compose files to 14
Closes #879
=> feat!: add mempool endpoint cache handlers

docs/api/rosetta/rosetta-construction-preprocess-response.example.json, docs/openapi.yaml, src/tests-rosetta/api.ts
This PR adds a test, and example in the documentation for `construction/preprocess` for `stack_stx`.
Test was added to increase code coverage for Rosetta tests.
For details refer to issue #1000
=> Example and test for contract call in `/rosetta/v1/construction/preprocess`

src/api/controllers/db-controller.ts, src/test-utils/test-builders.ts, src/tests-rosetta/api.ts
This PR loads the relevant transaction in `getRosettaTransactionFromDataStore`.
For details refer to issue #1008
=> Load relevant transaction

src/datastore/postgres-store.ts, src/tests/api-tests.ts, src/tests/datastore-tests.ts
Closes #1119
A bug in re-org handling for the `principal_stx_txs` resulted in some transactions being incorrectly filtered out of results from the `/extended/v1/address/:principal/transactions` endpoint. 
For example tx `0x9e3091dbb810f21147474ef835f22545af0988976dd48985270a7119817f107c`: 
* Source of truth, shows the tx as canonical: https://stacks-node-api.mainnet.stacks.co/extended/v1/tx/0x9e3091dbb810f21147474ef835f22545af0988976dd48985270a7119817f107c
* Bugged response, missing the tx: https://stacks-node-api.stacks.co/extended/v1/address/SP3573HMB9SPCTMT85YS85KEPYCX33E6MZGQ5QB2A/transactions?limit=30&offset=0&unanchored=true
This PR fixes the "missing txs for an address" bug, but it will _not_ fix an associated `count/total` bug related to the same issue. Fixing that requires a …
=> fix: missing txs from /extended/v1/address/:principal/transactions #1119 #1098

docs/api/bns/subdomains/subdomains-list.example.json, docs/api/bns/subdomains/subdomains-list.schema.json, docs/openapi.yaml, src/api/routes/bns/names.ts, src/datastore/common.ts, src/datastore/postgres-store.ts, src/tests-bns/api.ts
This PR creates an endpoint for fetching the list of `fully_qualified_subdomain` of subdomains for a specific `name` and returning the array of strings in response. The endpoint is as follows:
```
/v1/names/:name/subdomains_list/
```
For details refer to issue #1097
=> Fetch subdomains list for a name

src/datastore/common.ts, src/datastore/postgres-notifier.ts, src/datastore/postgres-store.ts, src/event-stream/tokens-contract-handler.ts
Some metadata notifications were too big, causing postgres to log errors such as:
```
2022-03-26 02:21:13.908 UTC [59] ERROR:  payload string too long
2022-03-26 02:21:13.908 UTC [59] STATEMENT:  NOTIFY "stacks-api-pg-notifier", '{"notification":{"type":"tokenMetadataUpdateQueued","payload":{"entry":{"queueId":190,"txId":"0x919a0f6831ca0b89a9ab6965323d777e159a42dd66b28d6b1e081a0c23f7e996","contractId":"SPEFVJJXM9BT0PP3H2S6V6029SWF4B92RCJFE1Y0.laser-eyes","contractAbi":{"functions":
... lots of additional data ...
{"access":"variable","name":"m_update_price","type":"uint128"}]},"blockHeight":35022,"processed":false}}}}'
```
This PR sends only the queue entry ID through notifications and queries the complete object on the other side.
Fixes #1126
=> fix: shorten token metadata pg notifications

src/api/init.ts, src/api/routes/bns/names.ts, src/datastore/postgres-store.ts, src/helpers.ts, src/migrations/1636130197558_nft_custody.ts, src/migrations/1640037852136_nft_custody_unanchored.ts, src/test-utils/test-builders.ts, src/tests-bns/api.ts, src/tests-bns/bns-integration-tests.ts, src/tests/datastore-tests.ts, src/tests/token-tests.ts
This PR fixes a bug where the owner of a BNS name was not correctly reported through the `/v1/names/[:name]` endpoint.
The `names` table does not really track true name ownership, given that it is mostly updated when there is a zonefile change or a set of specific contract calls, causing re-orgs not being accounted for correctly. The `nft_custody` view is now used to get the latest owner given that a name is also an NFT and we get all events for it.
Incidentally, this also fixes a previously unknown bug where `nft_custody` was not being refreshed on a deep chain re-org.
Closes #1158
=> fix: `/v1/names/[:name]` name resolution

src/api/init.ts, src/api/routes/bns/addresses.ts, src/datastore/common.ts, src/datastore/postgres-store.ts, src/helpers.ts, src/tests-bns/api.ts
Resolves names correctly, considering both subdomains and names including those who were imported from Blockstack v1 and don't generate an NFT event.
Fixes #1172
=> fix: resolve bns names correctly in `/v1/addresses/stacks/[:address]`

package-lock.json, package.json
Fixes #1181
More context at https://github.com/hirosystems/stacks-encoding-native-js/pull/2
=> fix: use 128 max size when deserializing contract principals #1181

src/tests-tokens/strict-mode-tests.ts, src/token-metadata/tokens-contract-handler.ts, src/token-metadata/tokens-processor-queue.ts
Some contracts incorrectly return `none` in their `get-token-uri` functions, causing an infinite retry loop in strict token metadata mode.
=> fix: treat incorrect get-token-uri none values as undefined

package-lock.json, package.json
Closes https://github.com/hirosystems/stacks-blockchain-api/issues/1188
Fixes off-by-one bug while decoding through a serialized Clarity value array. If the last value was a single byte, it was skipped.
See https://github.com/hirosystems/stacks-encoding-native-js/pull/3 for more info.
=> fix: contract-call txs returning null args in some situations

src/api/controllers/db-controller.ts, src/api/routes/block.ts, src/datastore/common.ts, src/datastore/pg-store.ts, src/tests/api-tests.ts
This PR optimizes `/block` endpoint. It changes the previous approach of individual queries for each block to 3 queries for `blocks`, `txs`, and `microblocks`. 
For details refer to issue #1173
=> Optimized block endpoint

src/datastore/pg-write-store.ts, src/migrations/1621511823381_nft_metadata.ts, src/migrations/1621511832113_ft_metadata.ts, src/tests-tokens/tokens-metadata-tests.ts
This PR updates the insert query for `nft` and `ft` metadata. New approach upserts on constraint for `contract_id`.
For details refer to issue #1187
=> Upsert nft and ft metadata

src/api/routes/tx.ts, src/helpers.ts
The query params were discarded when redirecting to 0x prefix in `tx/tx_id` endpoint. This PR redirects with the given query params. 
For details refer to issue #1195
=> Included query params in redirecting to prefix 0x in tx endpoint

src/migrations/1655235863682_nft_custody_value_index.ts
Greatly optimizes the performance on a BNS name resolution query:
```sql
EXPLAIN ANALYZE (
SELECT
value
FROM
nft_custody
WHERE
recipient <> $1
AND value = ANY ($2));
```
Before 💀 
```
Gather  (cost=1000.00..9384.09 rows=8 width=20) (actual time=14.153..15.106 rows=0 loops=1)
Workers Planned: 2
Workers Launched: 2
->  Parallel Seq Scan on nft_custody  (cost=0.00..8383.29 rows=3 width=20) (actual time=11.470..11.470 rows=0 loops=3)
Filter: ((value = ANY ('{""\\x7830663066""}'::bytea[])) AND (recipient <> 'SP3D6PV2ACBPEKYJTCMH7HEN02KP87QSP8KTEH335.megapont-ape-club-nft'::text))"
Rows Removed by Filter: 89733
Planning Time: 0.116 ms
Execution Time: 15.117 ms
```
After 😎 
```
Bitmap Heap Scan on nft_custody  (cost=4.07..39.21 rows=8 width=20) (actual time=0.006..0.006 rows=0 loops=1)
Recheck …
```
=> fix: add value indices on nft_custody views

package-lock.json, package.json
Closes https://github.com/hirosystems/stacks-blockchain-api/issues/1217
Bumps `stacks-encoding-native-js` to a version that includes a binary for the linux-musl-arm64 target. 
See https://github.com/hirosystems/stacks-encoding-native-js/issues/4 for more info.
=> fix: arm64-alpine image, bump stacks-encoding-native-js #1217

src/api/controllers/cache-controller.ts, src/api/controllers/db-controller.ts, src/api/routes/tx.ts, src/datastore/common.ts, src/datastore/postgres-store.ts, src/tests/cache-control-tests.ts
Adds `ETag` header to `/extended/v1/tx/:tx_id` and `/extended/v1/tx/:tx_id/raw`.
Since transactions can be in the mempool or in the chain and they can later get re-orged, a new `ETagType.transaction` was added which builds the ETag using the `tx_id`, `index_block_hash` (if any), `microblock_hash` (if any), and `status` of the relevant transaction. This way, we'll get the best caching behavior even when the tx may be moved from block to microblock to mempool and back.
Closes #1225
=> feat: add cache control to `/extended/v1/tx/:tx_id`

src/datastore/postgres-store.ts, src/migrations/1643755236533_chain_tip.ts, src/migrations/1660595195398_materialized_view_indexes.ts
Refresh materialized views concurrently on production deployments so postgres doesn't hold an `AccessExclusiveLock` on key tables while the refresh is being done. This completely removes the deadlocks we were seeing in the DB, specially when receiving `/new_block` messages in quick succession or blocks with a large number of transctions, microblocks, or re-org depth.
Refreshes still happen non-concurrently in local deployments and tests to maintain consistency.
Fixes #1204
=> fix: refresh materialized views concurrently

docs/entities/transactions/transaction-4-coinbase-metadata.schema.json, docs/generated.d.ts, src/api/controllers/db-controller.ts, src/datastore/common.ts, src/datastore/helpers.ts, src/datastore/pg-store.ts, src/datastore/pg-write-store.ts, src/event-stream/reader.ts, src/migrations/1584619633448_txs.ts, src/migrations/1591291822107_mempool_txs.ts, src/rosetta-helpers.ts, src/tests/address-tests.ts, src/tests/mempool-tests.ts, src/tests/search-tests.ts, src/tests/tx-tests.ts
Closes https://github.com/hirosystems/stacks-blockchain-api/issues/1275
The new `coinbase-pay-to-alt-recipient` transactions are now being parsed, stored in pg, and the new coinbase `alt_recipient` property is returned on applicable requests.
For regular `coinbase` transactions, the `alt_recipient` property is null.
Note: internally, we are storing this in pg as a new tx type (with the new type ID), but when generating http responses, we normalize the type as `"tx_type": "coinbase"` so as not to cause unnecessary breaking changes for clients.
Pay-to-alt coinbase with standard principal recipient:
```json
{
"tx_id": "0x36604700e58ff2cb1a47d7185f528ae7af5365433df5c0c46449052e545e19f3",
"nonce": 4,
"fee_rate": "0",
"sender_address": "ST3GVG66JXT2WRW0KPP5849Q2EC4K1HCS85YHA8M3",
"sponsored": …
```
=> Implement support for `coinbase-pay-to-alt-recipient` txs

docs/entities/transaction-events/asset-types/transaction-event-asset.schema.json, docs/generated.d.ts, src/api/controllers/db-controller.ts, src/datastore/common.ts, src/datastore/helpers.ts, src/datastore/pg-store.ts, src/datastore/pg-write-store.ts, src/event-stream/core-node-message.ts, src/event-stream/event-server.ts, src/migrations/1588252682585_stx_events.ts, src/tests/tx-tests.ts
Closes https://github.com/hirosystems/stacks-blockchain-api/issues/1276
Implements parsing, storing, and returning the `memo` field that can be included in Stacks 2.1 `stx_transfer_event` events when the `stx-transfer-memo?` Clarity2 function is used. 
To test this, deploy a Clarity2 versioned-smart-contract with something like the contract code:
```clar
(stx-transfer-memo? 
u60
tx-sender
'ST2X2FYCY01Y7YR2TGC2Y6661NFF3SMH0NGXPWTV5
0x74657374206d656d6f206669656c64)
```
Note: you need to be able to construct and serialize a `versioned-smart-contract`, this PR adds that capability to stacks.js https://github.com/hirosystems/stacks.js/pull/1341
The resulting tx will have a stx-transfer event with the associated memo, e.g.:
```json
{
"event_index": 0,
"event_type": "stx_asset",
"tx_id": …
```
=> Support for Stacks 2.1 stx-transfer event memo field 

docs/entities/transfers/inbound-stx-transfer.schema.json, docs/generated.d.ts, src/datastore/pg-store.ts, src/tests/tx-tests.ts
Follow-up to https://github.com/hirosystems/stacks-blockchain-api/pull/1285 
Added support for returning STX transfers w/ memos to the `/address/<recipient>/stx_inbound` endpoint. In Stacks 2.1, smart contract txs (leveraging `stx-transfer-memo?`) can now send STX w/ memos in a way supported by most exchange deposit requirements without having to use the [`send-many-stx` work-around contract/tool](https://github.com/stacks-network/send-many-stx-cli)
=> [Stacks 2.1] Include `stx-transfer-memo` results in `/address/<recipient>/stx_inbound`

src/api/controllers/db-controller.ts, src/api/rosetta-constants.ts, src/api/routes/rosetta/construction.ts, src/api/routes/rosetta/mempool.ts, src/rosetta-helpers.ts, src/test-utils/test-builders.ts, src/tests-rosetta/api.ts
Closes https://github.com/hirosystems/stacks-blockchain-api/issues/1284
* Include `memo` from `stx-transfer-memo` events in Rosetta token transfer operations.
* Tests that `versioned-smart-contract` tx types are parsed correctly in Rosetta responses.
* Tests that `coinbase-pay-to-alt` tx types are parsed correctly in Rosetta responses.
* Clean up several weakly typed `strings` being used for RosettaOperationType fields.
* Fixes bug in API v5 / `develop` branch where Rosetta `memo` strings were no longer decoded from hex.
=> [Stacks 2.1] Rosetta - `stx-transfer-memo` events, misc. compatibility

src/rosetta-helpers.ts, src/tests-rosetta/api.ts
Fix bug in `develop` branch where Rosetta `memo` strings were no longer decoded from hex.
The code was trying to trim NULL bytes from a hex string, which previously used to be a string from `Buffer.from(memoBytes).toString()` in v4.
This fixes the expected response, and trims bytes off the Buffer before converting to string, rather than depending on undefined behavior with Buffer and trailing null bytes.
=> chore: fix bug with memo hex strings not decoded in Rosetta responses

running_an_api.md, running_api_from_source.md
Adds an additional line to the markdown docs for deploying the API:
```
3. Verify data is being written to the database: `select * from blocks limit 1;`
```
During the step to verify the DB is setup, running this query will confirm data is being written to the DB.
in the case where the blockchain was syncing from genesis *without* the event observer, then restarted with the event observer, the previous commands will make it appear as though the DB is fine, but not adding records. this single query will confirm if the API is running normally.
=> Update docs to include a simple sql query

readme.md, running_an_api.md, running_api_from_source.md, src/datastore/common.ts, src/datastore/postgres-store.ts, src/event-replay/event-replay.ts, src/event-replay/helpers.ts, src/import-v1/index.ts, src/index.ts, src/tests-bns/api.ts, src/tests-bns/v1-import-tests.ts
* Import BNS v1 data during replay: first names and namespaces, then TSV data, then subdomains
* Obtain genesis block information from TSV to be used in BNS import
* Modify BNS insertion data to mark all imported names at block 1 instead of block 0
=> fix: import BNS v1 data during event replay

src/datastore/postgres-store.ts
Adds a check for the `ECONNRESET` error code when connecting to postgres. This should help reduce API terminations when the postgres db is behind a proxy (e.g. istio).
Closes https://github.com/hirosystems/stacks-blockchain-api/issues/1299
No
No
Tested in k8s and verified fixed!
=> fix: add postgres connection error checking for ECONNRESET code

src/event-replay/event-replay.ts, src/migrations/1608030374841_namespaces.ts, src/migrations/1608030374842_names.ts, src/migrations/1610030345948_subdomains.ts
Add `index_block_hash` index to optimize re-org queries.
Also, go back to the default log level before importing BNS subdomains during replay.
=> feat: add indexes for index_block_hash on BNS tables

.env, readme.md, src/datastore/pg-write-store.ts, src/event-replay/event-replay.ts
In the last few months, Stacks blockchain traffic has increased substantially. This PR removes the real-time appending of node events to a TSV file because now that blocks are massive and mempool messages are much more frequent, we've started running into race conditions when appending to the text file.
TSV generation should only be done via `export-events` from now on.
=> fix: remove live tsv append

src/datastore/common.ts, src/datastore/pg-store.ts, src/datastore/pg-write-store.ts, src/event-stream/bns/bns-helpers.ts, src/migrations/1608030374842_names.ts, src/tests-bns/event-server-tests.ts
We used to assume BNS names could only have 1 event (register, transfer, etc.) per transaction, however, newer contracts like [ryder-handles-controller-v1](https://explorer.stacks.co/txid/SPC0KWNBJ61BDZRPF3W2GHGK3G3GKS8WZ7ND33PS.ryder-handles-controller-v1?chain=mainnet) are performing both `name-register` and `name-transfer` events at the same time which causes the API to return the wrong name owner. To fix this, we have to keep track of `event_index` in the names table and use that field to sort name changes on queries. 
This PR also fixes another bug that caused owner inconsistencies when multiple names were registered and transferred in the same block.
Fixes #1333
=> fix: support multiple BNS name events in the same transaction

docs/api/address/get-address-nft-events.example.json, docs/api/address/get-address-nft-events.schema.json, docs/openapi.yaml, src/api/routes/address.ts, src/datastore/pg-store.ts, src/tests/address-tests.ts
This reverts commit 65bb4e55fabf21a70183d2b16c8bc1f6f742d04e.
=> chore: revert commit 65bb4e5 which removed the /nft_events endpoint

src/api/init.ts, src/datastore/helpers.ts, src/datastore/pg-store.ts, src/tests-tokens/strict-mode-tests.ts, src/tests-tokens/tokens-metadata-tests.ts, src/tests/other-tests.ts, src/token-metadata/tokens-contract-handler.ts, src/token-metadata/tokens-processor-queue.ts
Express has an exception handler that resolves them gracefully, but we need to make sure we catch them on any query outside of it e.g. the token metadata handlers.
This PR:
* Adds exception handlers to all queries in the token metadata handlers
* Edits the error response to a 503 when a user calls an endpoint which results in a pg connection error
* Adds the new postgres lib's connection errors to the error handlers we have in place
=> fix: catch pg exceptions on queries outside of express

src/index.ts
=> fix: skip migrations on read-only start

.env, src/datastore/connection.ts, src/datastore/pg-store.ts, src/datastore/pg-write-store.ts, src/helpers.ts, src/shutdown-handler.ts, src/tests/datastore-tests.ts
* Add `PG_CLOSE_TIMEOUT` and `PG_PRIMARY_CLOSE_TIMEOUT` to control seconds before killing in-flight queries when closing `PgStore` and `PgWriteStore`. Fixes #1352 
* Add `STACKS_SHUTDOWN_FORCE_KILL_TIMEOUT` to control seconds before force-killing an API component when shutting down
* Add `READ ONLY` annotation to all `BEGIN` postgres transactions on `PgStore`. No real performance upgrades from this but it is an extra security measure to avoid any modifications to the DB during read-only API execution: https://www.postgresql.org/docs/current/sql-set-transaction.html
* Fix style for `async`/`await` pg transaction use
=> feat: add ENV configs for DB close and API shutdown timeouts

.github/workflows/ci.yml
Attempting to resolve a CI bug where `non-master` branch builds are overwriting the `-latest` tagged image in hub.docker.
=> do not tag latest on non-master branches

.github/workflows/ci.yml
fixing an issue where non-master branch builds are tagging containers with `-latest` and overwriting the "real" `latest` image
=> chore: disabling latest tag on non-master branch

.github/workflows/ci.yml, src/datastore/postgres-store.ts, src/tests-bns/event-server-tests.ts
This PR is a v5 backport fix of the issues solved in #1337 for API v6. Since we're still working on deploying v6 in our environment, this patch will allow us to serve correct ownership data in the meantime.
**NOTE:** This only fixes the *owner* of the name, not its *status* e.g. a name's status could still appear as `name-register` when it should be `name-transfer`
=> fix: v5 backport BNS ownership for multiple name operations in the same transaction

.github/workflows/ci.yml
There seems to be conflicting configuration settings when it comes to _not_ tagging with `latest`.   The Priority attribute might be invalidating the `type=raw,value=latest,enable={{is_default_branch}}` line which is last in the list so it gets superseded by `type=semver,pattern=...` and triggers the default `flavor` attribute behavior.  I can try to move the line up, but that might cause unwanted tagging behaviors for the semver tags.
That being said it looks like setting the `flavor` param is a best way to _not_ tag with the `lastest`.
=> ci: add flavor param

.env, docs/socket-io/index.d.ts, src/api/routes/ws/channels/socket-io-channel.ts, src/api/routes/ws/channels/ws-rpc-channel.ts, src/api/routes/ws/web-socket-transmitter.ts, src/tests/socket-io-tests.ts
We currently process and send all web socket messages synchronously and in series, which may be causing OOM errors in node.js when a huge anchor block comes that tries to send potentially hundreds of messages to dozens of subscribers.
This PR:
* Adds a priority queue to handle incoming web socket messages from API read-only nodes, with a concurrency of `1` and a max job timeout of 5 seconds (e.g. 5 seconds to send a single `block` update to all block subscribers).
* Adds configurable 5 second timeouts to:
* Client ping/pong
* Each message sent to each client
* Per update enqueued to all clients
* Changes the ws-channel message send operations to be processed in parallel, so we can dispatch one message to all channels immediately and we can better use the 5 seconds we have available.
cc …
=> fix: handle websocket messages with a priority queue

src/datastore/pg-store.ts, src/tests/datastore-tests.ts
Get Rosetta's latest block from the `chain_tip` materialized view instead of the `blocks` table, so we can avoid race conditions while refreshing this view allowing us to return consistent transaction results across `/status` and `/block`.
Fixes #1370
=> fix: get rosetta latest block from chain_tip view

.github/workflows/regtest-image.yml
Add workflow_dispatch config for building the standalone regtest docker image. This needs to be in master for it to show up in the github "Run workflow" UI.
=> ci: add workflow dispatch for standalone docker image build

.github/workflows/regtest-image.yml, docker/standalone-regtest.Dockerfile
Follow up to the standalone regtest image implemented in https://github.com/hirosystems/stacks-blockchain-api/pull/1476
> ... new standalone regtest dockerfile which is epoch 2.1 capable. This is intended to be used in CI/local testing as an alternative to the existing standalone docker image (which uses a mocknet stacks-node that is non-functional for epoch 2.1 testing).
This PR adds a workflow_dispatch (manually triggered CI) config to build the new image. 
* Multi-platform images are built (for both arm64 and x86).
* This currently uses git commit SHAs for building both the API and stacks-node, so the git tag-based version reporting (`/v2/info` and `/extended/v1/status`) will show the commit hashes but the branch/version will be stubbed. This can be fixed once the Stacks 2.1 related …
=> Publish standalone regtest image

src/tests-bns/event-server-tests.ts
Fix bns test that is causing a timeout on build. 
https://github.com/hirosystems/stacks-blockchain-api/actions/runs/3678727169
Test is passing CI, but failing build. Test still confirms that the post request returns before bns import has finished.
=> Fix bns test

content/how-to-guides/how-to-run-api-node.md, content/how-to-guides/how-to-run-mainnet-node.md, content/how-to-guides/how-to-run-testnet-node.md
- This was identified by an external dev where there were gaps between the "How to run API nodes" file on the Github vs Docs site". Hence updated the config.toml file location. 
- Also, cleaned up how-to run API node doc to include the correct CLI commands.
- Fixed broken links for Stacks-blockchain API
**Discord reference**: https://discord.com/channels/621759717756370964/909867922971820102/1050836732695814264
=> Docs content: Updated config.toml location in the how to run API node doc

src/api/pagination.ts, src/api/routes/address.ts, src/api/routes/tx.ts, src/tests/pagination-tests.ts
Addressing https://github.com/hirosystems/stacks-blockchain-api/issues/1507
Max paging query limits were lowered causing backward compatibility issues with the explorer.
I am adding a max limit override to getPagingQueryLimit so that we can keep the new paging query limit categorization system without adding additional micro-categories that ostensibly only serve to raise the max limits of a few endpoints to create backwards compatibility. This approach also provides additional flexibility in the future to override query limits on endpoints that need to differ from their natural category query limits.
Added a test for the new override functionality.
The changes that were made to the query limits are below, copied from the PR that introduced them. I am override the max query limit for all …
=> Fix: make query limits backwards compatible

package-lock.json, package.json, src/btc-faucet.ts, src/ec-helpers.ts, src/helpers.ts, src/tests/helpers-tests.ts
* Fixes bug where taproot/segwit_v1 BTC addresses were not reported as a valid BTC address.
* Fixes warning logs about using taproot addresses which had only partial support prior to this lib update.
=> chore: bump bitcoinjs-lib to latest (fixes warnings related to taproot/segwit_v1 addresses)

src/index.ts, src/token-metadata/tokens-processor-queue.ts
The current call to `drainDbQueue` on the token processor during boot sequence waits for the `queue.onEmpty` promise to resolve before continuing to launch the API server.
This promise is supposed to wait until every token is processed, so if the token queue has a lot of work (and especially if it has `STACKS_API_TOKEN_METADATA_STRICT_MODE` enabled) this could lead to a very long (or infinite) wait time for the token metadata work to conclude, preventing the API server from ever launching.
This PR only changes the call so the first few tokens are enqueued and the API launch can proceed as expected. The rest of the token queue will be processed automatically afterwards in a non-blocking way.
Fixes #1482
=> fix: prevent token metadata processor from blocking api launch

migrations/1673632140730_pox_state_fix.js, src/datastore/pg-store.ts
Fixes bug with the `pox_v1_unlock_height` pg column being too small (int32 vs int64)
Error report:
```
{"level":"error","message":"error processing core-node /new_block: PostgresError: value \"4294967285\" is out of range for type integer value \"4294967285\" is out of range for type integer","stack":"PostgresError: value \"4294967285\" is out of range for type integer\n    at ErrorResponse (/home/admin/stacks-blockchain-api/node_modules/postgres/cjs/src/connection.js:765:26)\n    at handle (/home/admin/stacks-blockchain-api/node_modules/postgres/cjs/src/connection.js:468:6)\n    at Socket.data (/home/admin/stacks-blockchain-api/node_modules/postgres/cjs/src/connection.js:312:9)\n    at Socket.emit (node:events:513:28)\n    at addChunk (node:internal/streams/readable:315:12)\n    at …
```
=> fix: use pg bigint for `pox_v1_unlock_height` column

src/migrations/1673895089997_contract_logs_contract_identifier_index.ts
For SIP-013 SFT support, the Token Metadata Service needs to scan the `contract_logs` table to look for `sft_mint` events emitted by a SIP-013 contract so it can determine the number of tokens declared in the contract. https://github.com/hirosystems/token-metadata-service/issues/56
This index optimizes queries that use `contract_identifier` as the main filter column for this table.
=> fix: add contract_identifier index on contract_logs table

src/datastore/pg-store.ts, src/tests/block-tests.ts
The endpoint for retrieving blocks was returning the microblocks_streamed field in reverse order. This commit changes the sorting from descending to ascending to match the expected behavior.
For details refer to issue #1524
=> fix: fixed the order of microblocks_streamed

docs/openapi.yaml, src/helpers.ts, src/tests/other-tests.ts
Fixes https://github.com/hirosystems/explorer/issues/973
The liquid stx amount that is calculated from the postgres db is accurate (or at least it matches the `total_liquid_supply_ustx` value reported by the stacks-node):
* `/extended/v1/stx_supply - unlocked_stx: 1357774888442244` matches:
* `/v2/pox - total_liquid_supply_ustx: 1357774888442244`
However, the `total_stx` value is incorrect, and is currently _greater_ than the liquid stx supply.
The `total_stx` value is a constant that was copied from the Stacks 1.0 codebase, see https://github.com/hirosystems/stacks-blockchain-api/pull/466
> This was copied from the legacy 1.0 API codebase.
https://github.com/hirosystems/stacks-blockchain-api/blob/b6018dc06ae2dabccc85e93090fccc267e054b8f/src/helpers.ts#L220-L222
Here's what the [Stacks …
=> fix: update total STX supply to the year 2050 projected amount

src/migrations/1674838340313_contract_logs_block_height_index.ts
On boot, the Token Metadata Service needs to scan the `contract_logs` table to look for SIP-019 notifications that might have happened between two block heights. This index makes the performance of this query trivial on the API database.
=> fix: add block_height index to contract_logs

.github/workflows/ci.yml, docker/docker-compose.dev.stacks-krypton-2.1-transition.yml, docker/docker-compose.dev.stacks-krypton.yml, migrations/1666703991492_pox_events.js, src/api/controllers/db-controller.ts, src/datastore/common.ts, src/datastore/helpers.ts, src/datastore/pg-write-store.ts, src/ec-helpers.ts, src/event-stream/pox2-event-parsing.ts, src/event-stream/reader.ts, src/pox-helpers.ts, src/test-utils/test-helpers.ts, src/tests-2.1/pox-2-btc-address-formats.ts, src/tests-2.1/pox-2-burnchain-delegate-stx.ts, src/tests-2.1/pox-2-delegate-aggregation.ts, src/tests-2.1/pox-2-delegate-stacking.ts, src/tests-2.1/pox-2-stack-extend-increase.ts, stacks-blockchain/docker/Dockerfile
Support parsing `delegate-stx` BitcoinOps as synthetic tx. Uses new pox2 contract print implemented in https://github.com/stacks-network/stacks-blockchain/pull/3503/commits
=> [Stacks 2.1] `delegate-stx` Bitcoin-op parsing

docs/openapi.yaml
Updated maximum and example values for the Get mempool transitions.
Removed default value.
The openAPI.yaml file is updated.
=> OpenAPI: Get mempool transations - Removed default value and updated max and example values

src/datastore/common.ts, src/datastore/pg-write-store.ts, src/tests/mempool-tests.ts
Fixes https://github.com/hirosystems/stacks-blockchain-api/issues/1557, related to https://github.com/hirosystems/stacks-blockchain-api/issues/1428
This adds a function which detects any transactions that are erroneously marked as both pending in the mempool table and also confirmed in the mined txs table.
The function is called after all other sql writes during block & microblock ingestion, but before any reads or view refreshes that depend on the mempool table.
This should be a safe work-around for whatever bug is causing the underlying problem.
=> fix: ensure transactions are never reported as both pending and confirmed

src/event-replay/event-replay.ts, src/event-replay/helpers.ts, src/event-replay/reverse-file-stream.ts, src/event-stream/event-server.ts, src/import-v1/index.ts, src/tests-bns/event-server-tests.ts, src/tests-event-replay/helper-tests.ts, src/tests-event-replay/import-export-tests.ts
Fixes a bug during event-replay where the "find last block from tsv file" code isn't working with the large mainnet tsv files we've been testing. 
I swapped that code out for a more optimized version implemented earlier for PR https://github.com/hirosystems/stacks-blockchain-api/pull/1166, which fixes the bug. 
I'm not able to reproduce the bug with small unit-testable input, but I've tested locally with a mainnet tsv file synced on my machine, and one synced from @wileyj. 
There was a race condition that caused the BNS import process to be started multiple times for both block-0 and block-1. This has also been fixed.
=> fix: bug with finding last block with some large tsv files

src/index.ts
Help debug https://github.com/hirosystems/stacks-blockchain-api/issues/1584 by including verbose error details in the `Warning: failed to connect to node RPC server at ...` error message.
Example output:
```
{"code":"ECONNRESET","errno":"ECONNRESET","level":"error","message":"Warning: failed to connect to node RPC server at 127.0.0.1:20443 request to http://127.0.0.1:20443/v2/info failed, reason: socket hang up","stack":"FetchError: request to http://127.0.0.1:20443/v2/info failed, reason: socket hang up\n    at ClientRequest.<anonymous> (/Users/matt/Projects/stacks-blockchain-api3/node_modules/node-fetch/lib/index.js:1491:11)\n    at ClientRequest.emit (node:events:513:28)\n    at ClientRequest.emit (node:domain:489:12)\n    at Socket.socketOnEnd (node:_http_client:518:9)\n    at …
```
=> chore: include error details in `failed to connect to node RPC...`

src/api/routes/stx-supply.ts, src/datastore/pg-store.ts, src/tests/cache-control-tests.ts
Fixes https://github.com/hirosystems/stacks-blockchain-api/issues/1590
Adds chaintip-based etag caching for the `/stx_supply` endpoints. This makes it so the pg query generally only needs to be ran once per block.
If the we still run into performance issues with this endpoint then we can add materialized view for it.
=> Fix: `/stx_supply` caching

.vscode/launch.json, .vscode/tasks.json, src/datastore/offline-dummy-store.ts, src/index.ts
Closes https://github.com/hirosystems/stacks-blockchain-api/issues/1391
The dummy storage instance was not being used when initializing in offline mode, which was causing the postgres connection to retry forever.
=> fix: postgres should not be required in `STACKS_API_MODE=offline` mode

src/api/routes/core-node-rpc-proxy.ts
Fix for issue #1065.
400 errors should be logged as `warning`.
=> fix: warning logger level for RPC proxy errors

docs/openapi.yaml, src/api/init.ts, src/api/routes/faucets.ts, src/btc-faucet.ts, src/errors.ts, src/tests-btc-faucet/faucet-btc-tests.ts
1 . Added middleware to BTC faucet endpoint to catch a specific exception if BTC_RPC_PORT & BTC_RPC_HOST are not defined and respond with 403 status code with the following message.  
{
"error": "BTC Faucet not fully configured.",
"success": false
}
2. Added a unit test to verify the above scenario. 
3. Added a new response type 403 in /extended/v1/faucets/btc endpoint in openapi.yaml file.  
For details refer to issue #1522
=> fix: disabled BTC faucet endpoint

src/api/routes/rosetta/construction.ts, src/helpers.ts
A previous version of the API used a version of stacks.js that happened to work with negative stx amount values. In the latest version, this triggers an error. 
Some consumers of the Rosetta layer were depending on negative STX amounts for the `fee` value in tx construction. This PR uses a `Math.abs(fee)` so that both negative and positive STX amounts should work.
Error report:
> upgrade @stack/transactions from "2.0.1" to "6.0.0", which change the implementation of intToBytes conversion
Before this commit, the intToBytes(condition.fee, false, 8) [here](https://github.com/hirosystems/stacks.js/blob/v2.0.1/packages/transactions/src/authorization.ts#L276) can handle negative value, and after this commit, this line will throw exactly the same exception we saw.  And at the same time,  custody …
=> fix: allow negative fee value in Rosetta tx construction

.github/workflows/ci.yml
Try to fix [issue](https://github.com/hirosystems/stacks-blockchain-api/issues/1593).
Lock `build-publish` action to the node version present on `.nvmrc` file.
1. Using an old Node (v12) version the issue is reproduced.
```
❯ nvm use 12
Now using node v12.22.12 (npm v6.14.16)
❯ npx rimraf ./lib && npm run generate-openapi && npm run build:node && npm run build:browser
Unexpected token '('
```
2. Using the `.nvmrc` Node (v16) version the issue is fixed.
```
❯ nvm use
Found '/Users/chris/dev/hiro/stacks-blockchain-api/.nvmrc' with version <v16>
Now using node v16.20.0 (npm v8.19.4)
❯ npx rimraf ./lib && npm run generate-openapi && npm run build:node && npm run build:browser
> @stacks/blockchain-api-client@0.1.2 generate-openapi
> npm run prep-openapi && openapi-generator-cli generate …
```
=> fix npm publish CI

.github/workflows/ci.yml, src/event-stream/reader.ts, src/helpers.ts, src/tests-subnets/subnet-tests.ts
Fixes #1616
Use the boot address as the tx signer for synthetic subnet burnchain-tx parsing. Previously it was using the address associated with the asset transfer, which would cause other queries to view those addresses as having issued nonce-incrementing txs.
=> fix(subnets): use boot address for burnchain-tx signer

.env, src/import-v1/index.ts, src/tests-event-replay/import-export-tests.ts
Issue: #1602 .
Summary: BNS imports are mean to run for L1 stacks node. When running for Subnets the node sync is not starting.
Solution: Create an environment variable that explicits the underlying node type. And check for the node type before starting the BNS importer.
=> add check for stacks node type before BNS import

docker/docker-compose.dev.subnets.yml, docker/subnet-node.Dockerfile, src/event-stream/core-node-message.ts, src/event-stream/reader.ts, src/helpers.ts, src/tests-subnets/l1-contracts/simple-ft-l1.clar, src/tests-subnets/l1-contracts/simple-nft-l1.clar, src/tests-subnets/l1-contracts/sip-traits.clar, src/tests-subnets/l1-contracts/subnet-traits.clar, src/tests-subnets/l1-contracts/subnet.clar, src/tests-subnets/l2-contracts/simple-ft-l2.clar, src/tests-subnets/l2-contracts/simple-nft-l2.clar, src/tests-subnets/subnet-tests.ts
An initial subnet-support PR had accidentally already been merged into the develop branch a while ago, and is difficult to revert.
So, we might as well merge in the latest subnet support into develop. This means the next release cut from develop will support subnets. 
Note: if additional API changes related to subnets are needed, then those will continue to go only into the `subnets` branch of the API.
=> Merge subnets into develop

docs/entities/address/address-nonces.example.json, docs/entities/address/address-nonces.schema.json, docs/generated.d.ts, src/api/routes/address.ts, src/datastore/pg-store.ts, src/tests/address-tests.ts
This PR adds mempool nonces to the response of `extended/v1/address/:stx_address/nonces` endpoint.
Issue [1342](https://github.com/hirosystems/stacks-blockchain-api/issues/1342).
=> add mempool nonces to address endpoint JSON response

src/datastore/pg-store.ts
Fixes https://github.com/hirosystems/stacks-blockchain-api/issues/1639
=> fix: generate synthetic `stx_unlock` rosetta operations for all locked accounts after pox2 force unlock

src/logger.ts
Auto logging configuration was set to `false`. Every received request need to be logged.
=> Enable requests logging

.env, src/index.ts
May close https://github.com/hirosystems/stacks-blockchain-api/issues/1584
For context, see comment https://github.com/hirosystems/stacks-blockchain-api/issues/1584#issuecomment-1530010417
=> fix: option to skip RPC request during init which may avoid startup deadlocks

.env, src/api/controllers/db-controller.ts, src/api/init.ts, src/api/rosetta-constants.ts, src/api/routes/address.ts, src/api/routes/bns/addresses.ts, src/api/routes/bns/names.ts, src/api/routes/bns/pricing.ts, src/api/routes/debug.ts, src/api/routes/rosetta/account.ts, src/api/routes/rosetta/block.ts, src/api/routes/rosetta/construction.ts, src/api/routes/rosetta/mempool.ts, src/api/routes/rosetta/network.ts, src/datastore/pg-store.ts, src/event-stream/bns/bns-helpers.ts, src/event-stream/event-server.ts, src/event-stream/reader.ts, src/helpers.ts, src/index.ts, src/token-metadata/tokens-contract-handler.ts, src/token-metadata/tokens-processor-queue.ts
Adds a new environment variable that can be used to specify the network (mainnet or testnet) for a given chain_id.
For example, the current subnet testnet chain_id is `0x55005500`. This can be configured with the env var:
```env
CUSTOM_CHAIN_IDS=testnet=0x55005500
```
Multiple values can be configured using comma-separated key-value pairs:
```env
CUSTOM_CHAIN_IDS=testnet=0x55005500,mainnet=12345678,mainnet=0xdeadbeaf
```
With the introduction of subnets, there is no longer a 1-to-1 mapping between chain_id and network name. For example, it's no longer `chain_id(0x00000001) === mainnet, chain_id(0x80000000) === testnet`. Any given chain_id can now be either testnet or mainnet. So the const enum mapping between chain_id<->network has been removed, and replaced with a function that …
=> feat: support custom chain_id (e.g. for subnets)

src/api/routes/address.ts, src/tests/mempool-tests.ts
Closes https://github.com/hirosystems/stacks-blockchain-api/issues/1685
The endpoint `/extended/v1/address/:principal/mempool` (AKA client function `getAddressMempoolTransactions`) was too strict and rejected contract-type principals to be queried.
=> fix: allow contract-principals in `/extended/v1/address/:principal/mempool` endpoint

src/datastore/pg-store.ts
Only a single `stx_unlock` Rosetta operation is being returned per block, even when multiple unlocks occur in a block. 
Here are two examples that should include a `stx_unlock` operation for address `SPVEW3RAESA4A4TG5R81A5D06MBMGV3EP0KABEXK`, but do not and only contain a single `stx_unlock` for another address:
```shell
curl -X POST https://api.mainnet.hiro.so/rosetta/v1/block -H 'Content-Type: application/json' -d '{"network_identifier":{"blockchain":"stacks","network":"mainnet"},"block_identifier":{"index": 110979}}'
```
```shell
curl -X POST https://api.mainnet.hiro.so/rosetta/v1/block -H 'Content-Type: application/json' -d '{"network_identifier":{"blockchain":"stacks","network":"mainnet"},"block_identifier":{"index": 120101}}'
```
=> fix: allow more than one Rosetta `stx_unlock` operation per block

content/faqs.md
1. Motivation for change doc-a-thon, cleaning docs
2. What was changed Grammar
=> Fix: FAQs NOT FAQ’s

content/feature-guides/use-clarity-values.md
Fix links in documentation
Fixes https://github.com/hirosystems/docs/issues/485
=> docs: fix links in using cv guide

migrations/1696872367486_nft-custody-tables.js, src/datastore/common.ts, src/datastore/pg-store.ts, src/datastore/pg-write-store.ts, src/tests/search-tests.ts, src/tests/token-tests.ts
This PR transforms the `nft_custody` and `nft_custody_unanchored` materialized views into tables that are written to with each new block/microblock. This migration increases block ingestion performance considerably.
=> fix: move nft custody view into a table

Dockerfile
Switches to bullseye based Docker image so we can pull duckdb from another Docker image to make builds much faster.
=> build: switch to bullseye image, pull duckdb binary

migrations/1700071472495_chain-tip-table.js, src/api/controllers/cache-controller.ts, src/api/routes/status.ts, src/datastore/common.ts, src/datastore/pg-store.ts, src/datastore/pg-write-store.ts, src/event-stream/event-server.ts, src/tests-event-replay/import-export-tests.ts, src/tests-event-replay/poison-microblock-tests.ts, src/tests/cache-control-tests.ts, src/tests/datastore-tests.ts, src/tests/mempool-tests.ts, src/tests/microblock-tests.ts
This PR removes the `chain_tip` materialized view, because it relied on `COUNT(*)` operations that are considerably slow. Instead it updates the chain tip with totals as blocks are ingested.
=> fix: convert `chain_tip` materialized view into a table

docs/entities/mempool-transactions/transaction-status.schema.json, docs/generated.d.ts, src/api/controllers/db-controller.ts, src/datastore/common.ts, src/datastore/helpers.ts, src/datastore/pg-store.ts, src/event-stream/core-node-message.ts, src/tests/mempool-tests.ts
Handle dropped mempool txs with the new `Problematic` status implemented in https://github.com/stacks-network/stacks-core/pull/3212/files#diff-dd79d18b9e96a0ab54185412b55f3153aa45b2c71812ac33e6d1a07c94d4d9b7
=> fix: handle `Problematic` status in `/drop_mempool_tx` event

docs/openapi.yaml
fix a formatting issues on our docs page originating with the `openapi.yaml` file that was using html tags instead of markdown formatting
=> replace html tags with markdown

migrations/1703177555075_mempool-digest-table.js, src/datastore/pg-store.ts, src/datastore/pg-write-store.ts, src/event-replay/event-replay.ts, src/event-replay/parquet-based/replay-controller.ts, src/tests/cache-control-tests.ts, src/tests/mempool-tests.ts
* Delete `mempool_digest` materialized view, keep data in `chain_tip` table
* Change the digest algorithm from a hash to a simple "updated at" timestamp so mempool writes are extremely cheap
* Keep `tx_count` column to avoid running ad-hoc counts over unpruned txs
* Insert mempool txs in batches
=> fix: optimize mempool transaction reads and writes

docs/openapi.yaml, src/api/controllers/db-controller.ts, src/api/routes/v2/blocks.ts, src/api/routes/v2/burn-blocks.ts, src/api/routes/v2/schemas.ts, src/datastore/pg-store-v2.ts, src/datastore/pg-store.ts, src/tests/block-tests.ts
* Create specialized endpoint and migrate it from `/extended/v2/blocks?burn_block_height=` so its easier to validate and maintain and so it follows a more RESTful structure
* Move v2 read queries to v2 PgStore module
* Create "Burn Blocks" documentation tag
* Mark old endpoints as deprecated
=> feat: create `/extended/v2/burn-blocks/:height_or_hash/blocks` endpoint

docs/api/mempool/get-fee-priorities.example.json, docs/api/mempool/get-fee-priorities.schema.json, docs/generated.d.ts, docs/openapi.yaml, src/api/init.ts, src/api/v2/mempool.ts, src/datastore/common.ts, src/datastore/pg-store.ts, src/test-utils/test-builders.ts, src/tests/mempool-tests.ts
Creates an endpoint to return transaction fees based on priority (high = P95, medium = P75, low = P50, no = P25).
Results are included for `all` transactions and also per transaction type (`token_transfer`, `smart_contract` or `contract_call`).
Example response:
```
{
"all": {
"no_priority": 3000,
"low_priority": 3000,
"medium_priority": 6000,
"high_priority": 401199
},
"token_transfer": {
"no_priority": 3000,
"low_priority": 3000,
"medium_priority": 6000,
"high_priority": 401199
},
"smart_contract": {
"no_priority": 837500,
"low_priority": 925000,
"medium_priority": 1012500,
"high_priority": 1082500
},
"contract_call": {
"no_priority": 3000,
"low_priority": 10368,
"medium_priority": 100000,
"high_priority": 1000000
}
}
```
=> feat: add `/extended/v2/mempool/fees` endpoint

src/api/query-helpers.ts, src/api/routes/tokens.ts, src/api/routes/tx.ts, src/tests/tx-tests.ts
Related to https://github.com/hirosystems/stacks-blockchain-api/pull/1807
This adds support for parsing comma-separated array strings from url query params. Now both common formats for specifying arrays should work:
* `?tx_id=ID1,ID2,ID3`
* `?tx_id=ID1&tx_id=ID2&tx_id=ID3`
=> fix: support comma-separated strings in array query params

src/api/controllers/db-controller.ts
Update the `tx_type` maps to support Nakamoto `tenure_change` txs.
=> feat: support tenure_change in tx type filter queries

docs/openapi.yaml
Addresses issue https://github.com/hirosystems/stacks-blockchain-api/issues/1806
Some OpenAPI tooling default to comma-separated strings for arrays in URL query params. In particular, the `docusaurus` generator used in Hiro docs.
This specifies the default behavior used by Express which is multiple parameters with the same name. E.g.
Before:
`?tx_id=1111,2222`
After:
`?tx_id=1111&tx_id=2222`
=> fix(docs): URL query arrays should be formatted with `form` rather than comma-separated

.env, src/datastore/pg-write-store.ts, src/helpers.ts, src/tests/helpers-tests.ts, src/tests/mempool-tests.ts, src/tests/websocket-tests.ts
Currently when the event server handles a new_mempool_tx event, it reconcile mempool status and recalculate mempool stats. This is really unnecessary, especially when an influx of new transactions occurs. As the stacks node awaits the event server processing, it slows down the new block processing.
This PR suggests a method to reconcile and update mempool statistics through a debounce scheme. It significantly decreases the processing time for new_mempool_tx events from over 1s to less than 10ms. 
Performance optimization.
No.
No.
Since the reconcile process is deferred, a method to wait for next reconcile is added for testing purposes. And the tests are updated accordingly.
=> feat: remove reconcile mempool & debounce stats

.env, src/datastore/pg-write-store.ts, src/event-replay/parquet-based/importers/new-block-importer.ts, src/tests/datastore-tests.ts, src/tests/search-tests.ts
This PR improves the new block process improvements by means of running inserts in batch and in parallel.
Previously when the event server process a new block, it roughly process less than 10 transactions per second.
When tested with concurrency=100, it processes more than 30 transactions per second.
Performance improvements.
No.
No.
No changes required.
=> feat: run inserts in batch and in parallel when processing new block

src/datastore/common.ts, src/datastore/helpers.ts, src/datastore/pg-write-store.ts, src/tests/datastore-tests.ts
Log re-org data using the complete re-org entities serialized object, including restored and pruned mempool transaction totals.
=> fix: log re-orgs at `INFO` level

CHANGELOG.md, src/datastore/common.ts, src/datastore/helpers.ts, src/datastore/pg-write-store.ts, src/event-stream/event-server.ts, src/event-stream/reader.ts, src/tests/datastore-tests.ts
In order to determine which type of blocks take longer to process, we must know the proportion of transactions and different transaction types that were included. This will help us investigate further performance optimizations.
=> fix: log block event counts after processing

migrations/1705013096459_update-re-org-indexes.js, src/datastore/pg-write-store.ts, src/tests/datastore-tests.ts, src/tests/other-tests.ts, src/tests/search-tests.ts
Avoid table visits as much as possible
=> fix: optimize re-org queries and indexes

migrations/1705077567281_remove-hash-indexes.js
Our HASH indexes did not have enough cardinality, i.e. there were a lot of collisions which forced postgres to create "secondary" indexes of data inside each of those collisions. Changing indexes to BTREE helped reduce write latency tremendously (from ~5-10 seconds per block to ~150-900ms per block.
=> fix: change all HASH indexes to BTREE to optimize writes

src/datastore/common.ts, src/datastore/pg-store.ts, src/datastore/pg-write-store.ts, src/tests/datastore-tests.ts, src/tests/mempool-tests.ts
Fixes https://github.com/hirosystems/stacks-blockchain-api/issues/1817
=> fix: revive dropped mempool rebroadcasts

docs/api/smart-contracts/get-smart-contracts-status.example.json, docs/api/smart-contracts/get-smart-contracts-status.schema.json, docs/api/smart-contracts/smart-contract-found.schema.json, docs/api/smart-contracts/smart-contract-not-found.schema.json, docs/entities/smart-contracts/smart-contract-status.example.json, docs/entities/smart-contracts/smart-contract-status.schema.json, docs/generated.d.ts, docs/openapi.yaml, src/api/controllers/db-controller.ts, src/api/init.ts, src/api/routes/v2/helpers.ts, src/api/routes/v2/schemas.ts, src/api/routes/v2/smart-contracts.ts, src/datastore/common.ts, src/datastore/pg-store-v2.ts, src/tests/smart-contract-tests.ts
Retrieves the deployment status of multiple smart contracts at once
=> feat: add `/extended/v2/smart-contracts/status` endpoint

docs/openapi.yaml
This fixes some line spacing issues in the documentation.
1. The formatting is not as intended due to the treatment of line-breaks
Example:
In the screenshot above, it is clear that the information about 200 responses is not intended to be in the bullet about `CostEstimationDisabled`.
=> fix: line spacing in `/v2/fees/transaction`

src/datastore/pg-store.ts, src/tests-2.5/env-setup.ts, src/tests-2.5/global-setup.ts, src/tests-2.5/global-teardown.ts
* Move postgres down-migration logic out of teardown
* Remove timeouts in postgres shutdown call
These changes appear to remove the error log messages (which are sometimes fatal deadlocks) that would appear after tests finished.
=> test: fix flaky postgres teardown in tests

src/api/controllers/cache-controller.ts, src/api/routes/status.ts, src/datastore/pg-store.ts, src/datastore/pg-write-store.ts, src/event-stream/event-server.ts, src/tests-event-replay/import-export-tests.ts, src/tests-event-replay/poison-microblock-tests.ts, src/tests/cache-control-tests.ts, src/tests/datastore-tests.ts, src/tests/mempool-tests.ts, src/tests/microblock-tests.ts
Various functions using a sql transaction were querying the chaintip outside of the scoped sql transaction. This may have been the cause of https://github.com/hirosystems/stacks-blockchain-api/issues/1852
=> fix: sql transactional consistency bug with fetching chaintip in various areas

docs/openapi.yaml
Main API overview page [here](https://docs.hiro.so/api) currently references an old url path. This change updates to the new path that renders the proper sidebar in docs.
=> update to new url path

docker/docker-compose.dev.stacks-blockchain.yml, docker/docker-compose.dev.stacks-krypton.yml, migrations/1706886038615_update-pox4-signer-key.js, src/api/controllers/db-controller.ts, src/datastore/common.ts, src/datastore/helpers.ts, src/datastore/pg-store.ts, src/datastore/pg-write-store.ts, src/event-stream/pox-event-parsing.ts, src/tests-2.5/pox-4-burnchain-delegate-stx.ts, src/tests-2.5/pox-4-delegate-aggregation.ts, src/tests-2.5/pox-4-delegate-revoked-stacking.ts, src/tests-2.5/pox-4-delegate-stacking.ts, stacks-blockchain/docker/Dockerfile
Parse `signer-key` arg from pox events (when they are available / in pox4).
Example `GET /extended/v1/pox4/events`
```json
{
"limit": 96,
"offset": 0,
"results": [
{
"block_height": 7,
"tx_id": "0x6acc6a9a560eedc7be41b645677196ef581c02b039a1ae3e80669af04af67fc4",
"tx_index": 1,
"event_index": 1,
"stacker": "ST18MDW2PDTBSCR1ACXYRJP2JX70FWNM6YY2VX4SS",
"locked": "3000225000000000",
"balance": "6999774999999000",
"burnchain_unlock_height": "140",
"pox_addr": "mnvi1WQb3cm2QMeeKe6G9D7L1GsjmmGTda",
"pox_addr_raw": "0x005146f0566e9796602a677d895852e9c0fe5686f7",
"name": "stack-stx",
"data": {
"lock_amount": "3000225000000000",
"lock_period": "2",
"start_burn_height": "110",
"unlock_burn_height": "140",
"signer_key": "0xc6f48a7ea4fa4919b5135ac37eb1d33900cea5ddb63c4fd1fe4dd02d0749566135"
}
}
]
} …
```
=> feat: add signer-keys from pox4 events

src/api/init.ts
Fixes #1826
When a request path is invalid because it doesn't have a route handler, change the prometheus reporting so that the path name is the placeholder `<invalid_path>`. This fixes the issue of very long path names, and fixes the issue of log spam from many unique invalid paths.
=> fix: report placeholder in prom metrics for invalid request paths

docs/openapi.yaml
Caught a few more broken anchors causing some build issues with docs for some of the deprecated endpoints.
=> update broken anchors for deprecated endpoints

src/datastore/pg-store-v2.ts, src/tests/address-tests.ts
Fix for `/extended/v2/addresses/:address/transfers`
=> fix: include address transactions with no stx transfers

migrations/1710856121027_stacks_block_signer-bitvec.js, src/datastore/common.ts, src/datastore/helpers.ts, src/datastore/pg-write-store.ts, src/event-stream/core-node-message.ts, src/event-stream/event-server.ts, src/helpers.ts, src/test-utils/test-builders.ts, src/tests/address-tests.ts, src/tests/block-tests.ts, src/tests/cache-control-tests.ts, src/tests/datastore-tests.ts, src/tests/helpers-tests.ts, src/tests/mempool-tests.ts, src/tests/microblock-tests.ts, src/tests/other-tests.ts, src/tests/search-tests.ts, src/tests/smart-contract-tests.ts, src/tests/tx-tests.ts, src/tests/v2-proxy-tests.ts
Progress towards https://github.com/hirosystems/stacks-blockchain-api/issues/1893
Ingest new `signer_bitvec` property from `/new_block` event. Deserializes the Stacks consensus encoding into a base-2 string, and store in the postgres native bitvec type `bit varying`.
The property is added to the blocks table, but it is not included in the block data returned by various endpoints, because clients probably won't have a direct use for it. 
We are anticipating to use this to generate signer performance data when the `signer_bitvec` data we receive has real data (right now it's still dummy data).
=> feat: ingest signer_bitvec

src/datastore/pg-write-store.ts
=> fix: batch drop mempool transactions

docs/entities/blocks/block.example.json, docs/entities/blocks/nakamoto-block.example.json, docs/entities/blocks/nakamoto-block.schema.json, docs/generated.d.ts, src/api/routes/v2/helpers.ts, src/tests/block-tests.ts
Fixes https://github.com/hirosystems/stacks-blockchain-api/issues/1918
Add block times were to the new NakamotoBlock object returned in many of the new /v2 routes.
=> feat: add nakamoto block time to v2 endpoints

docs/entities/rosetta/rosetta-construction-options.schema.json, docs/generated.d.ts, src/api/routes/debug.ts, src/api/routes/rosetta/construction.ts, src/rosetta/rosetta-helpers.ts, src/test-utils/test-helpers.ts, src/tests-2.5/pox-4-rosetta-btc-addr-types.ts, src/tests-2.5/pox-4-rosetta-cycle-phases.ts, src/tests-2.5/pox-4-rosetta-segwit.ts, src/tests-rosetta-construction/construction.ts, src/tests-rosetta/offline-api-tests.ts
Closes https://github.com/hirosystems/stacks-blockchain-api/issues/1901
Implement Rosetta pox-4 `stack-stx` support.
This PR introduces three modes to use pox4 `stack-stx` in Rosetta:
1) Specify `signer-private-key` and the Rosetta layer will generate the signer signature used by the stack-stx transaction.
2) Specify `signer-signature` (generated external to the Rosetta layer) and it will be used in the stack-stx transaction.
3) Do not specify `signer-private-key` or `signer-signature`, and the stack-stx transaction will specify `none` for this field -- only works if the signer has added the caller to their allow-list.
Additionally:
* The stack-stx `auth-id` field is optional: if not specified, the Rosetta layer will automatically generate a random ID.
* The `reward-cycle-id` field is …
=> feat: rosetta pox4 support

src/event-stream/core-node-message.ts, src/event-stream/reader.ts, src/tests-2.5/pox-4-burnchain-stack-stx.ts
https://github.com/hirosystems/stacks-blockchain-api/issues/1875
Handle pox-4 `stack-stx` burn-ops and repair integration tests for it.
=> fix: pox4 stack-stx burn-op handling

package-lock.json, package.json, src/datastore/pg-write-store.ts
Add logging message when sql migration is performed. Fixes the issue where it looks like the API boot is stalled during a long migration.
Example of the logs:
```json
{"level":"info","msg":"PgNotifier connected, listening on channel: stacks-api-pg-notifier"}
{"level":"info","msg":"Performing SQL migration, this may take a while..."}
{"level":"info","msg":"Event observer listening at: http://127.0.0.1:3700"}
```
=> fix: log message when sql migration is performed

.github/workflows/ci.yml
I added arm docker builds support so I can run a node on my arm server. Right now you will get an error when trying to run the amd image on an arm server. The work was already started on other prs but never merged. I followed the approach mentioned in https://github.com/hirosystems/stacks-blockchain-api/pull/1578 to keep amd build only on prs to not increase the build time and build both arm + amd on the master branch.
Following up the following prs:
- https://github.com/hirosystems/stacks-blockchain-api/pull/1248
- https://github.com/hirosystems/stacks-blockchain-api/pull/1578
=> feat: add docker build for arm

.github/workflows/ci.yml
Part of https://github.com/hirosystems/stacks-blockchain-api/issues/1902
Speeds up CI
=> ci: remove unsupported standalone image build

docker/rosetta.Dockerfile
one-liner: Updates the rosetta dockerfile STACKS_BLOCKCHAIN_VERSION to the latest version `2.5.0.0.2`
=> update stacks-blockchain version to 2.5.0.0.2

src/api/routes/rosetta/account.ts, src/tests-rosetta/account-tests.ts, src/tests-rosetta/api.ts
Fixes https://github.com/hirosystems/stacks-blockchain-api/issues/1955
=> fix: rosetta account endpoint should assume chain tip if block not specified

src/api/controllers/db-controller.ts
Fix possible cause of Rosetta block lookups returning inconsistent results. E.g. reports of block response with 0 transactions:
```
curl --location 'https://xxx/block' \
--header 'Content-Type: application/json' \
--data '{
"network_identifier": {
"blockchain": "stacks",
"network": "mainnet"
},
"block_identifier": {
"index": 147250
}
}'
{
"block": {
"block_identifier": {
"index": 147250,
"hash": "0x2dc8a524911e12f3c4d14de79ca5893b70c7c34d07d0bef59d31b8568650c07f"
},
"parent_block_identifier": {
"index": 147249,
"hash": "0x52ae92098398349b936e1b1c29591150566d38b800101dc0dff805c47aca2f0b"
},
"timestamp": 1713772872000,
"transactions": []
}
}
```
=> fix: inconsistent block transaction results in Rosetta response

.github/workflows/ci.yml
Codecov upload step in CI is running into errors:
```
['error'] There was an error running the uploader: Error uploading to [https://codecov.io:](https://codecov.io/) Error: There was an error fetching the storage URL during POST: 404 - {'detail': ErrorDetail(string='Unable to locate build via Github Actions API. Please upload with the Codecov repository upload token to resolve issue.', code='not_found')}
```
Attempt to fix this by upgrading to latest codecov action and supplying CODECOV_TOKEN
=> ci: attempt to fix codecov upload errors

docker/docker-compose.dev.stacks-blockchain.yml, docker/docker-compose.dev.stacks-krypton.yml, docs/api/rosetta/rosetta-network-status-response.schema.json, docs/entities/rosetta/rosetta-block.schema.json, docs/generated.d.ts, src/api/controllers/db-controller.ts, src/api/routes/rosetta/network.ts, src/tests-rosetta/api.ts, stacks-blockchain/docker/Dockerfile
Closes https://github.com/hirosystems/stacks-blockchain-api/issues/1972
Adds to the `/rosetta/v1/block` response:
```js
{
block: {
metadata: {
burn_block_height: <bitcoin_block_height>
}
}
}
```
And to the `/rosetta/v1/network/status` response:
```js
{
current_burn_block_height: <bitcoin_block_height>
}
```
=> feat: add burn_block_height to Rosetta endpoints

docs/api/stacking/get-pox-cycle-signers.example.json, docs/entities/stacking/signer.example.json, docs/entities/stacking/signer.schema.json, docs/generated.d.ts, src/api/init.ts, src/api/routes/v2/helpers.ts, src/api/routes/v2/pox.ts, src/tests/pox-tests.ts
Adds the p2pkh stacks address of the signer pubkey, which is used for "vote for aggregate key" txs. Helpful for debugging and matching signers to known identities.
cc @hstove
=> feat: add signer_address to pox signer endpoints

client/README.md, client/src/socket-io/index.ts
Closes #1885
Ensure only `websocket` transport is used in the socket-io client. This fixes connectivity when using a load-balanced API endpoint that doesn't use sticky sessions.
=> fix: socket-io client must only use websocket transport

src/api/routes/v2/helpers.ts, src/datastore/common.ts, src/datastore/pg-store-v2.ts, src/datastore/pg-store.ts, src/tests-2.5/pox-4-delegate-aggregation.ts
Closes #1978
A few pox endpoints are missing some new pox4 data. 
For example `signer_key`, `end_cycle_id`, and `start_cycle_id` missing from `/extended/v1/pox4/stacker/<address>`.
And `stacked_amount` missing for pool addresses in the `/extended/v2/pox/cycles/<id>/signers/<key>/stackers` endpoint.
=> fix: a few pox4 properties missing in various endpoints

src/event-stream/event-server.ts, src/tests/synthetic-stx-txs-tests.ts, src/tests/synthetic-tx-payloads/stx_lock-1994-0xd45e090ac442380cf50655e3d1c904c355a501d6dffa3b5e4799083062469dbc.json
Fixes https://github.com/hirosystems/stacks-blockchain-api/issues/1983#issuecomment-2147704935
Synthetic pox events were being stored with their own index number which inflated the reported tx event count. 
This PR changes the event indexing so that pox events use the same index as the contract log event. 
Note: this fixes the data stored for new blocks, but won't fix it for previously ingested blocks. That requires a complicated migration which can be done in a later PR.
=> fix: pox events should use same index as associated contract log event

.github/workflows/ci.yml, docs/openapi.yaml, migrations/1718632097776_tx-sort-indexes.js, src/api/routes/tx.ts, src/datastore/pg-store.ts, src/tests/tx-tests.ts
Closes https://github.com/hirosystems/stacks-blockchain-api/issues/1998
=> feat: tx ordering options

docs/openapi.yaml, src/api/routes/tx.ts, src/datastore/pg-store.ts, src/tests/tx-tests.ts
=> feat: tx to/from address options

docs/openapi.yaml, src/api/routes/tx.ts, src/datastore/pg-store.ts, src/tests/tx-tests.ts
Closes https://github.com/hirosystems/stacks-blockchain-api/issues/1996
Add timestamp (by burn_block_time) filter options to `/extended/v1/tx`
Example usage: `/tx?start_time=1704067200&end_time=1706745599` (one or both can be specified)
=> feat: tx list timestamp filter options

docs/openapi.yaml, migrations/1718887498565_tx-contract-call-indexes.js, src/api/routes/tx.ts, src/datastore/pg-store.ts, src/test-utils/test-builders.ts, src/tests/smart-contract-tests.ts, src/tests/tx-tests.ts
Closes https://github.com/hirosystems/stacks-blockchain-api/issues/1999
Add query params to the tx list endpoint that filter by contract-call `contract_id` and `function_name`.
Example usage: `/tx?contract_id=SP000000000000000000002Q6VF78.pox-4&function_name=delegate-stx`
=> feat: tx list contract id/name filter options

docs/api/tokens/get-ft-holders.example.json, docs/api/tokens/get-ft-holders.schema.json, docs/entities/tokens/ft-holder-entry.schema.json, docs/generated.d.ts, docs/openapi.yaml, migrations/1720532894811_ft_balances.js, src/api/pagination.ts, src/api/routes/tokens.ts, src/datastore/pg-store.ts, src/datastore/pg-write-store.ts, src/tests/datastore-tests.ts, src/tests/token-tests.ts
Closes #1985
Implements indexing code to track (FT, account) balances
This data is exposed in a new endpoint:
Examples
`GET /extended/v1/tokens/ft/stx/holders`
```json
{
"limit": 100,
"offset": 0,
"total": 3,
"total_supply": "11700",
"results": [
{
"address": "SP3Y2ZSH8P7D50B0VBTSX11S7XSG24M1VB9YFQA2K",
"balance": "10000"
},
{
"address": "SP3WJYXJZ4QK2V5V9VX2VXVZ6VXVZ6V2V5V2V2V2V",
"balance": "900"
},
{
"address": "SP3WJYXJZ4QK2V5V9VX2VXVZ6VXVZ6V2V5V2V2V2V",
"balance": "800"
}
]
}
```
=> feat: ft holder indexing

docs/openapi.yaml, src/datastore/pg-store-v2.ts, src/tests/address-tests.ts
Closes https://github.com/hirosystems/explorer/issues/1709
Fixes two bugs with the `/extended/v2/addresses/{addr}/transactions` endpoint:
* Missing results for addresses that only had sent/received ft/nft tokens and were not involved with any stx transfers.
* The associated tx fee was included in the `stx_sent` value even when the address was not the tx sender/sponsor.
=> fix: `/v2/addresses/{addr}/transactions` incorrect when address only involved with token events

package-lock.json, package.json, src/datastore/pg-write-store.ts, src/tests-rosetta-cli-construction/validate-construction.ts, src/tests-rosetta-cli-data/validate-rosetta.ts
=> fix: batch insert length assertion

.github/workflows/ci.yml, docker/docker-compose.dev.bitcoind.yml, docker/docker-compose.dev.postgres.yml, docker/docker-compose.dev.stacks-blockchain.yml, src/event-replay/connection-legacy.ts, src/event-replay/event-replay.ts, src/event-replay/event-requests.ts, src/tests-event-replay/import-export-tests.ts
Releases #2048 as a cherry pick to master
=> feat: export events tsv directly to postgres instance (#2048)

src/api/routes/v2/blocks.ts, src/api/schemas/params.ts, src/api/schemas/responses/responses.ts, src/api/schemas/util.ts, src/datastore/common.ts, src/datastore/pg-store-v2.ts, src/tests/block-tests.ts
Closes https://github.com/hirosystems/stacks-blockchain-api/issues/2043
Supports a new `cursor` query param. The `offset` param continues to work but with a max page limit. Page random-access is possible when using both together.
This approach is generalizable and should work with other listing endpoints like transactions in future PRs.
Example usage:
`GET /extended/v2/blocks?limit=3`
```js
{
limit: 3,
offset: 0,
total: 14,
cursor: '0x0000000000000000000000000000000000000000000000000000000000000014',
next_cursor: null,
prev_cursor: '0x0000000000000000000000000000000000000000000000000000000000000011',
results: [
{ height: 14, ... },
{ height: 13, ... },
{ height: 12, ... }
],
}
```
`GET /extended/v2/blocks?limit=3&cursor=0x0000000000000000000000000000000000000000000000000000000000000011` …
=> feat: cursor-based pagination on blocks endpoint

CHANGELOG.md, README.md
=> chore(docs): improve upgrade readme 

src/datastore/pg-write-store.ts, tests/api/datastore.test.ts, tests/api/mempool.test.ts, tests/api/socket-io.test.ts, tests/api/websocket.test.ts
This PR alters how transactions for the **same sender with the same nonce** are pruned from and restored to the mempool.
* If transaction A with nonce 1 exists in the mempool and a new block comes which confirms transaction B with nonce 1 as well, transaction A is pruned.
* If there is a future re-org that restores transaction B to the mempool, transaction A gets restored as well so they can both compete in the mempool similar to an RBF situation.
Fixes #2041
=> fix: prune and restore mempool transactions with equal nonces for the same sender

migrations/1727465879167_principal-stx-txs-sponsors.js, src/api/controllers/cache-controller.ts, src/api/routes/address.ts, src/api/routes/v2/addresses.ts, src/datastore/pg-store.ts, src/datastore/pg-write-store.ts, src/event-replay/parquet-based/importers/new-block-importer.ts, tests/api/cache-control.test.ts
Creates an ETag for endpoints that serve confirmed data for a single principal (address or contract ID) and adds it to all single-account endpoints.
The ETag is formed with the SHA256 of a string containing the last transaction IDs of those that changed the account's STX, FT or NFT balance:
```ts
sha256(`${activity.stx_tx_id}:${activity.ft_tx_id}:${activity.nft_tx_id}`)
```
---
Other changes:
* Remove code that was moved to the API toolkit
* Consider `sponsor_address` in entries to the `principal_stx_txs` table, including a migration to backfill missing transactions
A future PR will add a similar ETag but also considering that account's mempool activity.
#1230
=> feat: add principal cache etag to account endpoints

src/api/query-helpers.ts, src/tests/address-tests.ts
Closes https://github.com/hirosystems/stacks-blockchain-api/issues/2099
The mutually-exclusive query param check for `unanchored` and `until_block` check had a regression from the Fastify refactor when `unanchored` was changed to default to `false`. This hotfix checks if the value is set to `true` rather than `!== undefined`.
=> fix: query param `until_block` not working in several endpoints

src/api/controllers/cache-controller.ts, src/api/routes/address.ts, src/datastore/pg-store.ts, tests/api/cache-control.test.ts, tests/utils/test-builders.ts
Expands on #2097 to add a new ETag that supports principal activity currently in the mempool. This will enable endpoints for feature requests like #2035 
This ETag is now used in:
```
/extended/v1/address/:principal/mempool
/extended/v1/address/:principal/nonces
```
#1230
=> feat: add cache handler for principal activity including mempool transactions

src/api/controllers/cache-controller.ts, src/api/routes/v2/blocks.ts, src/datastore/pg-store.ts, tests/api/cache-control.test.ts
Adds a cache handler for endpoints that show data for individual blocks:
```ts
`${index_block_hash}:${canonical}`
```
Fixes #1230
=> feat: add block etag

client/package-lock.json, client/package.json, client/src/generated/schema.d.ts, package-lock.json
=> fix: add preexisting declaration copy step in build

src/datastore/pg-store-v2.ts
Fixes https://github.com/hirosystems/stacks-blockchain-api/issues/2114
The final `LEFT JOIN` in this query resulted in a single empty row being returned even for results where no stackers were found (in the `combined_stackers` CTE).
=> fix: /extended/v2/pox/cycles/{n}/signers/{key}/stackers returning 500

.env, .vscode/launch.json, src/datastore/pg-write-store.ts, tests/api/mempool.test.ts, tests/api/socket-io.test.ts, tests/utils/test-builders.ts
Changes the logic for mempool transaction garbage collection depending on which Stacks epoch is active so it adapts to the corresponding implementation on stacks-core:
* If epoch is 2.5 or lower, prune after 256 blocks
* If epoch is 3.0 or higher, prune after 2560 minutes
=> fix: update mempool garbage collection logic for 3.0

src/api/routes/faucets.ts, src/helpers.ts, tests/api/faucet-stx.test.ts
This PR makes a few fixes to the testnet STX faucet:
* Instead of forming an array of `TestnetNetwork`s with the `STACKS_FAUCET_NODE_HOST` and `STACKS_FAUCET_NODE_PORT` values from .env plus the standard testnet network, these ENV vars are now treated only as **override** values. This fixes an issue where both pairs of values essentially pointed to the same network nodes causing faucet transactions to be duplicated in certain scenarios.
* Instead of always attempting to send faucet STX from the first key, keys are now selected in random order. If a key fails from nonce issues, other keys will be tried until we run out of keys. This spreads out the load and reduces the probability of failed transactions.
* Nonce values are now taken from the API nonce estimator, which includes transactions …
=> fix: randomize key order for testnet stx faucet transactions

src/datastore/pg-store.ts, tests/api/cache-control.test.ts
Fixes a bug where a mempool balance did not convert to confirmed balance due to a duplicate Etag calculation. This was because we were taking all the latest `tx_id`s that affected an account (both confirmed and mempool) to calculate the Etag, but when a mempool tx becomes confirmed the Etag did not change because that transaction retains the same transaction ID.
The solution is to prepend a string such as `mempool-` to a mempool transaction ID so the Etag will change once that transaction confirms.
=> fix: differentiate mempool transactions when calculating principal etag

src/api/controllers/db-controller.ts, src/api/rosetta-constants.ts, src/rosetta/rosetta-helpers.ts, tests/rosetta/api.test.ts
Adds support for a `tenure_change` transaction in Rosetta endpoints and reports it as an operation:
```json
{
"operation_identifier": {
"index": 0
},
"type": "tenure_change",
"status": "success",
"metadata": {
"tenure_consensus_hash": "0x2fedd90a5f318ed8cec419fd1c6656b5af452497",
"prev_tenure_consensus_hash": "0x5104aae6d442b49c8e8d2031df7f40b67528e654",
"burn_view_consensus_hash": "0x2fedd90a5f318ed8cec419fd1c6656b5af452497",
"previous_tenure_end": "0xb77b061202b1e6dce889ba1633efa969d3c24679d32a7542d29015ee94e8a860",
"previous_tenure_blocks": 9,
"cause": "block_found",
"pubkey_hash": "0x62b4273562dfa3825496094507564bf2b30c8b11"
}
}
```
Fixes #2127
=> fix: support tenure change transactions in rosetta

src/api/controllers/db-controller.ts, tests/rosetta/api.test.ts
Closes https://github.com/hirosystems/stacks-blockchain-api/issues/2131
In Rosetta block responses, the `timestamp` field uses Nakamoto block times in epoch3 (now that they are consensus-level / reliable). 
In epoch2.x, the burn-block-time is still used.
=> Fix(rosetta): Nakamoto timestamps

migrations/1730724278636_principal_activity_txs_idx.js, src/datastore/pg-store.ts
Possible fix for https://github.com/hirosystems/stacks-blockchain-api/issues/2147
In version v8.1.0, several endpoints (in particular the balance endpoints) were updated to use new [etag caching handling](https://github.com/hirosystems/stacks-blockchain-api/pull/2097). This change was actually an optimization to reduce db load, however, it performs a sql query that is very CPU intensive for postgres deployments without very large memory cache configurations. 
This PR adds composite indexes which _should_ be less CPU intensive than the bitmap scans required by the previously used indexes.
I was able to reproduce the slow query perf on a small-ish vm, and verify that this PR significantly improves the query:
```
// before PR
Planning Time: 4.330 ms
Execution Time: 774.455 ms
// after PR …
```
=> fix: indexes to optimize principal-based etag db lookups

src/datastore/pg-store.ts
Add support for Nakamoto coinbase when handling unlock events. This addresses an error reported by users with the first new reward cycle in Nakamoto. The change adds a check for this new third kind of coinbase in the SQL query.
No
No
Provide context on how tests should be performed.
1. Is testing required for this change?
2. If it’s a bug fix, list steps to reproduce the bug
3. Briefly mention affected code paths
4. List other affected projects if possible
5. Things to watch out for when testing
=> fix(rosetta): add support for Nakamoto coinbase for unlock events

src/event-stream/event-server.ts
Closes https://github.com/hirosystems/stacks-blockchain-api/issues/2158
* Event http response logs now include details like the url, request body size, etc so they don't have to be matched with a previous log entry.
* Aborted http requests are logged as an error with details about the request (this will identify issues like stacks-core using a short timeout).
=> fix: more details in event-observer http server logging

.vscode/launch.json, src/api/schemas/responses/responses.ts, src/openapi-generator.ts
Fixes an issue with the `error: never` types in the client library described in issue https://github.com/hirosystems/stacks-blockchain-api/issues/2138
=> docs: default 4xx error schemas for all routes

package-lock.json, package.json, src/api/routes/core-node-rpc-proxy.ts, tests/api/v2-proxy.test.ts
Adds a hook to the `/v2/fees/transaction` endpoint in the RPC proxy. 
Configure using the env var `STACKS_CORE_FEE_ESTIMATION_MODIFIER`. The fee estimations returned by the stacks-node will be multiplied by this value.
For example with `STACKS_CORE_FEE_ESTIMATION_MODIFIER=0.5`, if the response from stacks-core is:
```
estimations: [
{ fee: 400 },
{ fee: 800 },
{ fee: 1000 }
]
```
Then the modified response will be:
```
estimations: [
{ fee: 200 },
{ fee: 400 },
{ fee: 500 }
]
```
=> feat: option to modify estimated fees in /v2/fees/transaction proxy

client/src/socket-io/index.ts, src/api/routes/ws/channels/socket-io-channel.ts, tests/api/socket-io.test.ts
Closes https://github.com/hirosystems/stacks-blockchain-api/issues/2146
There's a bug in the socket-io client reconnection logic, where an invalid empty topic was being sent. 
```js
client.socket.on('connect_error', error => {
console.error('Socket connection was denied by the server', error);
// > Socket connection was denied by the server Error: Invalid topic: 
});
```
This PR fixes the bug in the client, and also updates the server code to ignore empty topics so that existing client versions will work.
=> Fix: socket-io reconnect

CHANGELOG.md, migrations/1730724278636_principal_activity_txs_idx.js, package-lock.json, package.json, src/api/controllers/db-controller.ts, src/api/rosetta-constants.ts, src/datastore/pg-store.ts, src/rosetta/rosetta-helpers.ts, stacks-blockchain/dist-tool/package-lock.json, stacks-blockchain/dist-tool/package.json, tests/api/cache-control.test.ts, tests/rosetta/api.test.ts
We're unable to cut `beta` branches from `develop` as it seems the past few releases aren't in `develop`.
I'd like to release the new btc faucet amount changes this week if possible, so updating `develop` is needed to do that.
=> Update develop with master

migrations/1734712921681_drop-nft-custody-unanchored.js, src/api/routes/tokens.ts, src/datastore/pg-store.ts, src/datastore/pg-write-store.ts, tests/api/datastore.test.ts, tests/api/token.test.ts
Drops old table and ignores `unanchored` param for `/nft/holdings`.
Fixes #1843
=> chore: remove obsolete nft_custody_unanchored table

src/datastore/pg-store.ts, src/datastore/pg-write-store.ts, src/event-stream/event-server.ts
Observe the following metric:
- `stacks_blocks_in_previous_burn_block`: Number of Stacks blocks produced in previous Bitcoin block
This will help us create alerts for when a Bitcoin block gap happens or blocks stop being produced. We also update the chain tip `burn_block_height` with each new burn block event.
=> feat: add prom metrics for stacks block count at previous burn block

migrations/1737567411419_block-tx-total-size.js, src/datastore/common.ts
Since we just need it for fee estimations, it's ok if this column remains null for past blocks
=> fix: make tx_total_size column nullable

src/api/routes/address.ts, src/api/schemas/entities/balances.ts, src/datastore/pg-store.ts, tests/api/address.test.ts, tests/api/mempool.test.ts, tests/api/tx.test.ts
Adds `pending_balance_inbound` and `pending_balance_outbound` values to `/balances` endpoints, reflecting balance changes from mempool transactions.
#2199
=> feat: show pending inbound and outbound stx balances

src/datastore/pg-write-store.ts
Previously, this debounced mempool stats calculator query was sharing a single sql connection with the pg writer. If the debounced trigger coincided with a new block ingestion, both tasks reused the same SQL transaction resulting in a race condition: as soon as the block ingestion ended, the mempool stats query was cut short because the transaction was committed. This resulted in a `CONNECTION_DESTROYED` postgres error as described here: https://github.com/stacks-network/stacks-core/issues/5663
This PR moves the mempool stats query to its own SQL connection
=> fix: use an independent sql connection for mempool stats

migrations/1740074359683_last-node-events-index.js, src/datastore/pg-store.ts, src/event-stream/event-server.ts
Adds prometheus metrics that show the timestamps of last Stacks node events received, split by event type
```
stacks_last_event_timestamps{event="/new_block"} 1740074547059
stacks_last_event_timestamps{event="/new_burn_block"} 1740074547032
```
=> feat(metrics): add metrics for last event receipt timestamps

src/api/routes/v2/addresses.ts, src/datastore/pg-store-v2.ts, tests/api/address.test.ts
In https://github.com/hirosystems/stacks-blockchain-api/pull/2229 we made the new `:addr/balances/ft` endpoint paginated. In some use cases, the deprecated "get all FT balances" endpoint was being used to lookup a single FT balance, which could now require multiple paginated requests using the new endpoint. 
This PR adds a new endpoint to get the balance of a specific FT for a given address:
```
GET /extended/v2/addresses/:addr/balances/ft/:token
```
Example:
```
GET /extended/v2/addresses/SPQC38PW542EQJ5M11CR25P7BS1CA6QT4TBXGB3M/balances/ft/SM3VDXK3WZZSA84XXFKAFAF15NNZX32CTSG82JFQ4.sbtc-token::sbtc-token
```
```json
{
"balance": "481723"
}
```
=> feat: endpoint to get the balance of a specific ft for a given account

package.json
Make sure `openapi.json` and `openapi.yaml` are in the Vercel output directory after building docs
=> ci(vercel): move openapi files to vercel output directory after build

rosetta-cli-config/docker/Dockerfile
Tests won't pass if we don't update this URL
=> build: update rosetta-cli binary download uri

.env, src/api/routes/tx.ts, tests/api/setup.ts
Users with their own deployments can still enable this by setting `STACKS_API_ENABLE_LEGACY_ENDPOINTS` as true in their ENV.
=> feat: mark /mempool/dropped endpoint as legacy deprecated

src/api/deprecation-plugin.ts, src/api/init.ts, tests/api/address.test.ts
Adds a `Warning: 299 - "Deprecated ..."` http response header for endpoints marked as deprecated. This should help with developer awareness. 
E.g.
```
curl -i 'https://api.hiro.so/extended/v1/address/SP318Q55DEKHRXJK696033DQN5C54D9K2EE6DHRWP/stx'
HTTP/2 200 
date: Mon, 07 Apr 2025 12:19:21 GMT
...
warning: 299 - "Deprecated: See https://docs.hiro.so/stacks/api for more information"
...
```
There are no deprecation-related http headers available and widely in-use today, however, this one is at least [RFC spec-compliant](https://stackoverflow.com/a/29623798/794962)
---
This is implemented as a generic Fastify plugin, and is a good candidate to port over to our api-toolkit repo.
=> feat: add `Warning` http response deprecation notices

migrations/1744989709876_contract-logs-events-index.js
Optimizes the `/extended/v1/contract/${contractId}/events` endpoint by combining two indexes into one, which prevents the query planner from picking a sub-optimal index and then doing a filter. The planner will use this new index instead, optimizing query response times by ~99%.
=> fix: optimize contract event list db index

src/datastore/pg-store-v2.ts, tests/api/tx.test.ts
Optimizes query for `/extended/v2/blocks/${blockHash}/transactions` by first looking for the `index_block_hash` of the relevant block in the `blocks` table and then using that value in other filters, instead of looking for the block in the `txs` table.
Reduces query time by 99%.
=> fix: optimize query for transactions in block

src/datastore/pg-store.ts, tests/bns/api.test.ts
Fixes 500 status error:
```
relation "nft_custody_unanchored" does not exist -> /v1/addresses/stacks/SP2E4MERK02YV3J5MC6SHT1XRVANEJ5DRD80NB3FV?unanchored=true -> 500 -> GET
```
We dropped the `nft_custody_unanchored` table a while ago because we no longer support microblocks.
=> fix: ignore unanchored param for BNS names endpoint

migrations/1745877592337_event-observer-timestamps.js, src/datastore/pg-store.ts, src/datastore/pg-write-store.ts
Optimizes the query which retrieves the latest Stacks node event timestamps for Prometheus metrics (currently taking ~3,000ms to complete) by creating a new table that pre-computes the required values.
=> fix: keep a table of latest stacks node event timestamps

README.md
Updates broken link to point to stacks foundations guides on how to run a node.
=> fix broken link on how to run a node

client/MIGRATION.md
This PR
* updates the link in the migration guide to @stacks/rpc-client
=> docs: update link to @stacks/rpc-client

package-lock.json, package.json
Dependency is no longer used. In place of #2257
=> chore: remove http-proxy-middleware

src/datastore/pg-store.ts
Simply the SQL query for the `/extended/v1/tx/events` endpoint so it doesn't rely on UNIONs with null columns. It will only query against tables based on the given filters.
Fixes #2261
=> fix: simplify transaction events query

migrations/1747151261415_recalculate-balances.js, src/datastore/pg-write-store.ts, tests/api/address.test.ts
The API has Stacks 2.x logic to avoid re-inserting transactions to the DB during a `/new_block` event when those transactions were previously inserted during a `/new_microblock` event. However, the new /extended/v2 balance endpoint logic only considers `/new_block` transactions when adding/subtracting from account balances. This is causing some old 2.x blocks to warp balances in accounts that happened to have transactions confirmed in previous microblocks.
This PR changes this behavior so these balance calculations always include all transactions regardless of microblocks. It also includes a migration that will execute a query to recompute all transaction balances to correct the issue on deployed environments.
Fixes #2267
=> fix: consider microblock transactions in balance calculations

client/src/generated/schema.d.ts, migrations/1747408872545_txs-vm-error.js, src/api/controllers/db-controller.ts, src/api/schemas/entities/transactions.ts, src/datastore/common.ts, src/datastore/helpers.ts, src/datastore/pg-write-store.ts, src/event-stream/core-node-message.ts, tests/api/address.test.ts, tests/api/block.test.ts, tests/api/cache-control.test.ts, tests/api/datastore.test.ts, tests/api/mempool.test.ts, tests/api/microblock.test.ts, tests/api/other.test.ts, tests/api/search.test.ts, tests/api/smart-contract.test.ts, tests/api/tx.test.ts, tests/api/websocket.test.ts, tests/utils/test-builders.ts
=> feat: store and expose vm_error for failed transactions

src/datastore/pg-write-store.ts, tests/2.5/block-zero-handling.test.ts
Our `chain_tip` table starts with `block_height` at zero, so when the API received the block 0 boot data from the Stacks node it is always marked as non-canonical.
This affected FT balance calculations because STX mint events contained within were not being considered, especially in devnet or testnet deployments where devs were configuring `[[ustx_balance]]` settings in their Stacks nodes.
This PR makes it so block 0 STX mint data is always considered for balances.
Related to #2267
=> fix: count stx mint data at block 0 towards account balances

package-lock.json, package.json, src/event-stream/snp-event-stream.ts, tests/snp/jest-global-setup.ts
Ensures only relevant chain events are ingested when using SNP, as opposed to ingesting all events.
Tested and verified against the latest release of SNP as a part of https://github.com/hirosystems/salt-n-pepper/pull/28
=> fix: only ingest snp chain events to avoid db bloat

src/api/routes/v2/block-tenures.ts, src/api/routes/v2/blocks.ts, src/api/routes/v2/schemas.ts, tests/api/block.test.ts
Enforce `cursor` parameter format so it is always a block hash string.
Fixes #2316
=> fix: validate block cursor pagination parameter format

src/datastore/pg-write-store.ts
Optimize the queries that prune and restore transactions from the mempool by processing sponsored and non-sponsored transactions separately to optimize the postgres query plan.
Related to #2271
=> fix: optimize queries to prune and restore mempool rbf txs

src/datastore/pg-write-store.ts
Move RBF mempool queries to the `PgWriteQueue` for parallel processing
=> fix: parallelize mempool rbf updates

migrations/1753205522199_drop-duplicate-indexes.js
Drops redundant indexes from several tables based on PgHero's recommendations:
```
On ft_balances ft_balances_token_index (token)
is covered by ft_balances_token_balance_index (token, balance DESC)
On mempool_txs mempool_txs_sender_address_index (sender_address)
is covered by mempool_txs_sender_address_nonce_index (sender_address, nonce)
On mempool_txs mempool_txs_sponsor_address_index (sponsor_address)
is covered by mempool_txs_sponsor_address_nonce_index (sponsor_address, nonce)
On nft_events nft_events_asset_identifier_index (asset_identifier)
is covered by nft_events_asset_identifier_value_index (asset_identifier, value)
```
=> fix: drop redundant db indexes

src/api/controllers/db-controller.ts, tests/api/tx.test.ts
For details refer to issue [#2323](https://github.com/hirosystems/stacks-blockchain-api/issues/2323)
No.
No.
Provide context on how tests should be performed.
Steps to reproduce the bug are on the issue referenced.
```
docker compose -f docker/docker-compose.dev.postgres.yml up -d
npm run test -- --config ./tests/jest.config.api.js tests/api/tx.test.ts -t "tx list - filter by tx-type" --runInBand
```
=> fix: include nakamoto coinbase txs on coinbase txs filter

src/datastore/pg-store-v2.ts
The `ORDER BY` statement was incomplete as it only sorted by stacked amount. If multiple stackers were stacking the exact same STX, pagination could cause some of them to be missing or appear duplicate in endpoint results.
Fixes #2054
Fixes #2022
=> fix: pox cycle signer stackers query pagination
