hirosystems/stacks-blockchain-api

.eslintrc.js
.github/workflows/commitlint.yml
.github/workflows/linting.yml
migrations/1584604583726_blocks.ts
migrations/1584619633448_txs.ts
package-lock.json
package.json
readme.md
src/api/controllers/db-controller.ts
src/api/init.ts
src/api/models/transaction.ts
src/api/routes/debug.ts
src/binary-reader.ts
src/datastore/common.ts
src/datastore/memory-store.ts
src/datastore/postgres-store.ts
src/event-stream/reader.ts
src/helpers.ts
src/index.ts
src/p2p/messages.ts
src/p2p/tx.ts

Blocked by https://github.com/blockstack/eslint-config/pull/2

fix: prettier formatting, ci

---

package-lock.json
package.json
readme.md
src/api/routes/debug.ts

As a placeholder for a working broadcast RPC API in core, I added this, to help test out TX broadcasting locally via API.
This API exactly mimicks the core API endpoint. I've tested the same payload in core, and although the RPC API doesn't add to the mempool yet (at least it didn't last week), I've validated that the payload is being deserialized correctly in core.

POST /v2/broadcast API

---

gulpfile.js
package.json
scripts/generate-types.ts
src/api/controllers/db-controller.ts
src/api/routes/tx.ts
src/tsconfig-bootstrap.ts
tsconfig.json

See https://github.com/dividab/tsconfig-paths

fix: use tsconfig-paths

---

src/api/routes/debug.ts

Adds a faucet API as `/debug/faucet?address={address}`
Requires an ENV variable `FAUCET_PRIVATE_KEY`

feat: adds STX faucet

---

docs/entities/post-conditions/abstract-post-condition.schema.json
docs/entities/post-conditions/post-condition-fungible.schema.json
docs/entities/post-conditions/post-condition-non-fungible.schema.json
docs/entities/post-conditions/post-condition-stx.schema.json
docs/entities/post-conditions/post-condition.schema.json
scripts/generate-types.ts

Todo:
[See generated post conditions here](https://gist.github.com/kyranjamie/1730753b175db486f51bcc3696b257fd)

feat: add schemas for post conditions

---

package.json

Added build task to dev script to ensure all assets are created first, should address issue highlighted by @hstove and @aulneau

fix: ensure generated files are present on build

---

.dockerignore
.github/workflows/linting.yml
Dockerfile
docker-compose.dev.stacks-blockchain.yml
docker-compose.yml
docs/entities/post-conditions/post-condition-2-non-fungible.schema.json
package-lock.json
package.json
scripts/generate-types.ts
src/api/routes/debug.ts
src/api/serializers/post-conditions.ts
src/core-rpc/client.ts
src/event-stream/reader.ts
src/p2p/tx.ts
src/tests/api-tests.ts

See https://github.com/blockstack/stacks-blockchain/pull/1494

fix: nft asset name is a Clarity value rather than string

---

src/event-stream/core-node-message.ts

Addresses: #41, https://github.com/blockstack/stacks-blockchain/pull/1508

Add burn_block_time to CoreNodeMessage

---

.github/workflows/test.yml
src/datastore/postgres-store.ts

Env var needed by devops for pg setup

feat: env var option to specify postgres migrations schema name

---

src/api/controllers/db-controller.ts
src/datastore/common.ts
src/datastore/memory-store.ts
src/datastore/postgres-store.ts
src/event-stream/core-node-message.ts
src/event-stream/reader.ts
src/migrations/1584604583726_blocks.ts
src/migrations/1584619633448_txs.ts
src/migrations/1588252682585_stx_events.ts
src/migrations/1588256295395_ft_events.ts
src/migrations/1588261750265_nft_events.ts
src/migrations/1588266401242_contract_logs.ts
src/migrations/1588266891631_smart_contracts.ts
src/tests/api-tests.ts
src/tests/datastore-tests.ts

Fix unique constraint violation when receiving blocks after a chain reset

fix: unique tx and block rows based on index_block_hash

---

src/btc-faucet.ts

fix: btc balance check error

---

src/btc-faucet.ts
src/tests/faucet-tests.ts

Improve btc selection outputs, remove unconfirmed txs from balance query

---

.github/actions/publish-docs/action.yml
.github/actions/publish-docs/publish-docs-action.js
.github/workflows/types-publish.yml
docs/package.json
package-lock.json
package.json

Creates new Github action to check, on push of master, if package version has been incremented. If so, deploys package.

feat: add github action to deploy types package

---

.prettierignore
docs/api/blocks/get-blocks.schema.json
docs/entities/blocks/block.schema.json
docs/index.d.ts
docs/openapi.yaml
docs/package-lock.json
docs/package.json
docs/readme.md
src/api/controllers/db-controller.ts
src/datastore/common.ts
src/datastore/memory-store.ts
src/datastore/postgres-store.ts
src/tests/api-tests.ts
src/tests/datastore-tests.ts

Initial incomplete implementation of the block response structure in JSON Schema.

feat: start blocks json schema

---

src/datastore/postgres-store.ts

Closes https://github.com/blockstack/stacks-blockchain-sidecar/issues/121
(minor sql syntax error)

fix: #121 stx faucet broken

---

src/api/init.ts
src/api/routes/address.ts
src/api/routes/search.ts
src/datastore/common.ts
src/datastore/memory-store.ts
src/datastore/postgres-store.ts
src/helpers.ts
src/tests/api-tests.ts

Closes https://github.com/blockstack/stacks-blockchain-sidecar/issues/114
This PR implements a new API endpoint: `GET /sidecar/v1/search/<term>`
The `term` can currently be a block hash, txid, standard account address, or contract address. 
This endpoint is designed for efficiency, for example, used with a search box that performs aggressive auto-complete queries on input change. This should be used as an alternative to the client performing something like `await Promise.any([ fetchBlock(term),  fetchTx(term), fetchAddr(term) ])`.
The following normalization is automatically applied:
* The `term` string whitespace is trimmed.
* Hex strings can be with or without the `0x` prefix, and are case-insensitive.
The response for a found entity is a 200 with:
```ts
{
found: true;
result: { …
```

feat: search endpoint for blocks, txs, and principals

---

docs/openapi.yaml

Closes https://github.com/blockstack/stacks-blockchain-api/issues/174

chore: update server in openapi.yaml for argon testnet

---

docs/api/rosetta/rosetta-network-list-request.schema.json
docs/api/rosetta/rosetta-network-list-response.schema.json
docs/api/rosetta/rosetta-network-options-request.schema.json
docs/api/rosetta/rosetta-network-options-response.schema.json
docs/api/rosetta/rosetta-network-status-request.schema.json
docs/api/rosetta/rosetta-network-status-response.schema.json
docs/entities/rosetta/rosetta-account.schema.json
docs/entities/rosetta/rosetta-amount.schema.json
docs/entities/rosetta/rosetta-block-identifier.schema.json
docs/entities/rosetta/rosetta-coin.schema.json
docs/entities/rosetta/rosetta-currency.schema.json
docs/entities/rosetta/rosetta-error.schema.json
docs/entities/rosetta/rosetta-genesis-block-identifier.schema.json
docs/entities/rosetta/rosetta-network-identifier.schema.json
docs/entities/rosetta/rosetta-network-peers.schema.json
docs/entities/rosetta/rosetta-oldest-block-identifier.schema.json
docs/entities/rosetta/rosetta-operation-statuses.schema.json
docs/entities/rosetta/rosetta-sub-account.schema.json
docs/entities/rosetta/rosetta-sync-status.schema.json
docs/index.d.ts

This PR contains the Rosetta API schema and entity files, and updated `index.d.ts` file.

rosetta schema files and updated types

---

docs/api/transaction/get-mempool-transactions.example.json
docs/openapi.yaml

Adds OpenAPI section for mempool transactions.

feat: add mempool openapi docs

---

client/README.md
client/package-lock.json
client/package.json
client/tsconfig.json
docs/gulpfile.js
docs/openapi.yaml
docs/package-lock.json
package-lock.json
package.json

Adding docs for JS WebSocket client: https://blockstack.github.io/stacks-blockchain-api/#section/Websockets

feat: ws client docs

---

follower.Dockerfile

Fixes https://github.com/blockstack/stacks-blockchain-api/issues/229

fix: #229 standalone docker image starts stacks-node twice

---

client/src/generated/apis/AccountsApi.ts
client/src/generated/apis/SmartContractsApi.ts
client/src/generated/apis/TransactionsApi.ts
docs/index.d.ts
docs/openapi.yaml

fix: pagination and proof params in openapi spec

---

docs/api/rosetta/rosetta-construction-derive-request.schema.json
docs/api/rosetta/rosetta-construction-derive-response.schema.json
docs/entities/rosetta/rosetta-public-key.schema.json
docs/index.d.ts
package.json
src/api/init.ts
src/api/rosetta-constants.ts
src/api/routes/rosetta/construction.ts
src/rosetta-helpers.ts
src/tests-rosetta/api-construction.ts
src/tests-rosetta/api.ts

Rosetta: /construction/derive endpoint

---

src/api/routes/faucets.ts

Address https://github.com/blockstack/stacks-blockchain/issues/1883

Revisit faucet generosity

---

package-lock.json
package.json
stacks-blockchain/dist-tool/index.js
stacks-blockchain/docker/Dockerfile

Closes https://github.com/blockstack/stacks-blockchain-api/issues/223

fix: support new Clarity string types #223

---

src/api/routes/faucets.ts

Give away amount in line with:
```json
{"contract_id":"ST000000000000000000002AMW42H.pox","first_burnchain_block_height":0,"min_amount_ustx":2000001725000,"prepare_cycle_length":30,"rejection_fraction":25,"reward_cycle_id":4,"reward_cycle_length":120}
```

Reduce amount of STX per /faucet

---

src/api/routes/faucets.ts

Allows multiple faucet transactions per block by incrementing the nonce on `ConflictingNonceInMempool` error. Up to 5 faucet transactions are allowed to be stacked in the mempool (this is hardcoded in core). 
This **_does not_** fix the related problem with txs getting permanently stuck or lost, which can also cause the `ConflictingNonceInMempool` error. For reference, see https://github.com/blockstack/stacks-blockchain/issues/1941 and https://github.com/blockstack/stacks-blockchain/issues/1940

ConflictingNonceInMempool fix: increment faucet mempool tx nonces

---

src/api/routes/faucets.ts

Fix a bug that left PR https://github.com/blockstack/stacks-blockchain-api/pull/270 incomplete. The STACKS_FAUCET_NODE vars were not being used in the final submission call.

fix: faucet node override vars missing in tx submission call

---

follower.Dockerfile

fix: #280 -- standalone docker image broken

---

src/tests-rosetta/api.ts

[x]Tests for Rosetta `account/` and `mempool/` endpoints #273

Test cases for rosetta account/ and mempool/ endpoints

---

src/api/routes/faucets.ts

Query `/v2/pox` endpoint for minimum required STX amount for stacking, rather than using hard coded value.
Closes https://github.com/blockstack/stacks-blockchain-api/issues/306

fix: #306 query for min stacking STX amount from /v2/pox endpoint

---

package-lock.json
package.json
src/api/routes/faucets.ts

Closes #319, #330
Increases the faucet STX amount sent for Stacking by 20%. This fixes an issue where the min STX amount would increase by the time the faucet tx completed.

Bump STX faucet to accommodate increasing min Stacking

---

src/datastore/common.ts
src/datastore/memory-store.ts
src/datastore/postgres-store.ts
src/event-stream/event-server.ts
src/tests-rosetta/api.ts
src/tests/api-tests.ts
src/tests/datastore-tests.ts
src/tests/websocket-tests.ts

Ref https://github.com/blockstack/stacks-blockchain-api/issues/333

Wrap mempool tx inserts in sql transactions

---

follower.Dockerfile
stx-rosetta.Dockerfile

fix: update core images used in docker files, fix #349

---

client/package-lock.json
client/package.json

Closes #352 
Updates some packages for client

fix: security issues with packages

---

docs/entities/transactions/abstract-transaction.schema.json
docs/entities/transactions/transaction-0-token-transfer.schema.json
docs/entities/transactions/transaction-1-smart-contract.schema.json
docs/entities/transactions/transaction-2-contract-call.schema.json
docs/index.d.ts
src/api/controllers/db-controller.ts
src/tests/api-tests.ts

Fixes https://github.com/blockstack/stacks-blockchain-api/issues/446
Tested on a local mainnet `http://localhost:3999/extended/v1/tx/0xdef44d1ce688bcbb57541a3d754b85b9fe341343b4c91766fe9effb50e7de27c` shows events as expected.

fix: error fetching coinbase tx containing events

---

package-lock.json
package.json
src/@types/zone-file/index.d.ts
src/bns-helpers.ts
src/event-stream/event-server.ts
src/tests/bns-helpers-tests.ts

Fix several of the `TODO`'s with updating the `zone-file` dependency to version with full typescript support

feat: update zone-file lib to latest with typescript support

---

docs/entities/rosetta/rosetta-construction-options.schema.json
docs/entities/rosetta/rosetta-operation.schema.json
docs/entities/rosetta/rosetta-signing-payload.schema.json
docs/index.d.ts
src/api/controllers/db-controller.ts
src/api/routes/rosetta/construction.ts
src/tests-rosetta/api.ts

Improve rosetta implementation. see https://github.com/blockstack/stacks-blockchain-api/issues/482
No
No

fix: rosetta improvement on construction api

---

docs/api/transaction/get-raw-transaction.example.json
docs/api/transaction/get-raw-transaction.schema.json
docs/index.d.ts
docs/openapi.yaml
src/api/routes/tx.ts
src/datastore/common.ts
src/datastore/memory-store.ts
src/datastore/postgres-store.ts
src/tests/api-tests.ts
src/tests/datastore-tests.ts

Get Raw transaction from `tx_id`.
New endpoint `/:tx_id/raw` added. 
For details refer to issue #428 
No
Yes, this endpoint should be documented somewhere. 
npm run test

Get Raw Transaction Endpoint Implementation

---

docs/api/address/get-address-nft-events.example.json
docs/api/address/get-address-nft-events.schema.json
docs/entities/nft-events/nft-event.example.json
docs/entities/nft-events/nft-event.schema.json
docs/index.d.ts
docs/openapi.yaml
src/api/routes/address.ts
src/datastore/common.ts
src/datastore/memory-store.ts
src/datastore/postgres-store.ts
src/migrations/1588261750265_nft_events.ts
src/tests/api-tests.ts

This PR list all nfts owned by an address
For details refer to issue https://github.com/blockstack/stacks-blockchain-api/issues/227
No
npm run test:integration
@zone117x

List of nfts  by address

---

src/datastore/postgres-store.ts
src/tests/api-tests.ts

Add total in account asset API query. 
Closes #459

Add total in Account Assets API

---

src/datastore/postgres-store.ts
src/tests/api-tests.ts

Closes https://github.com/blockstack/stacks-blockchain-api/issues/509

fix: support fetching raw tx data for mempool transactions

---

src/datastore/postgres-store.ts
src/tests/api-tests.ts

Fixes https://github.com/blockstack/stacks-blockchain-api/issues/468
STX burns were not taken into account in the total unlocked STX sql query. Thank you to @kantai for identifying the problem!

fix: liquid STX discrepancy between sql db and /v2/pox #468

---

docs/entities/rosetta/rosetta-construction-options.schema.json
docs/entities/rosetta/rosetta-operation.schema.json
docs/index.d.ts
src/api/controllers/db-controller.ts
src/api/rosetta-constants.ts
src/api/rosetta-validate.ts
src/api/routes/rosetta/account.ts
src/api/routes/rosetta/block.ts
src/api/routes/rosetta/construction.ts
src/api/routes/rosetta/network.ts
src/datastore/common.ts
src/datastore/memory-store.ts
src/datastore/postgres-store.ts
src/rosetta-helpers.ts
src/tests-rosetta/api.ts

* Rosetta ocnstruction api now support building stacking operation
* Fix the missing events that change the balance for Data api in rosetta side
* Get Network based on chainID (by default it used to be testnet)
See old PR https://github.com/blockstack/stacks-blockchain-api/pull/543
No

chore: stacking feature; event processing;

---

.env
src/api/routes/core-node-rpc-proxy.ts

feat: make the v2 proxy cache control file configurable via env var #519

---

src/api/routes/bns/names.ts
src/event-stream/event-server.ts
src/tests-bns/bns-integration-tests.ts

This PR fixes the issue described here #582 , It handles the zone files which are incorrect with missing Uri or subdomain properties.
Fixes #582

Fix zone file parsing 

---

package.json

* `ts-node` not picking up types correctly.
* Set `STACKS_CHAIN_ID` to mocknet/testnet in dev command.

chore: fix `npm run dev` issues

---

docs/openapi.yaml

feat: adding regtest network

---

overview.md

chore: add initial overview.md

---

CHANGELOG.md
running_an_api.md
running_api_from_source.md
src/api/init.ts

A hotfix for the API. 
For details refer to issue #636 
NO
NO

Harden api fix

---

.env
package.json
src/datastore/postgres-store.ts
src/helpers.ts
src/tests/datastore-tests.ts

This PR supersedes #655 and fixes the related merge issues by manually adding the changes against the `develop` branch.
See #655 for a full description of the change.

Feat: new database connection options

---

src/api/init.ts

Cherrypick from PR accidentally merged into develop rather than master: https://github.com/blockstack/stacks-blockchain-api/pull/638

fix: harden api hotfix

---

src/api/routes/rosetta/construction.ts
src/rosetta-helpers.ts
src/tests-rosetta/api.ts
src/tests-rosetta/offline-api-tests.ts

Integration tests for delegate-stacking for rosetta transaction constructions. 
closes #692 
`npm run test:integration:rosetta`

[Rosetta] Integration test for delegate-stacking

---

docs/openapi.yaml

Update BNS endpoint OpenAPI documentation to make titles shorter while keeping detailed descriptions below.
Closes #644 
No
They will be auto generated based on new information from this PR
N/A

short summaries for BNS endpoints

---

src/datastore/postgres-store.ts

This patch greatly optimizes the database query that retrieves transactions with asset transfers for an address or principal.
The main problem with the original query was that there were too many `LEFT JOIN` statements between event tables and the `txs` table which has hundreds of thousands of records. These operations were very expensive and created delays of a few seconds.
What was done was to first get the actual `tx_id`s that we're interested in from the event tables (using common table expressions for better performance), and then do an `INNER JOIN` between those results and the `txs` table.
These improvements reduced the latency of the original query from ~3,000 ms to ~50 ms in local tests.
No
No
Tested using existing unit tests

optimize query that retrieves txs with asset transfers

---

src/datastore/postgres-store.ts

This patch optimizes two other queries that retrieve transactions with asset transfers by using `INNER JOIN` instead of `LEFT JOIN` for the `txs` table, similar to #749 
No
No
Covered by existing unit tests

replicate query optimizations to other asset txs queries

---

package-lock.json
package.json
src/api/routes/faucets.ts
src/api/routes/rosetta/construction.ts
src/api/routes/ws-rpc.ts
src/core-rpc/client.ts
src/datastore/postgres-store.ts
src/rosetta-helpers.ts
src/tests-bns/bns-integration-tests.ts
src/tests/datastore-tests.ts

Update TypeScript to version 4.4.2 and specify `try/catch` block errors with `any` type.
Also, clean up some extra whitespace in `postgres-store.ts`.
No
No
N/A

chore: update typescript to 4.4.2

---

src/datastore/postgres-store.ts
src/tests-bns/bns-integration-tests.ts
src/tests/datastore-tests.ts

This PR just copy a test scanerio from  #620. These tests cover the reorg scenario for BNS  tables. 
closes #654

Copy a reorg test scenario for BNS. 

---

.github/PULL_REQUEST_TEMPLATE.md

chore: change @kyranjamie to @rafaelcr on pr template

---

Dockerfile
follower.Dockerfile

This patch fixes the Build-publish Github action which started to fail during the `python` installation.
No
No
N/A

fix: build/publish Dockerfile python installation issues

---

Dockerfile
follower.Dockerfile
src/api/routes/core-node-rpc-proxy.ts
src/tests/v2-proxy-tests.ts

Cherry picked from https://github.com/hirosystems/stacks-blockchain-api/commit/7a1138452ad60c3b4c49f8b97ba557e3609dc40f and https://github.com/hirosystems/stacks-blockchain-api/commit/e1c688297578b266983fc1daa30f41f44b082049

fix: transaction broadcast logs and Docker publish

---

src/api/routes/ws/ws-rpc.ts

This patch adds a heartbeat to the Websockets server by sending a `ping` control message to every subscribed client on each of our supported topics every 5 seconds.
There was no need to change anything in our client library. From the [`ws` library docs](https://www.npmjs.com/package/ws):
> Pong messages are automatically sent in response to ping messages as required by the spec.
Closes #820 
No
No
Local tests.

feat: add heartbeat to websockets

---

docs/api/search/search-address.schema.json
docs/api/search/search-block.schema.json
docs/api/search/search-contract.schema.json
docs/api/search/search-mempool.schema.json
docs/api/search/search-tx-id.schema.json
docs/generated.d.ts
docs/openapi.yaml
src/api/controllers/db-controller.ts
src/api/query-helpers.ts
src/api/routes/search.ts
src/datastore/common.ts
src/datastore/memory-store.ts
src/datastore/postgres-store.ts
src/tests/api-tests.ts

The purpose of this PR is to exclude multiple API calls for search from stacks explorer.
For details refer to issue #651

Include Metadata

---

client/src/socket-io/index.ts

it is unnecessary to log all events when init. it should be leave to the consumer to decided if it is needed. 
Provide context on how tests should be performed.
1. Is testing required for this change? NO
2. If it’s a bug fix, list steps to reproduce the bug
3. Briefly mention affected code paths
4. List other affected projects if possible
5. Things to watch out for when testing

fix: remove unnecessary logEvent when init

---

src/datastore/postgres-store.ts
src/tests/api-tests.ts

fix: fetch abi info on `/extended/v1/address/:addr/:tx_id/with_transfers`

---

.github/workflows/stacks-blockchain-api.yml
docs/.validaterc
docs/openapi.yaml

contributing to the following issues:
- https://github.com/hirosystems/stacks-blockchain-api/issues/744
- https://github.com/hirosystems/stacks-blockchain-api/issues/762
- https://github.com/hirosystems/stacks-blockchain-api/issues/745
- https://github.com/hirosystems/docs/issues/27
cc @saralab

feat: openapi lint config and grouping

---

src/index.ts

Also check for this file before anything else.
Fixes #902

fix: make missing git-info error message friendlier

---

.github/workflows/stacks-blockchain-api.yml

Update semantic-release version to 2.7.0

ci: update semantic-release plugin version

---

src/tests/socket-io-tests.ts

Fixes https://github.com/hirosystems/stacks-blockchain-api/issues/932

chore: fix tests stalling in CI

---

src/migrations/1584619633448_txs.ts
src/migrations/1588252682585_stx_events.ts
src/migrations/1588256295395_ft_events.ts
src/migrations/1588261750265_nft_events.ts
src/migrations/1588266401242_contract_logs.ts
src/migrations/1591291822107_mempool_txs.ts
src/migrations/1605100253938_stx_lock_events.ts
src/migrations/1608030374841_bns-tables.ts
src/migrations/1610030345948_bns-subdomain.ts

fix: remove redundant postgres indexes

---

src/datastore/postgres-store.ts
src/migrations/1584604583726_blocks.ts
src/migrations/1584619633448_txs.ts
src/migrations/1591291822107_mempool_txs.ts
src/migrations/1620937804009_microblocks.ts

* Makes sure sorting indexes are correct, specially on `block_height`
* Removes all unused boolean indexes
* Adds indexes that should be there (block index, parent index, burn index, etc.)

fix: optimize indexes for `blocks`, `microblocks`, `txs`, `mempool_txs`

---

src/event-stream/event-server.ts
src/index.ts

This PR adds an additional error log specifying failing event-replay to help automatically detect such failure.  
For details refer to issue #944

Print additional log for failing event-replay

---

src/api/controllers/db-controller.ts
src/api/routes/rosetta/account.ts
src/index.ts
src/rosetta-helpers.ts
src/test-utils/test-builders.ts
src/tests-rosetta/account-tests.ts
src/tests-rosetta/api.ts
src/tests-rosetta/block-tests.ts

* Include the full `contract_call` metadata for every applicable transaction
* Include every `ft_event` as an `operation` (mint, burn, transfer) while using the correct Fungible Token metadata for symbols and decimals
* Include FT balances in `/account/balance`
* Gate FT support depending on metadata availability
* Warn on FT/NFT metadata missing at API startup
Transaction example
```json
{
"transaction_identifier": {
"hash": "0x5d5980a81bc45b2b6843ea9c194c85dd17754859878ec55f6489c2a3b324c748"
},
"operations": [
{
"operation_identifier": {
"index": 0
},
"type": "fee",
"status": "success",
"account": {
"address": "SP335ZC3W6M308ZKTSCCBMR54GWA20RSXCKJPZC59"
},
"amount": {
"value": "-1000000",
"currency": {
"decimals": 6,
"symbol": "STX"
}
}
},
{
"operation_identifier": {
"index": 1
}, …
```

fix: rosetta add FT support (balance, operations) and return `contract_call` metadata

---

src/api/routes/rosetta/account.ts
src/api/routes/rosetta/block.ts
src/api/routes/rosetta/construction.ts
src/api/routes/rosetta/mempool.ts
src/api/routes/rosetta/network.ts
src/tests-rosetta/api.ts
src/tests-rosetta/offline-api-tests.ts

This PR responds with status code 400 on bad requests for Rosetta.
For details refer to issue #1009

Return 400 for Rosetta bad requests

---

docs/openapi.yaml

Fixed the link for postman collection 
- [X ] API reference/documentation update
No
No
- [ X] Tag 1 of @rafaelcr or @zone117x for review

fix:postman-collection-link

---

docs/api/info/get-status.example.json
docs/api/info/get-status.schema.json
docs/entities/info/chain-tip.example.json
docs/entities/info/chain-tip.schema.json
docs/generated.d.ts
docs/openapi.yaml
src/api/routes/status.ts

feat: add chain tip info to `/extended/v1/status`

---

.env
Dockerfile
docker/stx-rosetta.Dockerfile
running_an_api.md
src/api/init.ts
src/helpers.ts

This PR creates an endpoint to render documentation for stacks-blockchain-api at `/doc`.
For details refer to issue #896

Mount documentation at /doc

---

docs/openapi.yaml

Updated docs to include websockets info for mempool tx

chore: updated docs to include websockets info for mempool tx

---

docs/openapi.yaml

chore: update docs to include websockets info

chore: update docs to include websockets info

---

running_api_from_source.md

update the script to download bns data to absolute path if user is in different path than `/`

fix bns download script

---

docs/socket-io/index.d.ts
src/api/query-helpers.ts
src/api/routes/ws/socket-io.ts
src/tests/socket-io-tests.ts

This PR adds a validation check to subscribe to a topic. It validates the incoming `string` to the type of `Topic` and emits an error if invalid.
For details refer to issue #958 
Required tests have been added too in this PR. However, validation checks run when connecting as well as subscribing to a topic.

Validate socket.io topics

---

.vscode/launch.json
src/api/routes/bns/names.ts
src/datastore/common.ts

Previous PR did not correctly change the method signature in `common.ts` causing this bug.

fix: propagate chain id correctly to bns router

---

docs/entities/blocks/block.example.json
docs/entities/blocks/block.schema.json
docs/generated.d.ts
src/api/controllers/db-controller.ts
src/datastore/common.ts
src/datastore/pg-store.ts
src/tests/api-tests.ts
src/tests/cache-control-tests.ts

This PR adds `transaction_count` in `microblocks_accepted` in `block`.
For details refer to issue #1048

Add `transaction_count` for `microblocks_accepted` in block

---

docs/openapi.yaml

Includes changes for Accounts and Blocks API's.
- Added examples.
- Added/updated description.

OpenAPI.yaml - API examples and description

---

running_an_api.md
running_api_from_source.md

Small change to some markdown docs to use Postgres 14

updating postgres version in docs to 14

---

docs/openapi.yaml

Describe the changes that where made in this pull request. When possible start with a user story - short, simple descriptions of a feature told from the perspective of the person who desires the new capability. Be sure to also include the following information:
1. Motivation for change
2. What was changed
3. How does this impact application developers
4. Link to relevant issues and documentation
5. Provide examples of use cases with code samples and applicable acceptance criteria
Example:
As a Hiro Systems developer, I would like to encrypt files using the app private key. This is needed because storing unencrypted files is unacceptable. This pull request adds the `encryptContent` function which will take a string and encrypt it using …

Added examples for Microblocks and names API's

---

docs/openapi.yaml

Added examples, and updated description for more clarity to the following API's in the Stacks Blockchain API. 
- faucets
- fees
- fungible tokens
- Info

Added examples to Faucets, fees, fungible tokens and Info API's

---

docs/openapi.yaml

Added examples for path and query parameters for transaction API's.

Added examples for transaction APIs

---

docs/openapi.yaml

Added "Reward slot holder recipient address"

Added examples for stacking rewards APIs

---

docs/openapi.yaml

Added examples for smart contract API's.

Added examples for smart contract API's

---

docs/openapi.yaml

Added examples for Micro blocks, accounts, transactions and non-fungible tokens.

Added examples for missing API's

---

docs/openapi.yaml

- Cleaned up OpenAPI.yaml to have consistency for all the examples. 
- Fixed issues with examples of type string.

Cleaned up OpenAPI.yaml for consistency with all the examples

---

src/datastore/pg-write-store.ts

Integrate https://github.com/hirosystems/stacks-blockchain-api/pull/1270 into new postgres library code

fix: refresh materialized views concurrently in new pg format

---

src/datastore/connection-legacy.ts
src/datastore/connection.ts
src/datastore/helpers.ts

fix: retry pg connection on new library code

---

src/migrations/1610030345948_subdomains.ts
src/migrations/1663701407339_subdomains_owner_index.ts

Integrate changes from v5.0.1 patch https://github.com/hirosystems/stacks-blockchain-api/pull/1323

feat: add owner index to subdomains table

---

src/rosetta-helpers.ts
src/tests-rosetta/block-tests.ts

feat: add token_type metadata for rosetta ft operations

---

src/datastore/pg-store.ts
src/tests/datastore-tests.ts

this fix makes sure we don't query postgres with empty arrays in certain endpoints, which was causing 500 errors in some of our API pods. It also removes an unused `getSmartContractList` function.

fix: guard against empty lists before querying postgres

---

src/api/routes/ws/web-socket-transmitter.ts
src/tests/ws-transmitter-tests.ts

fix: handle pg exceptions on web socket transmitter

---

docker/docker-compose.dev.stacks-krypton-2.1-transition.yml
docker/docker-compose.dev.stacks-krypton.yml
src/ec-helpers.ts
src/helpers.ts
src/pox-helpers.ts
src/tests-2.1/pox-2.ts
src/tests/helpers-tests.ts

Integration tests against stacks-blockchain branch https://github.com/stacks-network/stacks-blockchain/pull/3283 (segwit support) for PoX-2 operations

PoX-2 integration testing for segwit addresses

---

src/event-stream/reader.ts

Closes https://github.com/hirosystems/stacks-blockchain-api/issues/1378

fix: log PoisonMicroblock tx instead rather than throwing

---

src/event-stream/reader.ts

this PR is against repo tag `v5.0.1`

fix: log poison microblock tx v5

---

src/event-stream/reader.ts

fix: log poison microblock tx v4

---

docs/openapi.yaml

OpenAPI.yaml:
Corrected typos for the word transactions.

Corrected typo for the word "transactions"

---

src/datastore/helpers.ts

fix: handle postgres.js connection timeouts

---

src/api/init.ts

fix: disable faucet endpoints on mainnet

---

src/datastore/helpers.ts

fix: handle postgres dns lookup error

---

src/api/routes/bns/names.ts
src/tests-bns/api.ts
src/tests-bns/bns-integration-tests.ts

fix: revert to 404 error code on bns name errors

---

.github/workflows/ci.yml
src/api/routes/faucets.ts
src/tests-2.1/env-setup.ts
src/tests-2.1/faucet-stx.ts

Closes https://github.com/hirosystems/stacks-blockchain-api/issues/1455

Fix STX faucet fee bug

---

.github/workflows/ci.yml
src/tests-2.1/pox-2-rosetta-btc-addr-types.ts
src/tests-2.1/pox-2-rosetta-cycle-phases.ts
src/tests-2.1/pox-2-rosetta-segwit.ts
tests/jest.config.2.1.js

Speed up long PoX-2 rosetta tests, attempt to fix flaky failures

chore: split up pox-2-rosetta tests

---

docker/docker-compose.dev.stacks-krypton-2.1-transition.yml
docker/docker-compose.dev.stacks-krypton.yml
src/test-utils/test-helpers.ts
src/tests-2.1-transition/pox-transition.ts
src/tests-2.1/pox-2-rosetta-btc-addr-types.ts

fix: update flaky tests (no publish)

---

src/api/controllers/db-controller.ts
src/tests/microblock-tests.ts

fix: is_unanchored property on /extended/v1/tx/:tx_id

---

docker/stx-rosetta.Dockerfile

Redo of PR #1421 (Issue #1362 )
Creating a new PR due rebase-related issues in the older one.
Use new repos: hirosystems/stacks-blockchain-api and stacks-network/stacks-blockchain
Read Toml from stacks-network / stacks-blockchain/testnet/stacks-node/conf/
These updates will now let the docker image build and run, but the settings in the Toml need to be validated.

Update stx-rosetta dockerfile

---

content/faqs.md
docs/openapi.yaml

Use the following template to create your pull request.
Added clarity for STX vs. bitcoin block heights.
1. Motivation for change - Confusing for devs
2. What was changed - OpenAPI Spec and FAQ article in docs.
3. How does this impact application developers - add clear understanding
4. Link to relevant issues and documentation NA
5. Provide examples of use cases with code samples and applicable acceptance criteria NA

Added clarity for bitcoin/stx blockheights

---

docker/docker-compose.dev.subnets.yml
docker/subnet-node.Dockerfile
src/event-stream/core-node-message.ts
src/event-stream/reader.ts
src/helpers.ts
src/tests-subnets/subnet-tests.ts

Support parsing the new `register-asset` burnchain-ops from https://github.com/hirosystems/stacks-subnets/pull/237
Example tx response for a `register-asset-contract ` burnchain-op tx:
```json
{
"tx_id": "0xe3ef36f2147cdce97257af219a95a8a369c48e37702eeeca8efd1a18a3ff0eac",
"nonce": 0,
"fee_rate": "0",
"sender_address": "ST000000000000000000002AMW42H",
"sponsored": false,
"post_condition_mode": "allow",
"post_conditions": [],
"anchor_mode": "any",
"is_unanchored": false,
"block_hash": "0x131e5435eb8456f067f1fb17f6cc33beb4be4c1e996a822973f4f6cee6953464",
"parent_block_hash": "0xb485410170e55d2fbdf13f54fb0f5064da071a67062da1135748d3a19f74cfc7",
"block_height": 6,
"burn_block_time": 0,
"burn_block_time_iso": "",
"parent_burn_block_time": 0,
"parent_burn_block_time_iso": "",
"canonical": true, …
```

feat: support register asset event synthetic tx parsing

---

client/README.md
client/src/generated/runtime.ts
client/test/test.ts
content/faqs.md
content/feature-guides/microblocks.md
content/feature-guides/nonce-handling.md
content/feature-guides/openapi-spec.md
content/feature-guides/rate-limiting.md
content/feature-guides/transactions.md
content/feature-guides/use-clarity-values.md
content/feature-guides/use-stacks-blockchain-api.md
content/how-to-guides/how-to-install-stacks-cli.md
content/how-to-guides/how-to-query-stacks2.0-blockchain.md
content/how-to-guides/how-to-run-api-node.md
content/how-to-guides/how-to-run-mainnet-node.md
content/how-to-guides/how-to-run-stacks-blockchain-api-docker.md
docs/openapi.yaml
running_an_api.md
running_api_from_source.md
stacks-blockchain/Stacks-follower.toml
stacks-blockchain/Stacks-mainnet.toml
stacks-blockchain/Stacks-testnet.toml

Closes https://github.com/hirosystems/stacks-blockchain-api/issues/1595

Fix: domain migration

---

client/README.md
client/src/generated/runtime.ts
client/test/test.ts
content/faqs.md
content/feature-guides/microblocks.md
content/feature-guides/nonce-handling.md
content/feature-guides/openapi-spec.md
content/feature-guides/rate-limiting.md
content/feature-guides/transactions.md
content/feature-guides/use-clarity-values.md
content/feature-guides/use-stacks-blockchain-api.md
content/how-to-guides/how-to-install-stacks-cli.md
content/how-to-guides/how-to-query-stacks2.0-blockchain.md
content/how-to-guides/how-to-run-api-node.md
content/how-to-guides/how-to-run-mainnet-node.md
content/how-to-guides/how-to-run-stacks-blockchain-api-docker.md
docs/openapi.yaml
running_an_api.md
running_api_from_source.md
stacks-blockchain/Stacks-follower.toml
stacks-blockchain/Stacks-mainnet.toml
stacks-blockchain/Stacks-testnet.toml

cherry-pick 2769e684688f6d6c049baabc1d7777a330bc3f40

fix: domain migration (#1596)

---

client/package-lock.json
client/package.json
package-lock.json
package.json

This PR fixes #1593 
An update of the `rimraf` external library was checked and validated.

ci: npm publish on CI

---

src/api/routes/address.ts
src/api/routes/block.ts
src/api/routes/burnchain.ts
src/api/routes/contract.ts
src/api/routes/microblock.ts
src/api/routes/pox2.ts
src/api/routes/stacking.ts
src/api/routes/tokens/tokens.ts
src/api/routes/tx.ts
src/api/routes/ws/channels/socket-io-channel.ts
src/event-stream/event-server.ts
src/helpers.ts

Fixes for issue https://github.com/hirosystems/stacks-blockchain-api/issues/1566.
Added:
1 - metadata component to logs.
2 - `getPagingQueryLimit` error handling.

fix: log cleanup

---

readme.md
running_an_api.md
running_api_from_source.md

Fix: typos

---

.github/workflows/ci.yml
docker/docker-compose.dev.stacks-krypton-2.1-transition.yml
docker/docker-compose.dev.stacks-krypton.yml
docs/api/info/get-status.schema.json
docs/generated.d.ts
migrations/1682694573447_pox_2_unlock.js
src/api/routes/status.ts
src/datastore/common.ts
src/datastore/pg-store.ts
src/datastore/pg-write-store.ts
src/event-stream/core-node-message.ts
src/event-stream/event-server.ts
stacks-blockchain/docker/Dockerfile

fix: support Stacks 2.2 force pox-2 unlocks

---

.github/workflows/ci.yml
src/tests-2.4/pox-3-delegate-aggregation.ts
src/tests-2.4/pox-3-delegate-revoked-stacking.ts

adds a test for the commented revoke tests we used to have for pox-2

test: add pox-3 revoke test

---

.github/CONTRIBUTING.md
.github/ISSUE_TEMPLATE/config.yml
README.md

Describe the changes that where made in this pull request. When possible start with a user story - short, simple descriptions of a feature told from the perspective of the person who desires the new capability. Be sure to also include the following information:
1. Motivation for change
2. What was changed
3. How does this impact application developers
4. Link to relevant issues and documentation
5. Provide examples of use cases with code samples and applicable acceptance criteria
Example:
As a Hiro Systems developer, I would like to encrypt files using the app private key. This is needed because storing unencrypted files is unacceptable. This pull request adds the `encryptContent` function which will take a string and encrypt it using …

chore: improve README.md standardization

---

content/feature-guides/rate-limiting.md

Expanded RPM - Rate per minute. 
Fixes https://github.com/hirosystems/stacks-blockchain-api/issues/1665

Expanded RPM as Rate per minute

---

src/event-stream/event-server.ts

Add explicit stopwatch logging for full block ingestion time, and prometheus histogram metrics for all event ingestion functions.

chore: log block ingestion time

---

docs/api/blocks/get-burn-blocks.example.json
docs/api/blocks/get-burn-blocks.schema.json
docs/entities/blocks/burn-block.example.json
docs/entities/blocks/burn-block.schema.json
docs/generated.d.ts
docs/openapi.yaml
src/api/controllers/db-controller.ts
src/api/init.ts
src/api/pagination.ts
src/api/query-helpers.ts
src/api/routes/burn-block.ts
src/datastore/common.ts
src/datastore/pg-store.ts
src/tests/block-tests.ts

Closes https://github.com/hirosystems/stacks-blockchain-api/issues/1758
Implement new endpoint returning the list of latest burn blocks:
```ts
interface Response {
limit: number;
offset: number;
total: number;
results: Array<{
burn_block_time: number;
burn_block_time_iso: string;
burn_block_hash: string;
burn_block_height: number;
stacks_blocks: Array<string>;
}>;
}
```
Supports the filters:
* `?height=<burn block height`
* `?hash=<burn block hash>`
* `?hash=latest` -- returns the latest burn block
* `?limit=n&offset=b`
Example:
```shell
curl -s http://localhost:3999/extended/v1/burn_block | jq
```
```json
{
"limit": 20,
"offset": 0,
"total": 9,
"results": [
{
"burn_block_time": 1683536586,
"burn_block_time_iso": "2023-05-08T09:03:06.000Z",
"burn_block_hash": …
```

feat: `GET /extended/v1/burn_block`

---

migrations/1700071472495_chain-tip-table.js
src/api/controllers/cache-controller.ts
src/api/routes/status.ts
src/datastore/common.ts
src/datastore/pg-store.ts
src/datastore/pg-write-store.ts
src/event-stream/event-server.ts
src/tests-event-replay/import-export-tests.ts
src/tests-event-replay/poison-microblock-tests.ts
src/tests/cache-control-tests.ts
src/tests/datastore-tests.ts
src/tests/mempool-tests.ts
src/tests/microblock-tests.ts

fix: convert `chain_tip` materialized view into a table

---

migrations/1703177555075_mempool-digest-table.js
src/datastore/pg-store.ts
src/datastore/pg-write-store.ts
src/event-replay/event-replay.ts
src/tests/cache-control-tests.ts
src/tests/mempool-tests.ts

fix: optimize mempool transaction reads and writes

---

src/datastore/pg-write-store.ts

cherry-pick from https://github.com/hirosystems/stacks-blockchain-api/pull/1920

fix: batch drop mempool transactions (#1920)

---

src/api/routes/rosetta/construction.ts

minor updates
- add check for `authID`
- allow stacking with `none` signature (possible, but we can disallow this flow if we want to)

chore: update rosetta pox-4 checks

---

src/tests-2.5/pox-4-rosetta-cycle-phases.ts

skip phase cycle tests

---

.env
src/api/routes/faucets.ts

feat: support multiple STX faucet source accounts

---

docs/api/blocks/get-burn-blocks.example.json
docs/entities/blocks/burn-block.example.json
docs/entities/blocks/burn-block.schema.json
docs/generated.d.ts
src/api/routes/v2/burn-blocks.ts
src/api/routes/v2/helpers.ts
src/datastore/common.ts
src/datastore/pg-store-v2.ts
src/tests/block-tests.ts

Closes https://github.com/hirosystems/stacks-blockchain-api/issues/1960

feat: add total tx count to burn block endpoints

---

src/datastore/pg-store-v2.ts

Stackers missing from the stacker endpoints because the `cycle_id` value in stacker queries was using a string instead of an int, e.g. `'85' + 1 = '851'`

fix: signer stacker query using string instead of int for cycle_id

---

package-lock.json
package.json

Part of fixing https://github.com/stacks-network/stacks-core/issues/5028

fix: support parsing Clarity3 version contract deploy txs

---

CHANGELOG.md

Only change left to merge is CHANGELOG

merge beta into master

---

.env
src/api/routes/core-node-rpc-proxy.ts
src/event-stream/event-server.ts

feat: stacks core event and rpc proxy body limits configurable via env
